### ISSUE TITLE
optimize 'kcm-msm'

### ISSUE THREAD

**Issue by philmmanjaro** [manjaro/release-plan#10]
* it would be great to ship **kcm-msm** within Plasma 5.4
* if possible, depreciate **manjaro-settings-manager 0.4.x**

**Comment by Kirek** [comment]
Issue to be solved before this is possible:
https://github.com/manjaro/manjaro-settings-manager/labels/manjaro%2015.09

**Comment by philmmanjaro** [comment]
I think we should move this to **Capella** in December ...

**Comment by philmmanjaro** [comment]
What is the current status on this one?
