### ISSUE TITLE
Add support for --needed flag in basestrap 

### ISSUE THREAD

**Issue by Chrysostomus** [manjaro/release-plan#100]
I would like basestrap script to forward --needed flag to pacman. It can be useful when scripting cli-installer to avoid unnecessary reinstallations if basestrapping is done in separate stages. 

I can send a pull request if it's okay.

**Comment by Chrysostomus** [comment]
Okay, nobody seems to be very interested in the issue. I'll make some adjustments and send a pull request to the related repo. I would imagine that there are no big objections to it since it should not break or remove any functionality nor cause any extra maintenance work for anyone.

**Comment by philmmanjaro** [comment]
Send a pull request and we check what needs to be changed ...

**Comment by Kirek** [comment]
You should basestrap only once, after that you chroot to this base system and just call pacman to install additional packages...

**Comment by Chrysostomus** [comment]
Maybe, that would be more flexible. The installer I am working with uses multiple pacstrap calls by default, but this could be changed. 

Anyway, I experimented on this and noticed that --needed flag is not really needed. This issue seems to have been unnecessary.
