### ISSUE TITLE
update Calamares slide-show

### ISSUE THREAD

**Issue by oberon2007** [manjaro/release-plan#101]
The screenshots are outdated. Any chance @mcder3 you could provide new ones?

**Comment by mcder3** [comment]
I just need the size of the images and I'll see what I can achieve.

**Comment by philmmanjaro** [comment]
@mcder3: You can check also other distros using [Calamares](https://calamares.io/about/) and on how they used the slide-show function. Using **svg** like [KaOS](https://github.com/KaOSx/calamares/tree/master/src/branding/kaos_branding) does, makes sense. Be creative and have fun with it.

**Comment by mcder3** [comment]
I'll see what I can do these days.

**Comment by mcder3** [comment]
This is the idea that I have at this time.

https://drive.google.com/file/d/0B7tTd_BxrUN3dTR4eDlRNktaQkk/view?usp=sharing

https://drive.google.com/file/d/0B7tTd_BxrUN3alItTGpnMlhuNFE/view?usp=sharing

https://drive.google.com/file/d/0B7tTd_BxrUN3a3p1QTMzNVA0bjA/view?usp=sharing

**Comment by Ste74** [comment]
beautiful , i like if possible see in action ..

**Comment by mcder3** [comment]
I still have to finish a couple of slides to have it complete.

**Comment by Ste74** [comment]
Great.. keep your time :)

**Comment by oberon2007** [comment]
Very nice already, great! :smiley: - I don't have an immediate associaltion with the triangle in the circles...?

**Comment by mcder3** [comment]
Is pure decoration nothing more.

**Comment by philmmanjaro** [comment]
Looks modern and slick.

**Comment by mcder3** [comment]
I hope you like these slides @philmmanjaro @oberon2007  @Ste74 

https://drive.google.com/file/d/0B7tTd_BxrUN3NDBvSURaeVFfVnc/view?usp=sharing

**Comment by oberon2007** [comment]
They are super cool! Great! :) Only suggestion I have is that it would be good to use the maia colored logo, since the launcher aswell as kde system info and **manjaro-hello** now are all using that logo color ;)

**Comment by mcder3** [comment]
Here it is with the green color.

https://drive.google.com/file/d/0B7tTd_BxrUN3cDh2UG1JQ2NTcUE/view?usp=sharing

**Comment by philmmanjaro** [comment]
I've committed it now: https://github.com/manjaro/calamares/commit/a6016c63aa03ba331c14f6328ba6cf4a7a1846b2

**Comment by philmmanjaro** [comment]
Well, we have several issues with the new slideshow.

The **languages.png** needs a transparent background:

![language](https://cloud.githubusercontent.com/assets/5050022/22625115/bab4b5ba-eb8d-11e6-952c-dd50b3733c89.png)

In KDE, when we use theming, we have other dimensions for the slides: 852x544

![slide](https://cloud.githubusercontent.com/assets/5050022/22625120/d71ccd78-eb8d-11e6-9cd6-eff941793331.png)

Similar goes for the XFCE edition: 800x510

![slide2](https://cloud.githubusercontent.com/assets/5050022/22625123/ed8a6e30-eb8d-11e6-92c6-64a1e6298e8c.png)

Would it be possible to have the slides also in **svg**?
We have to check how the other distros handle their slides and how we can make ours more dynamically.

**Comment by mcder3** [comment]
I imagine that even in svg it would deform, since the two measurements are neither 16: 9 or 4: 3

What could be done is to use approximate measures and make the background transparent.

I do not know if it will be possible to change the white background for another color?

**Comment by mcder3** [comment]
SVG Version: https://drive.google.com/open?id=0B7tTd_BxrUN3SDBjMkhwUUFqaG8

I do not know if it will work, but you have to try.

**Comment by mcder3** [comment]
I hope this solves the problem.

https://drive.google.com/file/d/0B7tTd_BxrUN3aWlFRnhZT0J1dmc/view?usp=sharing

**Comment by mcder3** [comment]
Slides for Manjaro KDE version

https://drive.google.com/file/d/0B7tTd_BxrUN3N01NZFlOWnJVQkU/view?usp=sharing

Already with this we would have to have the slides solved @philmmanjaro

**Comment by philmmanjaro** [comment]
@mcder3: the last one looks pretty cool. Can you send me also the SVG graphics of it? I'm playing a little around with the sizes to see if I find some to suit them all possible.

**Comment by philmmanjaro** [comment]
![cal-slide](https://cloud.githubusercontent.com/assets/5050022/22682320/57ac0f96-ed12-11e6-949d-f7adf1432c67.png)

Using the default QT-theme the slide is 800x440px. I'll try to rearrange your slides in a way to check if one size might work with all.

**Comment by philmmanjaro** [comment]
A quick edit can be found [here](https://sourceforge.net/projects/manjarodev/files/users/philm/branding/branding-manjaro.zip/download)

**Comment by mcder3** [comment]
SVG Files https://drive.google.com/file/d/0B7tTd_BxrUN3TVFkMVRtaG1jS00/view?usp=sharing
