### ISSUE TITLE
Arch removes i686 repo in November. We follow?

### ISSUE THREAD

**Issue by Strit** [manjaro/release-plan#103]
As Arch Linux removes the i686 repo's in November 2017, if no maintainer steps up, what do we do come November?

I imagine we also remove i686 from our repo, since they will no longer be updated.
Manjaro-Tools can be rewritten to not include the switch for i686.

Would this be a chance for Manjaro to adopt Manjaro-ARM as an official part of Manjaro Linux?

Just some of the questions and ideas I have at the moment. What do you guys think?

**Comment by jonathonf** [comment]
There would be a (large?) number of people who would be very happy if Manjaro could keep building i686 packages (myself included). Just because the Arch devs don't use 32-bit machines doesn't mean other people don't.

There is some talk on the arch-ports mailing list about "archlinux32": https://lists.archlinux.org/pipermail/arch-ports/2017-February/000756.html. If that doesn't come about, I suspect there would be some Arch users who would also make the switch to Manjaro to keep their 32-bit machines Arch-like.

However, I'm not sure whether we have the infrastructure for major amounts of package building...

**Comment by udeved** [comment]
@jonathonf 

I would be happy to drop i686.
However, we need to make a decision, and bad news is, we don't have infrastructure to fully build packages on our own currently. If we built all packages, it'd certainly have its advantages from non systemd pov.

**Comment by Strit** [comment]
> I think, the main obstacle to include a new arch is boxit.

I agree. Maybe it needs a big rewrite for it to support it.

**Comment by philmmanjaro** [comment]
Our change will be made earlier, according to [plan](Phasing out x86 architecture support in general ).

**Comment by jonathonf** [comment]
We could mirror from http://archlinux32.org/ once they're up-and-running.

I really don't want to lose 32-bit CPU support... 😢

**Comment by udeved** [comment]
@jonathonf 

I problem I see with syncing from an arch community project, we gonna get tons of threads and bug reports for those. Its unclear atm, how the arch-32 project will and can handle it.
I would rather have a separate sibblibg manjaro-32 project with their own boxit server and repos, site etc.

**Comment by Huluti** [comment]
Let's be serious two minutes. Manjaro is based on Arch. When Arch makes such an important decision, I think we have to follow it. Quite simply, we have so much to do that I do not see ourselves getting bogged down in the management of such a thing. Arch is a distribution ahead of this time and in fact we sum it too. 32-bits is almost not-used today and is no longer tested enough. It frees us from a weight. I know some users will be disappointed, but that's life. Other distributions continue to provide this support for a while. Let's move on!

**Comment by ChazyTheBest** [comment]
I like the idea of follow the arch decision and try something like @udeved said, have a separate github account for 32 bits and see if someone steps up to maintain it. I think it's the best path.

Also, there is the possibility to give Manjaro-ARM proper support and officially support it.

**Comment by udeved** [comment]
What I am concerned with, we can't delay a decision much longer.
We need to make a decision on that and do some planning, soon.

**Comment by philmmanjaro** [comment]
We will follow: https://forum.manjaro.org/t/phasing-out-i686-support/30398
