### ISSUE TITLE
[CAL] Do we need some x11 value to apply proper coloring?

### ISSUE THREAD

**Issue by philmmanjaro** [manjaro/release-plan#104]
@Kirek: since we don't use **sudo -E** anymore and **pkexec** instead, at least in **KDE** the colors are not adopted properly. Do we need an [extra x11 value](https://github.com/manjaro/packages-extra/blob/master/polkit/x11vars.patch)?

**Comment by Kirek** [comment]
Not sure, maybe we can go back to use sudo -E https://github.com/manjaro/calamares/commit/d1f3c2d73bb7fbd18b24dc44f1928bcea9cb1fc7

**Comment by Kirek** [comment]
With beta2 release pkexec hat the same odd behaviour as sudo -E, sudo still works properly...
With the patch now is always double click.

**Comment by philmmanjaro** [comment]
@Kirek: the patch exists before also within **polkit**. We used it to have themes applied properly since months now. The diff with **beta2** is now **Plasma 5.9**. **sudo** alone works, but doesn't apply any themes. Therefore the default QT-theme is used. Same goes for **KDE Neon**.

**Comment by Kirek** [comment]
Maybe because in beta1 the default behaviour was double click, pkexec used that even when I changed the manjaro user setting to single click, and because beta2 uses single click as default, pkexec had the same "bug".
Whatever, now with the patch calamares will behave always the same.
Can you update calamares adding that patch? I will do but I don't know what you changed with pkgrel=4, just noticed it's already in the repos https://github.com/manjaro/packages-extra/commit/31cb6bd826d934f16ef91ba0f350979afc4cdeaa

**Comment by philmmanjaro** [comment]
Ya, will do and also update **git repos** as needed.

**Comment by philmmanjaro** [comment]
@Kirek: **sudo -E** provides **QT** the needed **environment variables**, so theming can be applied. **pkexec** however blocks these. Now we have to find out, which variable we are still missing and update our [patch](https://github.com/manjaro/packages-extra/blob/master/polkit/x11vars.patch) so **pkgexec** passes it thru. Using **sudo** isn't the way to go ...

**Comment by Ste74** [comment]
Ot : interesting this pkexec issue ; in gnome in the past i use isousb and this install gksu ( or gksudo i don't remember :p ) . This create a laucher for terminal root and in the exec command it call pkexec etc... well this not work, only if i change in sudo it work :p /Ot

**Comment by philmmanjaro** [comment]
@Ste74: **pkexec** is normally used for **cli** applications. However it seems to be used now also for **gui**. Some of these need some **environment variables** to work properly. **pkexec** is designed to block these. With our patch we have lighten this a little.

**Comment by philmmanjaro** [comment]
Fixed with https://github.com/manjaro/iso-profiles/commit/1f5241c0f90514b867af55462f2a767fb9b7cd53
