### ISSUE TITLE
[plymouth] decide if v0.9 series is the right way to go

### ISSUE THREAD

**Issue by philmmanjaro** [manjaro/release-plan#107]
We have to check if we need to adopt our themes for **plymouth v0.9 series**. At least our default theme doesn't work properly with it. Manjaro logo is somehow missing. Bootup is however faster.

**Comment by udeved** [comment]
I noticed taht too, basically no theme, just black screen until DM login in my test build.

Btw, I'd need access to SF manjarotest to upload lxqt.

**Comment by philmmanjaro** [comment]
@udeved: needed access at SF granted. Can you also check @oberon2007 PR and comment on it?

@Ste74: how did you test the new **plymouth** package from your end? So far it seems to be broken.

**Comment by Ste74** [comment]
Hi have tested in my pc and the new gnome theme : the theme appear normal but in the left corner i can see a cursor (  _  ) but the theme appear only for 3/4 sec after black screen for 1/2 sec ( with progress bar )  and finally the lightdm login ..

**Comment by Ste74** [comment]
In Vbox it work with gnome ( try now with new build )  ; but use this @philmmanjaro https://github.com/manjaro/packages-extra/commit/811c5acfb262c40185746ba2923f923b7e075844 is better for all

**Comment by philmmanjaro** [comment]
Well, what is the purpose to have the **plymouth** package broken? **plymouth-legacy** is my old package with **sddm.service** added as **sddm-plymouth.service** added. So why recommend my old package instead of the package you just have updated?

**Comment by udeved** [comment]
So the new plymouth version needs to be fixed, generally not bad to update to latest release.
Perhaps theme format changed or something? Special background package depend? No clue.

**Comment by udeved** [comment]
gentoo add a 0.9.2 systemd unit patch, just quick glance.
https://github.com/gentoo/gentoo/blob/master/sys-boot/plymouth/files/0.9.2-systemdsystemunitdir.patch

**Comment by udeved** [comment]
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=plymouth

**Comment by philmmanjaro** [comment]
We adopted already all changes made by AUR. I also updated **plymouth-dev** now. Maybe it works better than the 23 months old **v0.9.2**. However **plymouth-legacy** is still the way to go for now.

**Comment by Ste74** [comment]
I don't know why when install in my real system the plymouth-legacy a.k.a. the old plymouth i have the same error mentioned in other post also in launchpad exist this report but with 0.9.2 series : 
https://bugs.launchpad.net/ubuntu/+source/plymouth/+bug/1525699
my error : 

> [stefano@ste74 ~]$ sudo mkinitcpio -p linux49
> [sudo] password di stefano: 
> ==> Building image from preset: /etc/mkinitcpio.d/linux49.preset: 'default'
>   -> -k /boot/vmlinuz-4.9-x86_64 -c /etc/mkinitcpio.conf -g /boot/initramfs-4.9-x86_64.img
> ==> Starting build: 4.9.8-1-MANJARO
>   -> Running build hook: [base]
>   -> Running build hook: [udev]
>   -> Running build hook: [plymouth]
> /usr/lib/initcpio/install/plymouth: riga 7: /usr/sbin/plymouth-set-default-theme: File o directory non esistente
> grep: /usr/share/plymouth/themes//.plymouth: File o directory non esistente
> ==> ERROR: file not found: `/usr/sbin/plymouthd'
> The default plymouth plugin () doesn't exist
> ==> Building image from preset: /etc/mkinitcpio.d/linux49.preset: 'fallback'
>   -> -k /boot/vmlinuz-4.9-x86_64 -c /etc/mkinitcpio.conf -g /boot/initramfs-4.9-x86_64-fallback.img -S autodetect
> ==> Starting build: 4.9.8-1-MANJARO
>   -> Running build hook: [base]
>   -> Running build hook: [udev]
>   -> Running build hook: [plymouth]
> /usr/lib/initcpio/install/plymouth: riga 7: /usr/sbin/plymouth-set-default-theme: File o directory non esistente
> grep: /usr/share/plymouth/themes//.plymouth: File o directory non esistente
> ==> ERROR: file not found: `/usr/sbin/plymouthd'
> The default plymouth plugin () doesn't exist
> [stefano@ste74 ~]$ 

And with the 0.9.2 for me nothing error .. really strange :(

**Comment by philmmanjaro** [comment]
@Ste74: the file is placed in the **bin** folder:
```
phil@manjaro ~ $ pacman -Ql plymouth-legacy | grep bin
plymouth-legacy /usr/bin/
plymouth-legacy /usr/bin/plymouth
plymouth-legacy /usr/bin/plymouth-set-default-theme
plymouth-legacy /usr/bin/plymouthd
```

**Comment by philmmanjaro** [comment]
@Ste74: this should fix the issue: https://github.com/manjaro/packages-extra/commit/c255b1b7bd60afcccff9b812db83dfb69ed7f6f6

**Comment by philmmanjaro** [comment]
Do we see some improvement with **plymouth-dev 0.9.2.r66.g63148b2-1** theme-wise? As the **v0.9.2** version from 2015-03-17 has some regressions, what does the more current git-version do for us? I'm not pleased with shipping a broken package with obvious regressions to **stable branch**.

**Comment by Ste74** [comment]
@philmmanjaro 👍 for the legacy version : now work fine without error , the dev version and gnome plymouth theme is broken : i see only a small squares

**Comment by oberon2007** [comment]
**1:0.9.2** isn't working at all for me on deepin. If I don't do anything booting dies on plymouth with a cursor appearing after a while.
When I keep hitting arrow keys for a while I manage to interrupt plymouth and then I can reach the desktop.
Just downgraded to **1:0.8.8-2** and will see it that one works :wink:

**Comment by oberon2007** [comment]
**1:0.8.8-2** is ok here.

**Comment by philmmanjaro** [comment]
Since we still see issues, I've reverted the package back to **v0.8.8-3**. We can test **v0.9** series within **plymouth-dev** which has a newer git-checkout.
