### ISSUE TITLE
[manjaro] version schema and SF upload 17.0+

### ISSUE THREAD

**Issue by udeved** [manjaro/release-plan#108]
What version schema do we use for 17.0+?

Should we integrate test builds on SF manjarolinux and manjaro-community accounts?
Would simplify deployment, just 2 instead of 4 SF locations.

**Comment by oberon2007** [comment]
Actually there are currently only 3 locations. At the moment we use:
**manjarolinux** for official release and candidates only
**manjarotest** for official testbuilds and
**manjarollinux-community** which has the identical structure as **manjarolinux** plus includes the dev-builds in the "development" directory.

**Comment by oberon2007** [comment]
**manjarotest** is so-to-say the 'development' directory split out to a separate project. Apart from that **manjarolinux** and **manjarolinux-community** are organized identically.

**Comment by oberon2007** [comment]
So I think this is clear now? 17.0 .1 .2 and now 4 projects really ;)
Close this?
