### ISSUE TITLE
Update 'Beginner-Guide'

### ISSUE THREAD

**Issue by philmmanjaro** [manjaro/release-plan#11]
* update to new versioning (#9)
* ~~add guide for calamares (#3)~~
* correct typos and adjust

**Comment by jonathonf** [comment]
If both Thus and Calamares are present, Calamares isn't ready, and Thus is default, I'd rather have just Thus in the guide. Having both will nearly double the number of pages...

**Comment by philmmanjaro** [comment]
Yep, I'm fine with that. So I remove that topic then ...

**Comment by jonathonf** [comment]
OK, so it took longer than I expected to get the rc2 installer iso downloaded... :(

**Comment by philmmanjaro** [comment]
He Jonathon, no problem at all.

**Comment by jonathonf** [comment]
This should do it. https://github.com/manjaro/manjaro-user-guide/commit/763ea5b3b73c4216b92913393f0fc0d7347896fb

**Comment by philmmanjaro** [comment]
Seems I'm unable to compile it with current packages in testing:
```
This is LuaTeX, Version beta-0.80.0 (TeX Live 2015/Arch Linux) (rev 5238) 
 restricted \write18 enabled.
(./manjaro-user-guide.tex
LaTeX2e <2015/01/01>
Babel <3.9l> and hyphenation patterns for 79 languages loaded.

Systemcall.cpp (292): Systemcall: 'lualatex "manjaro-user-guide.tex"' finished with exit code 1
```
