### ISSUE TITLE
Openrc completions

### ISSUE THREAD

**Issue by Chrysostomus** [manjaro/release-plan#110]
Gentoo has zsh completions for openrc: https://github.com/gentoo/gentoo-zsh-completions/blob/master/src/_openrc

Could we port these to manjaro?

**Comment by udeved** [comment]
I would rather have some bash and zsh completions for manjaro-tools, seems more useful to me.

**Comment by Chrysostomus** [comment]
That would be nice too. Are these mutually exclusive?

**Comment by udeved** [comment]
Nope, but I would have no use case for openrc completion.
But perhaps for some typical manjaro-tools commands.

**Comment by Chrysostomus** [comment]
I would like to have rc-update complete service names like zsh completes service names for systemctl command with systemd. It is in no way essential function, just a slight convenience for lazy typists like myself. It could save some time when checking if a particular service is available (openrc support in manjaro-architect is still incomplete, so nowadays I find myself often in situation where I need to check if particular service is disabled or downright not installed).

**Comment by udeved** [comment]
Easy to check on openrc, not much different from systemd.

     [[ -f /etc/init,d/some_svc ]] && do_something

**Comment by Chrysostomus** [comment]
Yes. But more typing than 

      rc-u<tab> add net<tab>

Anyway, the use case is laziness, I don't think there are much better arguments for tab completion. Maybe it could also save some misstypings in rc-update commands?

**Comment by Chrysostomus** [comment]
What kind of completions would be needed for manjaro-tools commands?

**Comment by udeved** [comment]
I am somewhat the wrong guy to ask that.
No errors means no learning, means stand still and recession.

**Comment by Chrysostomus** [comment]
Anyway, afaik, adding the completions should be a matter of of dropping this file: https://github.com/gentoo/gentoo-zsh-completions/blob/master/src/_openrc to this directory: `/usr/share/zsh/site-functions`. Possibly also replacing word gentoo_runlevels with manjaro_runlevels, although that seems to be just a cosmetic issue. 

Maybe we could package it in its own package?

**Comment by philmmanjaro** [comment]
Since we dropped OpenRC this is now obsolete.
