### ISSUE TITLE
packages-sonar, packages-openrc and boxit updates

### ISSUE THREAD

**Issue by udeved** [manjaro/release-plan#111]
Would it be helpful if we put all sonar packages in a separate **packages-sonar** repo?

boxit wishlist:
* sonar pkg repo
* nonsystemd  pkg repo
* qt5 port/rebuild of boxit client
* pkgfile support for pacman (file database for pacman) - done with: https://github.com/manjaro/boxit/commit/67b8a8c8fadc154706cacbbfb00ba8a784d5d64a

**Comment by Ste74** [comment]
You mean all extra binary added by @coffeking ? In the past i suggest to collect all in a subdirectory in the community repo because i don't know all the pkgs of sonar stuff..

**Comment by udeved** [comment]
I mean all sonar related PKGBUILD to move in its own repo.
Its getting confusing, and have all sonar builds in one place may also help sonar guys navigating.

**Comment by udeved** [comment]
@philmmanjaro @Kirek 

Sonar would also be a case to ideally have their own little pkg repo added to boxit server.
Afaik, its already possible to add additional boxit repos.

**Comment by philmmanjaro** [comment]
For most of the stuff we have to modify **boxit**. As of now we don't have the time to do so ...

**Comment by udeved** [comment]
How is a repo created on boxit server?
I'll probably have a test in vbox.

**Comment by philmmanjaro** [comment]
Actually you have to configure which repos should exist. Since we use overlay packages and sync with Arch we are some kind locked to the given repo names by Arch. I never tested if boxit can also manage repositories, which don't exist on Arch side.

**Comment by udeved** [comment]
I think its time for a test? From code side, it looks fine and should support it.

**Comment by udeved** [comment]
Afaik from code, the pkgs get moved to a central pool, and symlinked to branches.

**Comment by philmmanjaro** [comment]
Yes, into [sync](http://repo.manjaro.org.uk/pool/sync/) for Arch based packages and [overlay](http://repo.manjaro.org.uk/pool/overlay/) for our packages. So we have to check what might happen, if there is no sync-based repository ...

**Comment by udeved** [comment]
I was thinking if we can pretend that arch has more repos. by mixing arch and majanro config for the sync dir?

**Comment by philmmanjaro** [comment]
Well, it was not designed to do so. So we have to test it and if needed modify it. Else I've to ask Roland on how to do it. He should be available in about one week ...

**Comment by udeved** [comment]
That would be great. This is a feature which doesn't look connected with too much effort to realize.
The others are more effort in my view.

**Comment by udeved** [comment]
@philmmanjaro 

What do you think moving sonar PKGBUILDs in their own repo, all to be put in community in boxit?

**Comment by udeved** [comment]
https://github.com/manjaro/boxit/commit/67b8a8c8fadc154706cacbbfb00ba8a784d5d64a

👍

**Comment by Ste74** [comment]
@guinux great news.. i see also the delta pkgs ☺
