### ISSUE TITLE
[CAL-unstable] grub uefi error  

### ISSUE THREAD

**Issue by udeved** [manjaro/release-plan#112]
I park the bug report here temporaily, until CAL moved to github issues.

~~~
17:11:10 [0]: Starting job "grubcfg" 
17:11:10 [0]: Running "chroot" ("/tmp/calamares-root-8_rhdip6", "sh", "-c", "which dracut") 
17:11:10 [0]: Finished. Exit code: 1 
17:11:10 [0]: Starting job "bootloader" 
Bootloader: grub (efi)
17:11:10 [0]: Running "chroot" ("/tmp/calamares-root-8_rhdip6", "mkdir", "-p", "/boot/efi") 
17:11:10 [0]: Finished. Exit code: 0 
17:11:10 [0]: Running "chroot" ("/tmp/calamares-root-8_rhdip6", "grub-install", "--target=x86_64-efi", "--efi-directory=/boot/efi", "--bootloader-id=Manjaro", "--force") 
17:11:17 [0]: Finished. Exit code: 1 
17:11:17 [1]: tbMsg "  File &quot;/usr/lib/calamares/modules/bootloader/main.py&quot;, line 309, in run\n    prepare_bootloader(fw_type)\n\n  File &quot;/usr/lib/calamares/modules/bootloader/main.py&quot;, line 283, in prepare_bootloader\n    install_grub(efi_directory, fw_type)\n\n  File &quot;/usr/lib/calamares/modules/bootloader/main.py&quot;, line 220, in install_grub\n    &quot;--force&quot;])\n\n  File &quot;&lt;string&gt;&quot;, line 2, in &lt;module&gt;\n" 
17:11:17 [0]: Installation failed: 
17:11:17 [0]: - message: "Boost.Python-Fehler in Job \"bootloader\"." 
17:11:17 [0]: - details: "<div><strong>&lt;class 'subprocess.CalledProcessError'&gt;</strong></div><div>Command 'grub-install --target=x86_64-efi --efi-directory=/boot/efi --bootloader-id=Manjaro --force' returned non-zero exit status 1.</div><div>Traceback:</div><div><pre>  File &quot;/usr/lib/calamares/modules/bootloader/main.py&quot;, line 309, in run\n    prepare_bootloader(fw_type)\n\n  File &quot;/usr/lib/calamares/modules/bootloader/main.py&quot;, line 283, in prepare_bootloader\n    install_grub(efi_directory, fw_type)\n\n  File &quot;/usr/lib/calamares/modules/bootloader/main.py&quot;, line 220, in install_grub\n    &quot;--force&quot;])\n\n  File &quot;&lt;string&gt;&quot;, line 2, in &lt;module&gt;\n</pre></div>" 
~~~

[![cal-grub-uefi-error.png](https://s14.postimg.org/apma2vivl/cal_grub_uefi_error.png)](https://postimg.org/image/wc1ajwhfx/)

**Comment by philmmanjaro** [comment]
**CAL** already moved to **github issues**. However it will be take a while until somebody will code on **CAL** ...

**Comment by udeved** [comment]
I believe the --force option is the culprit.

Will try again but with deleting previous partitioning.
Perhaps nvram is not cleared?

**Comment by udeved** [comment]
@philmmanjaro 

Is here a break, holiday or something at CAL, or just issue migration period?

**Comment by philmmanjaro** [comment]
Well, you have to reproduce it again and again. Then edit the **python** file and run the same case. Maybe by removing **--force** it might work. However that option is in **CAL** for over 10 months now ...

**Comment by udeved** [comment]
Its the first time I encountered this error on uefi setup.

**Comment by udeved** [comment]
@philmmanjaro 

Pretty interesting.
My second test worked.
However, I removed one drive from vbox config, just a single hdd now.
Before, I had two drives with two manjaro uefi test installs, I was formated.
The failed attempt was on first hdd, with an old auto partition scheme by CAL.
I now manually partitioned, and it worked.

**Comment by udeved** [comment]
Shouldn't the grub-install call show a /tmp/calameres-xyz/boot/efi path?

17:11:10 [0]: Running "chroot" ("/tmp/calamares-root-8_rhdip6", "mkdir", "-p", "/boot/efi") 
17:11:10 [0]: Finished. Exit code: 0 
17:11:10 [0]: Running "chroot" ("/tmp/calamares-root-8_rhdip6", "grub-install", "--target=x86_64-efi", "--efi-directory=/boot/efi", "--bootloader-id=Manjaro", "--force") 
17:11:17 [0]: Finished. Exit code: 1 

The error message on screen doesn't show correct /boot/efi path.
If am right, calamares tries to install in the iso /boot/efi dir.

Will test...

**Comment by udeved** [comment]
I think I finally found the culprit.

https://github.com/manjaro/calamares/blob/development/src/modules/bootloader/main.py#L280

This is wrong, fw_type in global storage is set efi, and we have configured bootloader for grub, but code executes systemd-boot part.

I'll try a fix, if it works, I'll push it as fix, since this module had changes upstream some days ago.

**Comment by udeved** [comment]
Something else going on with efi.
It only effects manual partitioning.
Next test will be without setting flags on partition when manually partitioning.

**Comment by udeved** [comment]
Issue already opened on cal.
