### ISSUE TITLE
Does plymouth create more pain as it should?

### ISSUE THREAD

**Issue by philmmanjaro** [manjaro/release-plan#115]
More and more people post in our forums about **plymouth** issues not able to start **X**. Should we try to remove it completely with **v17.0-rc3** to see the reaction to it?

**Comment by Strit** [comment]
I don't use plymouth myself, as I like to see all the things starting up, and maybe catch something that does not start up correctly, which would otherwise be hidden by plymouth.

**Comment by udeved** [comment]
I am with Strit, if people saw eventual services failing at boot, we'd probably get better reports than just stating "my system doesn't boot"
Connected with this, I would opt to default systemd starting at tty7, like most distros do.
User would simply get login prompt in console, and inexperienced users would still be able to login without asking what to do. Systemd at tty1 looks as if nothing else is possible, no login prompt at tty1 by default.

**Comment by notramo** [comment]
I use Arch Linux. Instead of Plymouth, I use mkinitcpio-archlogo, because I log in in console. I made a custom logo, that has the same geometry as the resolution of the console.
I did the things written here: https://wiki.archlinux.org/index.php/Silent_boot.
Firstly mkinitcpio-archlogo prints the logo to the screen, then systemd prints its output, but if there no error, no additional text will be printed, and you can see only the logo. If there is an error, it is printed.

**Comment by Ste74** [comment]
I have already moved out plymouth from gnome for the future rc3 ( our profile and sonar profile ) . Now moved in the netgroup ( only manjaro profiles ) . GDM and plymouth not are big friends and the advantages are more of disadvantages .

**Comment by polarathene** [comment]
Removing Plymouth would fix one issue I have with my VMs in QEMU, detailed debug on [MHWD issue](https://github.com/manjaro/mhwd/issues/32).

**Comment by udeved** [comment]
https://github.com/manjaro/manjaro-tools/commit/d75095f3e6e7a8f62e6565e1bb7b43b1c75ac716

**Comment by philmmanjaro** [comment]
@udeved: removing **plymouth** support completely makes no sense. It would be better to keep it in and make it **false** by default. For me seems to be a to radical step for now.

**Comment by AlManja** [comment]
As Linux virgin, first thing that impressed me was transparency and all the text scrolling and notifying me what is going on. It was love on first sight! Next I come to Manjaro and Plymouth killed it. First thing I did is decided to remove Plymouth and by doing it I destroyed my Manjaro system. Since then, Plymouth is the enemy. Get rid of it 👍 

>>  I would opt to default systemd starting at tty7, like most distros do. @udeved 

I second this. Confusing for beginners, when they see blank screen. Log in screen would be so much better.

**Comment by udeved** [comment]
@philmmanjaro 

Its noply branch, no worries. If we want to be radical, we merge it.
I suggest we use oackages module by default, and add plymouth optionally.
CAL handles all plymouth activation, and we have a less to worry about.
I like the ide of being radical, plymouth_boot makes it very static and impractical for the many options we have with profiles.

**Comment by philmmanjaro** [comment]
I know that **plymouth** is not or friend. However we have **quiet** in our grub config by default. This also prevents us to show any text scrolling as we had with **v0.8** series of Manjaro. Maybe we rethink that also with our **grub** package. Let me explore the **archlogo** stuff. Maybe we can adopt some of it.

**Comment by udeved** [comment]
I was gonna suggest that also.
I found it to be a strange default to have.

Regarding grub in general, we do have some urgent need to replace uefi loader on iso with grub.
Reason is, without lang kernel parameter, our entire mirror ranking, language stuff doesn't really work in uefi mode.

**Comment by philmmanjaro** [comment]
Forget about my last comment about **archlogo** _Add colored Arch Linux ASCII art logo to early boot process_ It is old and breaks resume hook and also only works for **systemd** ...

**Comment by udeved** [comment]
I referred to the quiet grub default ;)

**Comment by philmmanjaro** [comment]
Ya, I know. So before we change some on the **grub** package, maybe use a **sed** to get rid of **quiet** when **plymouth** is not present. I've to check **CAL** if we have to change some there. Lets try a **v17.0-rc3** without **plymouth** and get the result by it thru feedback.

**Comment by udeved** [comment]
Or should we have a go with uefi syslinux first? Make two branches, for each bootloader and we test what works best?

**Comment by philmmanjaro** [comment]
Why not exploring the options?  **UEFI** is the way to go anyway. All Ryzen CPUs are based on **UEFI** mainboards ...

**Comment by udeved** [comment]
I just read syslinux uefi is sort of unreliable on hardware. Thats the concern.
We just need some uefi loader that can handle language selection.

**Comment by philmmanjaro** [comment]
How does Suse handle it? **gfxboot** is their baby and we use an older version of it. Get an ISO and check it out.

**Comment by udeved** [comment]
IIrc, they use grub for uefi, not sure, its been a while I checked.
Ubuntu use grub, I recently checked.

**Comment by udeved** [comment]
Btw, @philmmanjaro , have you checked the systemd-lxqt-rc2? 
I think it boots pretty fast without mhwd repo and no plymouth.

**Comment by polarathene** [comment]
I'd be happy to try out RC3 with Plymouth removed to see if it fixes a VM driver issue. Could any changes to bootloader like trying Grub on UEFI be delayed to another RC or the next release after 17? Many have been waiting on the 17 release for a while. Would be neat if a boot param can be added to disable MHWD running too if that isn't too much to ask.

**Comment by polarathene** [comment]
I tried out RC3 with VGA(bochs_drm), the errors I've experienced were gone. `/dev/fb0` was not eaten by Plymouth and the extra `/dev/fb` is no longer present. As long as I disable MHWD to avoid vesa being forced on UEFI system it works great!

**Comment by udeved** [comment]
@philmmanjaro 

suse use uefi grub,m I rechecked.

I really like to remove plymouth permanently from buildiso, and if necessry, we add automation at pkg level, so buildiso doesn't have to care about that,

**Comment by philmmanjaro** [comment]
@udeved: sure, makes sense ...

**Comment by udeved** [comment]
So I merge noply branch?
Its nothing but trouble with plymouth, better dealt with at pkg level.

**Comment by oberon2007** [comment]
I was there last year. It's a OneWay. So is pe(a)rl street apparently... :stuck_out_tongue_winking_eye:

![plym](https://cloud.githubusercontent.com/assets/11800714/23486302/a20a3548-fedf-11e6-8a83-9c325a6c8aca.JPG)

:laughing:

**Comment by udeved** [comment]
I'll close this, the overall consensus to the question if plymouth means pain, seems yes, it is.
