### ISSUE TITLE
Release ISO images

### ISSUE THREAD

**Issue by philmmanjaro** [manjaro/release-plan#118]
- [x] XFCE
- [x] KDE
- [x] Gnome
- [x] Cinnamon
- [ ] Deepin
- [x] i3
- [x] LxQT

**Comment by oberon2007** [comment]
i3 is built, tested and uploaded.

**Comment by philmmanjaro** [comment]
@oberon2007: please rebuild so you have **mhwd-db-0.5.9-4** on your ISO. Without it you will have a broken **nvidia** driver not supporting **glx** in live-session and therefore **Calamares** will display a black slideshow during installation when using that driver!

**Comment by Ste74** [comment]
Start now upload of gnome ..

**Comment by oberon2007** [comment]
No problem. the folder is staged right now and I'll just rsync the delta.
Cinnamon on the way now, also.

**Comment by Ste74** [comment]
Gnome is now in the main repo .

**Comment by oberon2007** [comment]
Cinnamon done.

**Comment by philmmanjaro** [comment]
@Ste74: you mean [here](https://sourceforge.net/projects/manjarolinux/files/release/17.0/gnome/)? @oberon2007: should we move it to community project?

**Comment by philmmanjaro** [comment]
Forget about my comment. Seems we made **Gnome** official after all.

**Comment by oberon2007** [comment]
I don't know... :wink: It depends if gnome is an official edition now. I trust @Ste74 a lot, at the same time  know nothing about the Gnome edition and have never tested it. Your decision @philmmanjaro ! :smiley:

**Comment by oberon2007** [comment]
Fine with me :+1:

**Comment by Ste74** [comment]
Yes , i moved in according with your folder structure : deployiso upload gnome in the main folder ..

Edit : i missed anything ? I wrong the announce ? I misunderstanding anything :( ?

**Comment by philmmanjaro** [comment]
@Ste74: all good. @oberon2007: will you be so kind and announce it also in our blog. I'm busy as usual :+1:

**Comment by oberon2007** [comment]
will do. :)

**Comment by udeved** [comment]
@excalibur1234 

You do the systemd lxqt release right?
openrc version is uploaded.

**Comment by rayanshuman** [comment]
What about Manjaro Minimal NET Edition 17.0?

**Comment by udeved** [comment]
We have that covered with lxqt net.

**Comment by philmmanjaro** [comment]
There is a plan to release a new one with **cli** installer. Current image can be found [here](https://forum.manjaro.org/t/experimental-manjaro-architect-test-iso/17661).

**Comment by excalibur1234** [comment]
lxqt systemd is here:
https://sourceforge.net/projects/manjarodev/files/users/excalibur1234/net-lxqt/2017.03/

**Comment by udeved** [comment]
Oh noes, please upload to manjarolinux-community @excalibur1234.
Use deployiso.

**Comment by udeved** [comment]
deployiso -p lxqt -t

Will create a torrent before upload.

**Comment by udeved** [comment]
We have little chaos with too many SF projects and cluttered uploads.
Should we probably send SF a request with some projects to delete? 
Iirc, we can't delete projects ourselves.

**Comment by excalibur1234** [comment]
ok, after some help from artoo is lxqt (systemd) done:
https://sourceforge.net/projects/manjarolinux-community/files/lxqt/17.0/

the file names are missing a "systemd" and the .md5 files can be deleted.

**Comment by udeved** [comment]
It doesn't add systemd in filename, since its default. ;)
We only do it for the yaml files.

**Comment by oberon2007** [comment]
There is something very wrong with these filenames! https://sourceforge.net/projects/manjarolinux-community/files/lxqt/17.0/
Also, the torrents don't belong there, please :wink:

**Comment by udeved** [comment]
The idea of deployiso was to incorporate torrents before upload.
The torrent is fully functional with SF mirror webseeds and @Strit 's tracker.

**Comment by oberon2007** [comment]
I see - just at the moment we appear to have them stored in different locations.

**Comment by udeved** [comment]
Thats why I said, we should centralize the download stuff, too confusing with so many SF projects that have manjaro in heir name. We should try to get rid of as many as possible, so we end up with 3 locations.
One place for iso and torrent, like requested often on forums, but torrents only for releases.

The filename is ok, its only half a lxqt, its a pure netinstall, which allows also console only system, in fact the default selection.

**Comment by udeved** [comment]
Btw, how do we update the latest link download on SF?
Still points to old deepin.

**Comment by oberon2007** [comment]
no idea! normally it updates automatically and picks the newest larger file. I can't find a setting for that anywhere...

**Comment by Strit** [comment]
Regarding the torrents of lxqt, as longa s there are torrents, they are linked to correctly on the download page and it's using the tracker, it's all good. It's just one less I have to manage.

I do agree though, seems to be something missing in the filenames of lxqt.

**Comment by philmmanjaro** [comment]
@excalibur1234 and @udeved: there is no need to re-upload **lxqt**. @oberon2007 or I can move them between projects from shell.

**Comment by philmmanjaro** [comment]
You can define it manually also for latest link in SF. Simply select a common ISO.

**Comment by oberon2007** [comment]
I'm putting Deepin on hold for now... upstream needs to fix a showstopper bug - icon theme cannot be changed currently :stuck_out_tongue_closed_eyes: 
Sofar feedback on all the ISOs is GREAT as far as I've seen! :smiley: 
BRAVO everyone!! :tada: :champagne:

**Comment by excalibur1234** [comment]
here is a proper screenshot of the lxqt edition:
https://s10.postimg.org/d9v3d9fs9/Capture.png
