### ISSUE TITLE
Unify iso booting with grub after 17.0 release

### ISSUE THREAD

**Issue by udeved** [manjaro/release-plan#119]
I have created a grub branch for buildiso.

isolinux and syslinux have been removed, switched to grub to handle bios and uefi booting on iso.

Currently, there is a default grub black/white boot screen.

[![miso_grub.png](https://s28.postimg.org/fu6echkh9/miso_grub.png)](https://postimg.org/image/vsf42mep5/)

What is still to do:

* intensive testing in usb and dvd mode
* a manjaro theme
* language/keymap selection

The resulting iso about 15MB smaller now.

**Comment by Strit** [comment]
Very nice. Doing it Arch style, but with a Manjaro theme:

**Comment by udeved** [comment]
Implementing lang and keymap could prove to be some work.
grub legacy supported gfxboot, but grub2 doesn't.

**Comment by excalibur1234** [comment]
how about memtest?
i regularly use the "resolution" option for livecd in virtualbox. this would also be nice to have (again).

i really like the minimal approach: if it works in grub, we do not need isolinux and syslinux!

**Comment by udeved** [comment]
@excalibur1234 

Its just a playground branch, experimental.
The approach is to use grub-mkrescue, which creates a grub iso, I just added our squash images as of now. Haven't created a memtest entry yet.

Problem: lang and keymap would have to be submenus, for each lang/keymap, one entry 😨 

Suse seem to make attempts to port their gfxboot for grub2.
We have used gfxboot in combination with isolinux/syslinux.
https://hackweek.suse.com/all/projects/gfxboot-for-grub2

**Comment by udeved** [comment]
Closing this, grub is only alternative, and it doesn't support gfxboot

**Comment by papajoker** [comment]
view in this [video](https://www.youtube.com/watch?v=1sMZOBJASkg&t=220) a cool iso menu uefi and bios for the last [siduction](https://forum.siduction.org/)

**Comment by udeved** [comment]
Very nice, they scripted the language and keyboard selection in grub.cfg.
