### ISSUE TITLE
SF manjarolinux structure

### ISSUE THREAD

**Issue by udeved** [manjaro/release-plan#120]
Hasn't this been moved yet?
We now have two different SF trees and deployiso was changed as requested and done on SF community.

Should we clean the archive folders to have fresh start with 17.0? Take all other previous versions offline?

**Comment by oberon2007** [comment]
What do you mean with moved? We now have
**manjarolinux**/**manjarotest** and
**manjaro-community**/**manjarotest-community**
as discussed.

**Comment by udeved** [comment]
Well, manjarolinux SF has old directory structure, making deployiso useless.
I made deployiso as requested, but the structure doesn't match.
If you upload, it will always have to be moved manually in release folder. We should drop this folder and do like community.

**Comment by Ste74** [comment]
Yes , confirm @artoo say : when upload gnome deployiso put it in the main folder , i have move it via shell into release folder ...

**Comment by udeved** [comment]
I can move them out of release folder and create proper structure @oberon2007 
However, eventual download links would need to be fixed to new location.

**Comment by artoo** [comment]
Hey everyone, how can I help?

**Comment by oberon2007** [comment]
Ah of course!

**Comment by udeved** [comment]
Should I move them around?

**Comment by artoo** [comment]
Yes move them around!

**Comment by oberon2007** [comment]
I think now is a bad moment. We don't know where the links have spread with the release. Also right nite noone is uploading anything. Let's do it in a week or so!?

**Comment by artoo** [comment]
Hmm, I really think now is a good moment though. We can't afford it escalating even more.

**Comment by udeved** [comment]
Well, its never a good time to do that. Should have been done before 17.0.
I'd do it rather sooner than later, I can create the new torrents for them.

Btw, we should do a profiles release going along with mt-0.15, its just a cleaned version, removed plymouth and aufs. Wasn't planned, but since we dropped plymouth in middle of release, its better to do such release before 17.0 profile branch gets too many commits.

**Comment by oberon2007** [comment]
Looks like you've invited a new friend, @Ste74 ! 😆

**Comment by artoo** [comment]
![troll](https://cloud.githubusercontent.com/assets/312726/23767622/1e5481b8-0501-11e7-812b-02ac9a1bef79.png)

**Comment by Ste74** [comment]
Ah ah ... my mind is out , i have with flu ... ah ah

**Comment by oberon2007** [comment]
We need stable 17.0 profile packages for the new CLI installer. I'm packaging them right now from stable-17.0 branch. Can we please have -dev packages for mt-0.15 for the new cycle?

**Comment by udeved** [comment]
No, I really dislike dozens of dev packages. For that, we have branches in boxit.

On Arch, I would put 0.15 package in testing, while stable had 0.14, until 0.15 moved stable.
We need this approach on manjaro.

**Comment by oberon2007** [comment]
We need stable profile packages. There's no use in packaged profiles with random everyday changes.
mt-0.15 can be used with git profiles if you don't want them packaged aswell - we use git anyway.

**Comment by oberon2007** [comment]
manjaro-architect uses profiles packages for installation. If we cannot use manjaro-iso-profiles packages for that we'll need dedicated extra packages for that - so, the same amount of packages in the end...

**Comment by udeved** [comment]
master branch is stable.
Plymouth removed.

**Comment by udeved** [comment]
In other words. I took care of the inconsistencies, lets use master, package profiles from master.
I'll do a mt-0.15 release, which is 0.14 minus plymouth and aufs.

**Comment by oberon2007** [comment]
You'll just have to do a pkgrel 2 then. I was just pushing the stable-17.0 packages while we were typing.
My idea was that the packages were supposed to be a snapshot of the current release. Apparently I was wrong.

**Comment by oberon2007** [comment]
ah. actually I didn't hit Enter, yet! :laughing:

**Comment by oberon2007** [comment]
so pkgver 17.0 is still untouched.

**Comment by udeved** [comment]
Profiles? Yes, whatever suits, but please don't do a second set of profile-dev packages.
Its useless and confusing.

**Comment by udeved** [comment]
I'll put mt-0.15 in unstable, and you should put profile packages also only in unstable for now. 
Let them be moved with regular moving.

**Comment by Ste74** [comment]
@oberon2007 but cli installer pull from git so you can set to pull in the right branch .. or not ?

**Comment by oberon2007** [comment]
sure @udeved 
``depends=("manjaro-tools-yaml>=0.15")`` ?
Or no need to specify?

**Comment by oberon2007** [comment]
@Ste74 that's just one option. It's an option, yes.

**Comment by Ste74** [comment]
I will continue to work in the 17.0 branch for mate ..

**Comment by udeved** [comment]
Yes, increase _mt_pkgver=0.15.0 in profiles build @oberon2007

**Comment by udeved** [comment]
I would recommend to port the few commits to master and remove 17.0 branch.

**Comment by oberon2007** [comment]
Let me keep it until I'm able to release Deepin 17.0
iso-profiles pkgs are up now, too.

**Comment by oberon2007** [comment]
Only thing that isn't included in master is @Ste74 's latest commit. If you wouldn't mind Ste, can you just adopt that on stable branch?

**Comment by udeved** [comment]
Ok, but we need profile packages matching in unstable.
Do you want to build them, or should I do now with latest commit?
https://github.com/manjaro/iso-profiles/commit/d6b42ce5267137c0adfe68dba155ef1ad8405e7a

**Comment by oberon2007** [comment]
I'll just rebuild them.

**Comment by Ste74** [comment]
Ok, so guys the commit  only in master branch ?
