### ISSUE TITLE
firefox distribution.ini

### ISSUE THREAD

**Issue by oberon2007** [manjaro/release-plan#123]
Latest Archlinux **firefox** package delivers a **distribution.ini** file, conflicting with the one in **manjaro-browser-settings** ...
https://git.archlinux.org/svntogit/packages.git/commit/trunk?h=packages/firefox&id=f042bdecefce83f18a1383096e3a2f815aa706d0
We can either repackage **firefox** from now on :stuck_out_tongue_closed_eyes: or we need to find a different approach for our customization...
@Kirek ?

**Comment by Kirek** [comment]
I suppose we will need to repackage it... I don't now any alternative clean way to to this.

**Comment by oberon2007** [comment]
I agree. Also because we don't really want to keep Archlinux distribution.ini ...

**Comment by oberon2007** [comment]
We can just use the upstream package and remove the file ... I'll prepare a PKGBUILD

**Comment by Kirek** [comment]
It has this line in the mozconfig 'ac_add_options --with-distribution-id=org.archlinux' dunno if it will break something if it can't find the id.

**Comment by oberon2007** [comment]
ok. lets try ... Would just be great if we wouldn't need to build it ourselves ...

**Comment by oberon2007** [comment]
hm. not so easy unfortunately. It doesn't complain, but the default settings from manjaro distribution.ini are apparently ignored ...

**Comment by oberon2007** [comment]
I'm afraid I don't have a lot of time right now to play with this more. Was just trying to build Archlinux PKGBUILD, but I'm having issues with hg (mercurial)
Do you maybe have the nerve right now to try? I'll push the PKGBUILD and patches to extra repo ...

**Comment by oberon2007** [comment]
https://github.com/manjaro/packages-extra/commit/d5479dcc685cf19c28143c22c75b8f88b0fdc8fe

**Comment by Kirek** [comment]
When I updated firefox-kde with the mercurial changes, the time it takes to download and process all the stuff is insane, at the end I just removed the mercurial changes and built the thing with the tarball as always...

**Comment by philmmanjaro** [comment]
Hmm, we should simply adjust **manjaro-browser-settings** and keep the Arch.INI. Compiling **firefox** just for that is to much effort. If a repackage doesn't help I suggest to keep the original package as it is.

**Comment by oberon2007** [comment]
Seems necessary. Else we'd need to live with Archlinux branding and drop default startpage and favorites - or the only alternative would be to ship a dirty profile with desktop-settings ... not nice :angry:

**Comment by oberon2007** [comment]
Maybe we can just adjust our **distribution.ini**. FF might still accept it as long as it starts with ``id=archlinux`` :wink:

**Comment by oberon2007** [comment]
Sorry, my bad! :wink: Simply replacing the **distribution.ini** does in fact work. I had forgotten that I had installed upstream package with ``--force`` flag :roll_eyes: 
So we can just re-package it next time :+1:
