### ISSUE TITLE
Need Net-Install media, to install manjaro on server

### ISSUE THREAD

**Issue by netroby** [manjaro/release-plan#124]
Hello. i need the latest Net-Install media for 17.03, that can help me install manjaro on server . I am using manjaro both server , and my local laptop. thanks.

**Comment by Strit** [comment]
Not sure there's a net media planned for the next release, but there is an unofficial one named manjaro-architect ISO, which can be found on the forum.

**Comment by udeved** [comment]
Calamares also does the job in pure netinstall configuration.

I'll close this.

**Comment by netroby** [comment]
https://github.com/Chrysostomus/manjaro-architect

Hope manjaro official provided this release as well.

Very need to install for server/vps/cloud

**Comment by Ste74** [comment]
All you need are in our repo . Also the profile to build a manjaro-architect iso is in our repo iso-profiles .

**Comment by oberon2007** [comment]
@netroby You can download the ISOs already from [here](https://sourceforge.net/projects/manjaro-architect/files/architect/dev/)
