### ISSUE TITLE
Remove bumblebee depend from hybrid-intel-nouveau-bumblebee

### ISSUE THREAD

**Issue by udeved** [manjaro/release-plan#127]
According to arch wiki, nouveau doesn't work any longer with bumblebee.

Should we drop bumblebee depend from mhwd-db hybrid-intel-nouveau-bumblebee?
We would also have to remove bumblebee.nouveau.conf from bumblebee package to avoid troubles.

**Comment by philmmanjaro** [comment]
Hmm, ok. We also have to check with **catalyst**. Seems that is now totally broken due the new **libglvnd-mesa** stack.

**Comment by udeved** [comment]
Should I remove it from mwhd-db and bumblebee?

**Comment by philmmanjaro** [comment]
I'd say just wait a little to get some feedback if it is true with the last adjustments. If **bumblebee** and **nouveau** is broken, that can be removed. We may release **mhwd v0.6.0-rc2** or so ...

**Comment by udeved** [comment]
I can confirm, that bumblebee and nouveau does not work any longer.
I fiddled last days on the laptop, where bumblebee was broke after mesa update.

**Comment by philmmanjaro** [comment]
Well, did you reload the settings? Please post to the [thread](https://forum.manjaro.org/t/xorg-mesa-with-libglvnd-support-in-testing-unstable/19366) and ask the community if it is really broken.

**Comment by udeved** [comment]
Btw, if we remove the depend, we should also drop bumblebee from the package name.

Yes, I used old but updated config file, nvidia needs some special new switch to work, we don't have in default config as well

**Comment by philmmanjaro** [comment]
please spin an ISO and check from a fresh media if some is broken to be sure.

**Comment by udeved** [comment]
I don't have the laptop to test the iso over the weekend :(

**Comment by philmmanjaro** [comment]
Did you talk about the **openrc** or **systemd** compiled **bumblebee**? As you have to implement some patches and update **bumblebee** to get it working.

**Comment by udeved** [comment]
I can only refer to wikis and my own experience trying to get bumblebee working again.

~~~
Installing Bumblebee with Intel/Nouveau
Warning: This method is deprecated and will not work anymore. Use the nvidia module instead. If you want nouveau, use PRIME.

Install:

    xf86-video-nouveau - experimental 3D acceleration driver.
    mesa - Mesa classic DRI with Gallium3D drivers and 3D graphics libraries.

Note: If, when using primusrun on a system with the nouveau driver, you are getting:

primus: fatal: failed to load any of the libraries: /usr/$LIB/nvidia/libGL.so.1 
/usr/$LIB/nvidia/libGL.so.1: Cannot open shared object file: No such file or directory

You should add the following in /usr/bin/primus after PRIMUS_libGL:

export PRIMUS_libGLa='/usr/$LIB/libGL.so.1'

If you want, create a new script (for example primusnouveau).
~~~

libgl again ...


Interesting info on gentoo wiki
```

The EDID information is provided to the Intel GPU (Graphics Processing Unit) by specifying its location in the kernel boot parameter:

drm_kms_helper.edid_firmware=edid/1920x1080_clevo_W670SR.bin

If the GRUB2 bootloader is being used, this can be configured in the file /etc/default/grub
FILE /etc/default/grub
```
https://wiki.gentoo.org/wiki/NVIDIA/Optimus

>  Note
> Bumblebee does not work correctly with Nouveau.
https://wiki.gentoo.org/wiki/Hybrid_graphics

**Comment by philmmanjaro** [comment]
https://github.com/manjaro/packages-community/commit/076f38354f2ed4e26421ff84394cf5b399d598c5 I added to get the new folders recognized. On mesa you have to point to **usr/lib/libGL.so.1** which is included in **libglvnd**.

**Comment by udeved** [comment]
@philmmanjaro 

I talk about bumblebee, the openrc version is exactly the same upstream version as we use on systemd, just compiled `--with-pid` instead of `--without-pid`

**Comment by philmmanjaro** [comment]
Your **bumblebee-openrc** is broken. Please adopt to my changes and it may work.

        CONF_DRIVER_MODULE_NVIDIA=nvidia \
        CONF_LDPATH_NVIDIA=/usr/lib/nvidia:/usr/lib32/nvidia:/usr/lib:/usr/lib32 \
        CONF_MODPATH_NVIDIA=/usr/lib/nvidia/xorg,/usr/lib/xorg/modules \

**Comment by udeved** [comment]
Funnily, its not broken, it works. Afaik, my build has no lib32 path atm.

**Comment by udeved** [comment]
@philmmanjaro 

    Option "ProbeAllGpus" "false"

I think this one is missing from xorg.conf.nvidia if bumblebee is setup with nvidia driver.

**Comment by philmmanjaro** [comment]
These are your configs:

		CONF_DRIVER_MODULE_NVIDIA=nvidia \
		CONF_LDPATH_NVIDIA=/usr/lib/nvidia:/usr/lib32/nvidia \
		CONF_MODPATH_NVIDIA=/usr/lib/nvidia/xorg/,/usr/lib/xorg/modules \

No wonder that **nouveau** doesn't work as you never source the **mesa** folders. Also some **nvidia** libs are now to be found in **/usr/lib\{32\}**. If `ProbeAllGpus` is needed I don't know.

**Comment by udeved** [comment]
`ProbeAllGpus` is required on some lenovo laptops, or else you get black screen.
https://wiki.gentoo.org/wiki/Lenovo_ThinkPad_T440s

The arch bumblebee package has this commented in xorg.nvidia.conf

```
#   Setting ProbeAllGpus to false prevents the new proprietary driver
#   instance spawned to try to control the integrated graphics card,
#   which is already being managed outside bumblebee.
#   This option doesn't hurt and it is required on platforms running
#   more than one nvidia graphics card with the proprietary driver.
#   (E.g. Macbook Pro pre-2010 with nVidia 9400M + 9600M GT).
#   If this option is not set, the new Xorg may blacken the screen and
#   render it unusable (unless you have some way to run killall Xorg).
    Option "ProbeAllGpus" "false"
```

Regarding bnouveau, well, I had mesa path set, it doesn't work, at least it did not on the lenovo laptop.

Arch wiki says, it does not work, gentoo say the same, and remove xorg.nouveau.conf in their git build.

**Comment by udeved** [comment]
What I would like to test next, if the default bumblebee package really has a hard requirement to turn off pid creation. Would simplify thingy drastically.

**Comment by udeved** [comment]
https://github.com/Bumblebee-Project/Bumblebee/issues/773

**Comment by philmmanjaro** [comment]
**/usr/lib\{32\}** is needed for the **nvidia** driver to get working properly. **nouveau** seems only to work with [prime](https://wiki.archlinux.org/index.php/PRIME) nowadays ...

**Comment by udeved** [comment]
Yes, we need to drop nouveau from bumblebee.

Regarding bumblebee package, I think the default package can be also compiled `--with-pid` and we can shared the same package.

**Comment by udeved** [comment]
hybrid-intel-nouveau-bumblebee -> hybrid-intel-nouveau-prime

**Comment by philmmanjaro** [comment]
@udeved: makes sense to create the prime version of it. :smile:

**Comment by udeved** [comment]
We need several prime mhwd db entries.

I couldn't resist, but can't test today.

~~~
# mhwd Driver Config

NAME="video-hybrid-intel-nouveau-prime"
INFO="Hybrid bumblebee solution for NVIDIA Optimus Technology - Open source nouveau & intel video driver."
VERSION="2017.03.26"
FREEDRIVER="true"
PRIORITY="6"

# NVIDIA cards
CLASSIDS="0300 0302"
VENDORIDS="10de"
DEVICEIDS="*"

# Intel cards
CLASSIDS="0300"
VENDORIDS="8086"
DEVICEIDS="*"
BLACKLISTEDDEVICEIDS="0be1 8108"

# Conflicts with other mhwd configs
MHWDCONFLICTS="video-intel video-nouveau video-hybrid-intel-nvidia-bumblebee video-hybrid-intel-nouveau-bumblebee"

# Dependencies
DEPENDS="xf86-video-nouveau xf86-video-intel"

XORGFILE="/etc/X11/mhwd.d/intel.conf"
PXORGFILE="/etc/X11/mhwd.d/10-prime.nouveau.conf"

make_prime_xorg_config()
{
    MHWD_HEADING "${PXORGFILE}"
    # Discrete Card as Primary GPU

    MHWD_ADD_DEVICE_SECTION_FOR_EACH_BUSID "nouveau" "${PXORGFILE}" 10de
    echo 'Section "Screen"' >> "${PXORGFILE}"
	echo '    Identifier     "Screen0"' >> "${PXORGFILE}"
	echo '    Device         "Device0"' >> "${PXORGFILE}"
	echo 'EndSection' >> "${PXORGFILE}"
}

post_install()
{
	# Create intel xorg configuration with enabled sna acceleration method
	MHWD_HEADING "${XORGFILE}"
	MHWD_ADD_DEVICE_SECTION_FOR_EACH_BUSID "intel" "${XORGFILE}" 8086 "Option      \"AccelMethod\" \"sna\""
	MHWD_ADD_DRI "${XORGFILE}"
	MHWD_ADD_COMPOSITING "${XORGFILE}"
	MHWD_ADD_BACKSPACE "${XORGFILE}"

	# Enable next generation of DRI
	sed -i /'Section "Device"'/,/'EndSection'/s/'EndSection'/"\tOption \"DRI\" \"3\"\nEndSection"/g "${XORGFILE}"

	# Create nouveau bumblebee xorg configuration
	make_prime_xorg_config

	# Unload modules if X is not running
	if [ ! "$(pgrep X)" ];	then
		rmmod -f nouveau
	fi

	mhwd-gpu --setxorg "${XORGFILE}"
}

post_remove()
{
	if [ -e "${XORGFILE}" ]; then
		rm "${XORGFILE}"
	fi

	mhwd-gpu --check
}
~~~

Just raw approach.

**Comment by udeved** [comment]
@philmmanjaro 

We should really think about implementing mhwd prime/nouveau in 17.0.1.
Current situation is not good, with broke bumblebee in combination with nouveau.

**Comment by philmmanjaro** [comment]
@udeved: builds are already done. We can track this for **v17.0.2** or so. Did we test that new config already?

**Comment by udeved** [comment]
nope. 
Perhaps at least remove mhwd-hybrid-bumblebee-nouveau in 17.0.1?

**Comment by philmmanjaro** [comment]
**v17.0.1** is built and released. Currently uploading it. Target will be with **v17.0.2** on this ...

**Comment by udeved** [comment]
Ok, I would file it urgent to address asap after .17.0.1

**Comment by philmmanjaro** [comment]
@udeved: did you had time to test your **video-hybrid-intel-nouveau-prime** config yet?

**Comment by udeved** [comment]
Not yet...

**Comment by philmmanjaro** [comment]
Still no test cycles on the new config you created? Maybe ask in our forums for additional feedback.

**Comment by udeved** [comment]
I don't get the display going when mwhd writes the config files, so far it end in black screen.
Haven't had time to further test, in not my laptop, and I can only break it if my mom is away and there is a chance to test.
I myself don't have a laptop with optimus.

**Comment by udeved** [comment]
@philmmanjaro 

I'll have the chance to get my hands on the bumblebee laptop this weekend. Hopefully, I'll complete the task in time.

**Comment by philmmanjaro** [comment]
@udeved: no pressure. Please also include our community ...

**Comment by udeved** [comment]
Ok, there is also a nouveau bug open, major one.

I still have trouble with basically a xorg conf file, whereas it simply runs out of box without placing a file.
I have this suspicion since some time, since arch changed libgl, that we could generally drop almost all of mhwd, and just leave the pure hw detection, let the rest be done by package management.
