### ISSUE TITLE
mt-0.15.2 release

### ISSUE THREAD

**Issue by udeved** [manjaro/release-plan#128]
- [x] tag release
- [x] release tools and depending packages to unstable branch
- [x] update git iso-profiles
- [x] rebuild iso-profile packages
- [x] move manjaro-tools to testing branch
- [x] move grub-theme-live to testing branch
- [x] move manjaro-live to testing branch
- [x] move manjaro-tools to stable branch
- [x] move grub-theme-live to stable branch
- [x] move manjaro-live to stable branch

**Comment by philmmanjaro** [comment]
Since we dropped **v0.15.1** and moved on to **v0.15.2** I updated our todo list :smile:
