### ISSUE TITLE
decide if we drop 'flashplugin' from our official install medias

### ISSUE THREAD

**Issue by philmmanjaro** [manjaro/release-plan#13]

**Comment by offa** [comment]
You'll see the answer [here](https://cve.mitre.org/cgi-bin/cvekey.cgi?keyword=flash+player).

**Comment by Esclapion** [comment]
I removed it from my ISO, but after I searched for a video : the first two sites found needed it.

Speedtest also need it. Now, I keep it.

**Comment by philmmanjaro** [comment]
The security issues are well known. However this is more regarding usability. Most will install it anyway. Those who don't needed it will uninstall. So we are user-friendly or act more on security. 100% you can't guarantee that your install media is bulletproof secure ...

**Comment by oberon2007** [comment]
When I think of the typical Linux reviews - I think they will do exactly what Esclapion did: Open a few homepages, try to load some videos and then say, the release is not working or at least incomplete...

**Comment by Kirek** [comment]
Sadly, flash is still needed in a lot of pages, I think we should keep it.

**Comment by philmmanjaro** [comment]
**15.09-rc1** has it pre-installed, still ;)

**Comment by SolarAquarion** [comment]
yes.  We can use freshplayer.  Which supports the chromium versions of flash

**Comment by jonathonf** [comment]
FreshPlayer has its own issues. For example, Firefox won't know if the Pepper Flash version is out of date. It would also rely on either:

1. The user updating AUR packages (which is disabled by default for new users), or
2. Manjaro adopting ```freshplayerplugin``` and ```chromium-pepper-flash``` into the repos.

I would err on the side of keeping the official Flash Player until it officially dies. YouTube doesn't need it any more, ad networks aren't taking Flash-based ads any more, and Chrome will now start to ignore Flash content. The end of Flash is coming (slowly) - we shouldn't perpetuate it.

**Comment by nodeg** [comment]
In my opinion security is more important than user friednlyness. Many websites moved to HTML 5 and nearly all videos on youtube are playable without flash.

**Comment by philmmanjaro** [comment]
On the official release editions we keep **flashplugin** due usabilty ....

**Comment by alexara** [comment]
Most important websites are usable without flash by now. And having a look at the bug / security statistic of last year the security arguments overweights the usability by far.

>   August 11, 2015 Fixed 34 bugs
>     July 14, 2015  Fixed 2 bugs
>     July 8, 2015  Fixed 36 bugs
>     June 23, 2015  Fixed one bug
>     June 9, 2015  Fixed 13 bugs
>     May 13, 2015  Fixed 18 bugs
>     April 14, 2015  Fixed 22 bugs
>     March 12, 2015  Fixed 11 bugs
>     February 5, 2015  Fixed 15 bugs
>     January 27, 2015  Fixed 2 bugs
>     January 22, 2015  Fixed 1 bug
>     January 14, 2015  Fixed 9 bugs
> 
> This adds up to 164 bug fixes so far in 2015, a year that was 223 days old when the last group of patches were released on the 11th. In round numbers, this comes out to 1 bug fix every 33 hours for 2015.
> 
> Or, five a week.

Source: http://www.computerworld.com/article/2971721/security/stop-the-flash-madness-5-bugs-a-week.html

Why don't you make it optional as opt in? Give the user the choice whether he likes to install 3rd party codecs like mp3 etc. or flash when he/she installs the system.

Alex

**Comment by Ste74** [comment]
Hi guys firefox 49 is near https://wiki.mozilla.org/RapidRelease/Calendar and in this version flash is totally dropped ... do you think if also drop in our iso's ?

**Comment by philmmanjaro** [comment]
Since Adobe keeps it again in sync with Windows, should we still consider to drop it?

**Comment by Ste74** [comment]
Good question ... i don't understand this step by Adobe .. flash is old tecnology, html5 the future ... but at the moment if adobe maintain again flash the problem for security is solved ...

**Comment by Huluti** [comment]
If adobe maintains flash, the question is to see if it's a package wanted by the comunnity?

**Comment by Strit** [comment]
I know I don't use Flash, but a lot of new comers might expect it, since it's what they are used to from Windows. Many popular sites still use flash and will probably not drop it in the next release cycle.

**Comment by alexara** [comment]
> if adobe maintain again flash the problem for security is solved ...

Adobe had released security updates for the old Linux Flash plugin  from time to time, which however never meant that Flash had been secure at any time!
Whenever a few critical bugs were fixed, new ones were already discovered and this cycle endures until now and problably until Flash will finally be buried.

**Comment by jonathonf** [comment]
As far as I can tell, Adobe's latest updates to the Linux FlashPlayer are just an attempt to keep it from being consigned to the dustbin of history.

I'd say drop it. It's easily available to install should users need it - just as Java and its associated plugin is.

Or - add it as an option to the installer similar to Ubuntu's "restricted extras" option.

**Comment by ChazyTheBest** [comment]
+1 drop flashplugin and Java too (yes, it comes preinstalled). These programs don't come with Windows and users have to manually install them, so why do we provide them? It's not an standard nor basic package. Just saying.

**Comment by philmmanjaro** [comment]
So we toss **flashplugin** for good?

**Comment by Huluti** [comment]
I think it's the best decision.

**Comment by Ste74** [comment]
FF blacklist it .. we ship our iso with FF so ... and 
https://tessla.org/mozilla-blocks-versions-adobe-flash-plugin-firefox/

**Comment by philmmanjaro** [comment]
https://github.com/manjaro/iso-profiles/commit/bad338fa77a05224692f05c2e246de375b9b0c42

**Comment by Kirek** [comment]
ff don't blacklist it, it blacklist all npapi plugins BUT flashplugin, also is still used in many many pages... I think it's a step back in usability.

**Comment by philmmanjaro** [comment]
It is always a question of usability vs. security. If we "drop" it and the community wants it badly back we can reconsider. Let's see what might happen ...

**Comment by Kirek** [comment]
The community here are mostly powerusers, they don't care about flashplugin since forever, but we should think about all users. Also security is not an issue, mozilla already automatically disables flashplugin if you are using and old version with known vulnerabilities.

**Comment by philmmanjaro** [comment]
Yah, I know. However the [community thinks similar](https://forum.manjaro.org/t/should-the-flash-player-be-installed-by-default-on-manjaro/16870/) as already discussed within here. With **Pamac** it is simply installed if needed. So to say: only one click away :smiley_cat:
