### ISSUE TITLE
drop hexchat desktop launcher?

### ISSUE THREAD

**Issue by oberon2007** [manjaro/release-plan#130]
Currently [desktop-items script](https://github.com/manjaro/manjaro-tools-livecd/blob/master/bin/desktop-items.in#L41) creates a hexchat launcher on the desktop by default.
The idea of course was to provide easy access to IRC support from the live environment.
Is there still 'official' support going on on IRC? I don't know at all because I don't use IRC at more. But as I read a while ago it looks like Ringo is not active there any more, or is he? And apparently there was a lot of trollling going on on the Manjaro channel.
In any case if no one knows and none of the team is active there, I think we should drop the desktop launcher.

**Comment by Strit** [comment]
IRC does still provide users with support most of the day. It depends on when people are active.
Dodgejcr and I are probably the most active close-to-team members active. Other than us there are a multitude of long time users also providing support.

**Comment by oberon2007** [comment]
Ah great! That sounds very reassuring 👍 Then lets of course keep the launcher 😉 !
