### ISSUE TITLE
re-consider pacman-mirrors live service

### ISSUE THREAD

**Issue by oberon2007** [manjaro/release-plan#131]
Should pacman-mirrors service on the ISOs be adjusted after latest **pacman-mirrors** development?
To me it looks like nowadays option ``-f 10`` would be more useful than ``--geoip``?
@fhdk @Kirek @udeved

**Comment by fhdk** [comment]
Especially when --geoip mirrors point to not so frequently updated mirrors :)

Otherwise I have no opinion :smiley_cat:

**Comment by excalibur1234** [comment]
i agree. i would stay conservative and use option` -f 20`

the last time i have edited the live service, i added a sync:
https://github.com/manjaro/manjaro-tools-livecd/pull/27/files
artoo recommended to [add octopi-notifier instead of syncing](https://github.com/manjaro/manjaro-tools-livecd/pull/27), but this failed in some cases (i experienced it once and some users complained about it not working). unless somebody has a good reason not to do this, i recommend to add a mirror sync.

**Comment by udeved** [comment]
No, please don't add sync to boot script.
We should find a way then to sync after login in ui session.

**Comment by excalibur1234** [comment]
just a clarification:
the [systemd service i have edited](https://github.com/manjaro/manjaro-tools-livecd/blob/master/data/sd/mirrors-live-net.service) runs when there is an established internet connection.
it is not necessarily been executed before login or during boot.

**Comment by oberon2007** [comment]
Why not just in the existing  service we are already using replace ``-m random --geoip`` with ``-f 10`` then?
It should be faster than what we have now and most likely the result will even be better.

**Comment by udeved** [comment]
I am fine with fasttrack, regarding mirrors-live scripts.

     pacman-mirrors -f 5

no other args required.

I would also go for 5 mirrors.

**Comment by oberon2007** [comment]
If I have understood correctly a higher number of mirrors doesn't mean that it takes longer but it would increase the likelihood of including faster or more updated mirrors? In that case 10 or even higher would not hurt...

**Comment by fhdk** [comment]
The higher number gives a higher possibility of a responsive mirror.
The higher number - it will take longer - worst case timeout/mirror.

Only mirrors which in repo.manjaro.org/status.json has branches = [1, 1, 1] are considered using fasttrack so they as up2date as status.json delivers them.

**Comment by oberon2007** [comment]
Ok, sorry, so I misunderstood again :wink: In that case 20 is maybe not such a good idea on an ISO. 10 or 5 maybe is reasonable. We just need to try one or the other and then see how it works out and what the feedback will be.

**Comment by oberon2007** [comment]
After some more local testing I suggest we give it a try with -f 5. It seems to take roughly the same amount of time than with geoip. As soon as I try with 6 or higher I do get the feelling that it begins to take longer. I understand that it will be different depending on where you are, but lets just try with 5 and listen to user feedback  to that.
Btw @philmmanjaro does anything contradict forwarding **pacman-mirrors** to stable branch? Or is another stable snapshot immanent anyway?

**Comment by oberon2007** [comment]
Seems to work fine on latest ISOs. :+:
