### ISSUE TITLE
Adjust tools for ARM architecture

### ISSUE THREAD

**Issue by philmmanjaro** [manjaro/release-plan#135]
- [ ] remove all code related to x86 architecture
- [ ] add new code for ARM architecture
- [ ] adjust profiles for tablets
- [ ] adjust profiles for supported phones
- [ ] create prototype images for internal testing

**Comment by TiberiumN** [comment]
Finally! This shitty x86 arch is so old!

**Comment by ShalokShalom** [comment]
April fools day

**Comment by TiberiumN** [comment]
@ShalokShalom no, you're wrong.
x86 is deprecated and hard to maintain

**Comment by philmmanjaro** [comment]
Part of yesterdays April's fool day. Got ya :smile_cat:
