### ISSUE TITLE
Finish transition to our new logo

### ISSUE THREAD

**Issue by Huluti** [manjaro/release-plan#137]
- [x] GitHub logo
- [x] Official site
- [x] Wiki
- [x] Manjaro Bug tracker
- [x] Vimeo

**Comment by philmmanjaro** [comment]
It would be great to collect all links to logos we have to change and create alternatives for them.

**Comment by Huluti** [comment]
Like this ?

- https://github.com/manjaro
- https://manjaro.org/wp-content/uploads/2013/11/logo_header_transparent.png
- https://manjaro.org/wp-content/uploads/2013/01/logo_comfortaa_small_180px.png
- https://wiki.manjaro.org/logo.png
- https://bugs.manjaro.org//logo_header_transparent.png
- https://i.vimeocdn.com/portrait/4270866_300x300

**Comment by Huluti** [comment]
In addition, we often have two different logos: one with the maia color and the other with the green color. Should not we choose one?

**Comment by philmmanjaro** [comment]
Ya, we should choose one. Since we have most of the logos now identified, we have to create similar to replace them.

**Comment by Huluti** [comment]
How can we choose one ? Organize a vote ?

**Comment by philmmanjaro** [comment]
From Coloring we should use the standard green one. For each logo we have to create a similar one. Maybe ask one of our graphical artists to achieve that.

**Comment by Huluti** [comment]
For now, there is a mix of the two logos. Why ask to a designer? We just have to replace them with the standard logo.

**Comment by philmmanjaro** [comment]
Well, somebody had to create the new files with the current logo. When ready we can replace them ...

**Comment by Huluti** [comment]
For example, for Github replace the current image with this: https://github.com/manjaro/artwork-logo/blob/master/logo.png. Same for  the wiki and Vimeo.
For the favicon of bug tracker, just use same icon as https://forum.manjaro.org.
The only image to recreate is (bug tracker and manjaro.org): https://manjaro.org/wp-content/uploads/2013/11/logo_header_transparent.png

**Comment by philmmanjaro** [comment]
@Tids can you do here some magic?

**Comment by oberon2007** [comment]
You mean, just like this?
![logo_header_transparent_bkg](https://cloud.githubusercontent.com/assets/11800714/26521588/8938c31c-42ec-11e7-84f0-a8b10cf76cfd.png)

**Comment by philmmanjaro** [comment]
@oberon2007: exactly. Send me the file or upload it somewhere and I'll change them ...

**Comment by oberon2007** [comment]
emailed to you.

**Comment by philmmanjaro** [comment]
Ok, This [logo](https://manjaro.org/wp-content/uploads/2013/01/logo_comfortaa_small_180px.png) also needs an edit ...

**Comment by oberon2007** [comment]
emailed, too ;)

**Comment by Huluti** [comment]
Don't forget the favicon too ;)

**Comment by philmmanjaro** [comment]
Seems for the wiki I need it bigger ...

**Comment by oberon2007** [comment]
You mean the one in the top left corner? The header already looks good, doesn't it?

**Comment by oberon2007** [comment]
I'll send you a 72x72.png

**Comment by oberon2007** [comment]
Ah wait. I see now, it has some padding...

**Comment by oberon2007** [comment]
on the way.

**Comment by philmmanjaro** [comment]
I already use a different one. Check the wiki

**Comment by oberon2007** [comment]
hm, yeah. Not too big now? 😉

**Comment by oberon2007** [comment]
The round one under >Getting Started>Manjaro Overview is a bit more tricky to adjust because of the gradient background ... Do you maybe still have the svg somewhere? Is it from an icon set? Or did David create it especially for the purpose?

**Comment by oberon2007** [comment]
Ah. I can do it, it's not so difficult as I thought.

**Comment by oberon2007** [comment]
comming your way:

![manjaro](https://cloud.githubusercontent.com/assets/11800714/26522881/859f6710-430a-11e7-887b-8bc591713c90.png)

**Comment by philmmanjaro** [comment]
Should be fine now. Please check if I missed some ...

**Comment by oberon2007** [comment]
looking good!
