### ISSUE TITLE
[bumblebee] please kill --without-pid

### ISSUE THREAD

**Issue by udeved** [manjaro/release-plan#138]
I would love to see `--without-pid` killed in the bumblebee PKGBUILD.

Reason is, I would really like to use the default bumblebee package on openrc too, but it would need to create a simple pid file, which is deactivated.

Please, lets have it a go with pid in unstable and testing to see if it effects systemd in any negative way.
I can't really imagine a pid file confuses systemd, gentoo have it in in on systemd.

**Comment by jonathonf** [comment]
Have you tested the changes initially before it gets pushed out to users?

**Comment by udeved** [comment]
Not yet, but since I don't have a systemd laptop, I think unstable is optimal ground to get feedback from multiple people.
These hybrid cards appear to be troublesome, depending on manufacturer.

I just notice, gentoo don't deactivate pid in their systemd builds.
I guess they would if it caused trouble. After all, other stuff still use pid on systemd too.

**Comment by udeved** [comment]
@jonathonf 

https://github.com/gentoo/gentoo/blob/eca95e70409810b07a07795df3e4a020118479ac/x11-misc/bumblebee/bumblebee-3.2.1.ebuild

They just have a "shared" bumblebee package for any init system.

**Comment by udeved** [comment]
Does no one have about 10 mins time to test bumblebee on systemd --with-pid enabled?

Would be very nice if we had a shared bumblebee package, which is sort of troublesome by default.
