### ISSUE TITLE
Remove LightFirefox from our repo 

### ISSUE THREAD

**Issue by Ste74** [manjaro/release-plan#139]
LightFirefox seem abandoned .. Last edition is 49 so i think for security reason better if remove from repository . @Chrysostomus you use this pkgs in bspwm profiles ..

**Comment by philmmanjaro** [comment]
I agree with this decision ...

**Comment by Ste74** [comment]
Done 
https://github.com/manjaro/packages-community/commit/6400706fa011fda7f91402ecefae200f86529823
@Chrysostomus : i have removed lightfirefox from your bspwm profile and add palemoon
https://github.com/manjaro/iso-profiles/commit/39d5c0a1ee0153c49e97ea2b648db8a959ce971c

**Comment by Chrysostomus** [comment]
Okay, I think I need to use epiphany or midori to avoid the gtk2 dependency now. Any other suggestions?
