### ISSUE TITLE
Please actually compile a Kernel correctly for Wifi usage....

### ISSUE THREAD

**Issue by NovaCygni** [manjaro/release-plan#140]
Considering I reported this YEARS ago,,, what the hell are you guys playing at? Your still NOT compiling the Kernels with 'CONFIG_ATH_USER_REGD' OpenWRT patch, thus people are STILL having the EEPROM issue of:
Starting of with 
```
country GB: DFS-ETSI
        (2402 - 2482 @ 40), (N/A, 20), (N/A)
        (5170 - 5250 @ 80), (N/A, 20), (N/A), AUTO-BW
        (5250 - 5330 @ 80), (N/A, 20), (0 ms), DFS, AUTO-BW
        (5490 - 5710 @ 160), (N/A, 27), (0 ms), DFS
        (57000 - 66000 @ 2160), (N/A, 40), (N/A)
```
Then doing "sudo iw reg set JP", (* or Any other regdom, even if specified with country code number instead ie, 60, or 67 *): will result in:
global
```
country 98: DFS-UNSET
        (2402 - 2482 @ 40), (N/A, 20), (N/A)
        (2474 - 2482 @ 8), (N/A, 20), (N/A), NO-OFDM
        (5170 - 5250 @ 80), (N/A, 20), (N/A), AUTO-BW
        (5250 - 5330 @ 80), (N/A, 20), (0 ms), DFS, AUTO-BW
        (5490 - 5710 @ 160), (N/A, 23), (0 ms), DFS
        (59000 - 66000 @ 2160), (N/A, 10), (N/A)

```
The problem is easily spotted: The EEPROM is resetting to whatever country the Wireless card was sold from and ignoring the USER SET DETAILS... please, after 2 fuckin years, can you AT LEAST COMPILE THE KERNELS with the CORRECT PATCHES -.-
```
[    6.285400] cfg80211: Calling CRDA to update world regulatory domain
[    7.054075] cfg80211: World regulatory domain updated:
[    7.054081] cfg80211:  DFS Master region: unset
[    7.054081] cfg80211:   (start_freq - end_freq @ bandwidth), (max_antenna_gain, max_eirp)
[    7.054085] cfg80211:   (2402000 KHz - 2472000 KHz @ 40000 KHz), (N/A, 2000 mBm)
[    7.054087] cfg80211:   (2457000 KHz - 2482000 KHz @ 40000 KHz), (N/A, 2000 mBm)
[    7.054089] cfg80211:   (2474000 KHz - 2494000 KHz @ 20000 KHz), (N/A, 2000 mBm)
[    7.054091] cfg80211:   (5170000 KHz - 5250000 KHz @ 80000 KHz), (N/A, 2000 mBm)
[    7.054093] cfg80211:   (5735000 KHz - 5835000 KHz @ 80000 KHz), (N/A, 2000 mBm)
[    7.054095] cfg80211:   (57240000 KHz - 63720000 KHz @ 2160000 KHz), (N/A, 0 mBm)
[    7.054119] cfg80211: Calling CRDA for country: JP
[    7.068527] cfg80211: Regulatory domain changed to country: JP
[    7.068555] cfg80211:  DFS Master region: JP
[    7.068555] cfg80211:   (start_freq - end_freq @ bandwidth), (max_antenna_gain, max_eirp)
[    7.068558] cfg80211:   (2402000 KHz - 2482000 KHz @ 40000 KHz), (N/A, 2000 mBm)
[    7.068560] cfg80211:   (2474000 KHz - 2494000 KHz @ 20000 KHz), (N/A, 2000 mBm)
[    7.068562] cfg80211:   (4910000 KHz - 4990000 KHz @ 40000 KHz), (N/A, 2300 mBm)
[    7.068564] cfg80211:   (5030000 KHz - 5090000 KHz @ 40000 KHz), (N/A, 2300 mBm)
[    7.068566] cfg80211:   (5170000 KHz - 5250000 KHz @ 80000 KHz), (N/A, 2000 mBm)
[    7.068567] cfg80211:   (5250000 KHz - 5330000 KHz @ 80000 KHz), (N/A, 2000 mBm)
[    7.068569] cfg80211:   (5490000 KHz - 5710000 KHz @ 160000 KHz), (N/A, 2300 mBm)
[   35.219154] cfg80211: Calling CRDA for country: GB
[   35.224197] cfg80211: Regulatory domain changed to country: GB
[   35.224200] cfg80211:  DFS Master region: ETSI
[   35.224204] cfg80211:   (start_freq - end_freq @ bandwidth), (max_antenna_gain, max_eirp)
[   35.224208] cfg80211:   (2402000 KHz - 2482000 KHz @ 40000 KHz), (N/A, 2000 mBm)
[   35.224212] cfg80211:   (5170000 KHz - 5250000 KHz @ 80000 KHz), (N/A, 2000 mBm)
[   35.224216] cfg80211:   (5250000 KHz - 5330000 KHz @ 80000 KHz), (N/A, 2000 mBm)
[   35.224220] cfg80211:   (5490000 KHz - 5710000 KHz @ 80000 KHz), (N/A, 2700 mBm)
[   35.224223] cfg80211:   (57240000 KHz - 65880000 KHz @ 2160000 KHz), (N/A, 4000 mBm)
```

Relative reading (The issue + Fix): https://bbs.archlinux.org/viewtopic.php?id=124574

Also the list of Country codes... EVERY SINGLE LAST FRIGGIN CODE WILL FRIGGIN FAIL BECAUSE OF THE UNPATCHED KERNEL... 2 years... and no-one can be bothered to fix or solve this issue, by the way ill be making sure to let the people know with Wireless RegDom issues in the IRC that you guys got told years ago... and did fuck all... :::: https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

Fix the fuckin kernels or give what people have also been asking for, for years, and a option to use NON-MANJARO kernels (* ones compiled themselves *) which wont break the system due to MHWD crying a fucking river.....

**Comment by udeved** [comment]
I close this for the explicit, brazen language.

**Comment by NovaCygni** [comment]
Aww did you drop your little dummy :'( Did the adults using EVERYDAY LANQUAGE that NO-ONE SINCE THE FUCKING 90s has been offended by? 
Grow the fuck up, and expect then when you MORONS cant act on something after 2 fucking years that people are going to be pissed of... No-Wonder Ringo left when the rest of you are just fucking morons with Ego/Attitude problems and put no value on trying to support the users... Whys there no MHWD-Chroot on the Installation ISO's so people can repair there installs with the medium they installed with when the internet isnt available??? Huh? No Response? Wouldnt that be a SENSIBLE thing to do that was suggested hundreds of times and requested NUMEROUS TIMES by people who are Manjaros "Support Team" on the IRC, Oh wait, they DONT EVEN FUCKING USE MANJARO ANYMORE BECAUSE YOU MUPPETS WONT LISTEN TO ANYONE!!!.

Btw I screenshotted Philm declaring "MD5 and Sha1" are still viable and will be used in the foreseeable future, its a classic example of why you dipshits are mentally unable to grasp even WELL  KNOWN Corrections...

**Comment by NovaCygni** [comment]
Also you idiotic moron... ISSUE WAS REPORTED 2 YEARS AGO... so you have a TWO YEAR OLD FUCKING PROBLEM,,, and rather than go "Aw shit maybe we should fix that" you try stroking your e-pen0r by just "Closing" something.... your a PRIME EXAMPLE of idiotic moron....

**Comment by udeved** [comment]
If I wanted someone to help me, I would not hurl insults, you poor child.

**Comment by oberon2007** [comment]
> Whys there no MHWD-Chroot on the Installation ISO's

Because you can use **manjaro-chroot**, which is present on every Manjaro ISO.

**Comment by NovaCygni** [comment]
udeved Awww ickle boy trying to be clever... if you had half a clue who I was yourd know I fix a vast proportion of your users issues for them in the IRC, I dont "Need help" Ive already bypassed the problem by compiling a new CRDA, But this is NOT something i can suggest to the average user to do when they need help, and this was reported YEARS AGO.... then followed up by Ringo who gave me the impression "If the devs dont need something for there OWN personal usage, then dont care" which was confirmed by Philm when a Broken Kernel update was pushed that didnt support True/Veracrypt... in which he confirmed none of  you guys use Encryption therefore dont care about it......
@oberon2007  its called... "MHWD-CHROOT" not "Manjaro-Chroot", Im one of the most active helpers for Manjaro in the IRC dont chat waffle you know nothing about......

**Comment by NovaCygni** [comment]
```
[novacygni@Firewall ~]$ yaourt -Ss manjaro-chroot
[novacygni@Firewall ~]$
```
Doesnt Exist :') 

```
community/mhwd-chroot 1.4-1
    Tool to easily chroot into an installed Linux installation from a live boot
aur/mhwd-chroot 1.4-1 (13) (0.69)
    chroot gui
aur/mhwd-chroot-extended 1.4.1-1 (3) (0.00)
    mhwd-chroot updated to support nvme storage (sda/hda/nvme)
[novacygni@Firewall ~]$

```

**Comment by udeved** [comment]
> Doesnt Exist :')

You know little but also insult oberon.

manjaro-chroot is part of manjaro-tools, which is present in live session.
Think and know before you burp.

**Comment by Ste74** [comment]
Please stop and read this before write : 
https://github.com/manjaro/manjaro-tools
see the readme.md file

**Comment by NovaCygni** [comment]
Aye I know little thats why you guys still cant work out why the MHWD is failing on Hybrid GPU's with a Hard-Disabled GPU0, Tip: Check the BUSID MHWD is configuring the display to use.... You got it right on the OpenRC-XFCE version and b0rked it on everything else.... Please tell me Mwoar about how you cant fix a 2 year old issue... Go get Philm to come tell me Sha1 and Md5 is viable for security and your going to KEEP using them for the foreseeable future only to have him edit/delete his idiotic comment afterwords.........

@Ste74 @udeved : If you were a little brighter you might have spotted "Renaming MHWD-Chroot" into "Manjaro-Chroot" ONLY in the "Tools" section, is a pretty retarded idea... "Zomg Guyz lets R change its name to be leet..."

**Comment by Ste74** [comment]
manjaro-chroot and mhwd-chroot not equal : we not support mhwd-chroot and is the reason because is in aur and not in our repo . If you follow our forum you know this. For the kernel problem i think better if you keep calm and talk civilly.

**Comment by udeved** [comment]
I am just saying, your language and insults do not make me want to help you at all.

**Comment by NovaCygni** [comment]
"Americans have an inferiority complex. By being offended by swear words, we can hold ourselves superior to the vulgar Others.Naw. Get more cynical. It's competitive. Someone else shows a disadvantage, you pounce.

**_The difference with Americans is that we pursue such matters on instinct. Even if it makes us look stupid or distracts us from real issues, we gotta pounce."_**
Stop being a steriotyical American, take your ego outside and get rid of it... Profanities, As iut happens the USAGE of Profanities is the Cultural norm for Essex in England, if someones done stupid things, you use profanities, its what they are for...
@Ste74 Well from a quick glance over the code, they appear very similar with maybe manjaro-chroot having a few of the bugs sorted... Also I Dont follow the forums to much because im also, one of the many hundreds who a Verification email never gets sent to (* Confirmed by Ringo wayyy back, I even offered/gave email access so he could verify himself *) 
@udeved I dont want "help" I just want the issue resolved so when people come into the IRC looking for help I dont have to matter of fact go "Yes this issue was reported years ago, please follow the following hour and a half long guide to fixing the issue yourself...", Ill be the first to admit I come across as a arsehole, thats just me and my way, but Its not fair on the average Manjaro user who gets this problem to be expected to know how to rebuild the CRDA themselves :/

**Comment by NovaCygni** [comment]
`The difference with Americans is that we pursue such matters on instinct. Even if it makes us look stupid or distracts us from real issues, we gotta pounce`
Spot on hits the nail on the head with you guys attitude, Americans need to realise outside the USA, theres nothing even remotely uncivilised about Profanities used correctly...

**Comment by oberon2007** [comment]
Your shouting and swearing helps noone and nothing. 90% of your output is completely off-topic and nothing but a waste of energy.
If you have factual input it's welcome, if it gets missed, overlooked or forgotten it's ok to say something again.
Just drop the rest and also accept that more than one opinion is sometimes valid and acceptable.
I'm out.

**Comment by NovaCygni** [comment]
@oberon2007 Read the original topic, PAY ATTENTION to the WALLS OF INFORMATION,,, then also notice, that "What the hell are you guys playing at" isnt a PROFANITY, thus is directed at you guys.... THEN FUCKIN notice the rest of the profanities are Generalised regarding the annoyance of the matter NOT being Resolved and are NOT Directed at anyone... which means the "I R will close this due to lanquage" idiotic responce, is, AS CORRECTLY CALLED, and IDIOTIC RESPONSE by a AMERICAN who cant grasp how pathetic it makes you look... fuck it, Ill just tell the Manjaro newcomers with ANY PROBLEMS PERIOD now that the Manjaro Dev's place there own ego's and virtue signalling beyond and problems, not just this issue, but everything ranging from the "GOSH I WONDER WHY HYBRID GPU's WITH DISABLED DISCRETE GPU'S CANT BOOT ON EITHER GRAPHICS SETTINGS" Most common problem Manjaro has to everything else.... 

Act like fuckin morons then get spoken to and treated like morons.... The FIRST Post, Wasnt even remotely directly offensive at anyone....

**Comment by udeved** [comment]
Perhaps tomorrow, you will be able to earn a better response, when you found a more social approach to communication, asking for help.
If you were not asking for help, you'd do it yourself and we'd accept the pull request.
So, lets not try the semantics game here, have a nice day.

**Comment by philmmanjaro** [comment]
Can somebody tell me what this is all about. @NovaCygni: it doesn't help you at all to insult people here. I see none what so ever to be changed here. We simply don't use hybrid cards as much. And if we use some we fix it for our own needs. Be happy to be able to use the same distro we create as is. If it doesn't work for you, well there are plenty other fish to catch ...

**Comment by philmmanjaro** [comment]
To clear this nonsense once and for all. We won't change it. Period! `CONFIG_ATH_USER_REGD=y` can't be enabled by default, because it can be used to violate country restrictions, thus breakin the law.

**Comment by lhorace** [comment]
I want to comment, I am bugzbunny, you patch Kernels, I like to know why, and who author to those patches. @philmmanjaro You restricting what should be open source software, I didn't know that in your _distro_ that you dictate what users are are allowed to use. It's very close to DRM

**Comment by udeved** [comment]
We patch kernels as we see appropriate and necessary.

What "DRM" modules are you referring to?
Put up specifics please.

**Comment by philmmanjaro** [comment]
@lhorace: you can find the source always in our git repos for our overlay packages. For **linux410** you may find it [here](https://github.com/manjaro/packages-core/tree/master/linux410). All other sources can be found at the [**Archlinux** project](https://www.archlinux.org/svn/).
