### ISSUE TITLE
2 YEAR OLD WARNING: Keep Autoclosing it and ill just keep spamming it...... GROW UP Morons...

### ISSUE THREAD

**Issue by NovaCygni** [manjaro/release-plan#141]
Considering I reported this YEARS ago,,, what the hell are you guys playing at? Your still NOT compiling the Kernels with 'CONFIG_ATH_USER_REGD' OpenWRT patch, thus people are STILL having the EEPROM issue of:
Starting of with

country GB: DFS-ETSI
        (2402 - 2482 @ 40), (N/A, 20), (N/A)
        (5170 - 5250 @ 80), (N/A, 20), (N/A), AUTO-BW
        (5250 - 5330 @ 80), (N/A, 20), (0 ms), DFS, AUTO-BW
        (5490 - 5710 @ 160), (N/A, 27), (0 ms), DFS
        (57000 - 66000 @ 2160), (N/A, 40), (N/A)
Then doing "sudo iw reg set JP", (* or Any other regdom, even if specified with country code number instead ie, 60, or 67 *): will result in:
global

country 98: DFS-UNSET
        (2402 - 2482 @ 40), (N/A, 20), (N/A)
        (2474 - 2482 @ 8), (N/A, 20), (N/A), NO-OFDM
        (5170 - 5250 @ 80), (N/A, 20), (N/A), AUTO-BW
        (5250 - 5330 @ 80), (N/A, 20), (0 ms), DFS, AUTO-BW
        (5490 - 5710 @ 160), (N/A, 23), (0 ms), DFS
        (59000 - 66000 @ 2160), (N/A, 10), (N/A)

The problem is easily spotted: The EEPROM is resetting to whatever country the Wireless card was sold from and ignoring the USER SET DETAILS... please, after 2 fuckin years, can you AT LEAST COMPILE THE KERNELS with the CORRECT PATCHES -.-

[    6.285400] cfg80211: Calling CRDA to update world regulatory domain
[    7.054075] cfg80211: World regulatory domain updated:
[    7.054081] cfg80211:  DFS Master region: unset
[    7.054081] cfg80211:   (start_freq - end_freq @ bandwidth), (max_antenna_gain, max_eirp)
[    7.054085] cfg80211:   (2402000 KHz - 2472000 KHz @ 40000 KHz), (N/A, 2000 mBm)
[    7.054087] cfg80211:   (2457000 KHz - 2482000 KHz @ 40000 KHz), (N/A, 2000 mBm)
[    7.054089] cfg80211:   (2474000 KHz - 2494000 KHz @ 20000 KHz), (N/A, 2000 mBm)
[    7.054091] cfg80211:   (5170000 KHz - 5250000 KHz @ 80000 KHz), (N/A, 2000 mBm)
[    7.054093] cfg80211:   (5735000 KHz - 5835000 KHz @ 80000 KHz), (N/A, 2000 mBm)
[    7.054095] cfg80211:   (57240000 KHz - 63720000 KHz @ 2160000 KHz), (N/A, 0 mBm)
[    7.054119] cfg80211: Calling CRDA for country: JP
[    7.068527] cfg80211: Regulatory domain changed to country: JP
[    7.068555] cfg80211:  DFS Master region: JP
[    7.068555] cfg80211:   (start_freq - end_freq @ bandwidth), (max_antenna_gain, max_eirp)
[    7.068558] cfg80211:   (2402000 KHz - 2482000 KHz @ 40000 KHz), (N/A, 2000 mBm)
[    7.068560] cfg80211:   (2474000 KHz - 2494000 KHz @ 20000 KHz), (N/A, 2000 mBm)
[    7.068562] cfg80211:   (4910000 KHz - 4990000 KHz @ 40000 KHz), (N/A, 2300 mBm)
[    7.068564] cfg80211:   (5030000 KHz - 5090000 KHz @ 40000 KHz), (N/A, 2300 mBm)
[    7.068566] cfg80211:   (5170000 KHz - 5250000 KHz @ 80000 KHz), (N/A, 2000 mBm)
[    7.068567] cfg80211:   (5250000 KHz - 5330000 KHz @ 80000 KHz), (N/A, 2000 mBm)
[    7.068569] cfg80211:   (5490000 KHz - 5710000 KHz @ 160000 KHz), (N/A, 2300 mBm)
[   35.219154] cfg80211: Calling CRDA for country: GB
[   35.224197] cfg80211: Regulatory domain changed to country: GB
[   35.224200] cfg80211:  DFS Master region: ETSI
[   35.224204] cfg80211:   (start_freq - end_freq @ bandwidth), (max_antenna_gain, max_eirp)
[   35.224208] cfg80211:   (2402000 KHz - 2482000 KHz @ 40000 KHz), (N/A, 2000 mBm)
[   35.224212] cfg80211:   (5170000 KHz - 5250000 KHz @ 80000 KHz), (N/A, 2000 mBm)
[   35.224216] cfg80211:   (5250000 KHz - 5330000 KHz @ 80000 KHz), (N/A, 2000 mBm)
[   35.224220] cfg80211:   (5490000 KHz - 5710000 KHz @ 80000 KHz), (N/A, 2700 mBm)
[   35.224223] cfg80211:   (57240000 KHz - 65880000 KHz @ 2160000 KHz), (N/A, 4000 mBm)
Relative reading (The issue + Fix): https://bbs.archlinux.org/viewtopic.php?id=124574

Also the list of Country codes... EVERY SINGLE LAST FRIGGIN CODE WILL FRIGGIN FAIL BECAUSE OF THE UNPATCHED KERNEL... 2 years... and no-one can be bothered to fix or solve this issue, by the way ill be making sure to let the people know with Wireless RegDom issues in the IRC that you guys got told years ago... and did fuck all... :::: https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

Fix the fuckin kernels or give what people have also been asking for, for years, and a option to use NON-MANJARO kernels (* ones compiled themselves *) which wont break the system due to MHWD crying a fucking river.....

**Comment by udeved** [comment]
If you adapt your language to be worth of a human being, I'll leave it open.

**Comment by NovaCygni** [comment]
@udeved  http://boards.straightdope.com/sdmb/archive/index.php/t-560291.html
Suck it up, and deal with it, Profanities is a NORMAL part of English, Spoken and used correctly, if you cant handle that go learn another lanquage... ENGLISH people, speaking and using ENGLISH, use Profanities... Get over your Morally superior complex and realize how even more pathetic it makes you idiots look...  YOUR PROBLEM.. Not mine... YOU LEFT SOMETHING UNFIXED for TWO years and you want what? A "Please sir, If you dont terribly mind would it be at all possible for you to fix x issue?"... I tried that... YEARS AGO... These days i dont have the patience for the Manjaro Dev's constant Ego stroking and idiotic Idea they always know better... (* Proven by Philm, countless times, right up to the moment he deleted his dribble about md5 and sha1 being viable and secure... *)

**Comment by philmmanjaro** [comment]
To clear this nonsense once and for all. We won't change it. Period! `CONFIG_ATH_USER_REGD=y` can't be enabled by default, because it can be used to violate country restrictions, thus breakin the law.
