### ISSUE TITLE
Clean out the manjaro repository

### ISSUE THREAD

**Issue by Huluti** [manjaro/release-plan#142]
This issue follows the discussion on the Manjaro forum:

- clean out the manjaro repository of all outdated packages.
- clean out old projects on github (or even better: move them to an "archive").

Allow me(artoo) to put deletion lists here so we can updated them to keep overview.

To be deleted in 

**packages-core** 

- [x] syslinux
- [x] syslinux4
- [x] cryptsetup
- [x] manjaro-system
- [x] sudo
- [x] xfsprogs

**packages-extra**

- [x] bluez
- [ ] catalyst-input
- [ ] catalyst-server
- [ ] catalyst-utils
- [ ] catalyst-video
- [x] exo
- [x] garcon
- [ ] gcc49
- [x] gfxboot
- [x] gnutls28
- [x] libxfce4ui
- [x] manjaro-base-skel
- [ ] manjaro-firmware
- [ ] manjaro-meta
- [ ] manjaro-printer
- [x] mdm
- [x] mdm-themes
- [x] mesa-libgl
- [x] networkmanager-openvpn
- [ ] plymouth
- [x] plymouth-dev
- [ ] plymouth-theme-manjaro
- [ ] plymouth-theme-manjaro-elegant
- [ ] plymouth-theme-manjaro-elegant-hidpi
- [ ] plymouth-theme-sonar-elegant
- [ ] plymouth-legacy
- [x] ruby-ethon
- [x] ruby-hashie
- [x] ruby-json
- [x] ruby-osdn-cli
- [x] ruby-osdn-client
- [x] ruby-typhoeus
- [x] samba
- [x] sonar-isolinux
- [x] syslinux-themes
- [ ] xdg-su
- [x] xfce4-appfinder
- [x] xfce4-dev-tools
- [x] xfwm4
- [x] xorg

**packages-community**

- [ ] sterminal
- [ ] update-notifier
- [ ] vertex-maia-gtk3
- [ ] vertex-maia-themes
- [ ] vertex-themes
- [ ] vicky
- [ ] vlc-nightly
- [ ] xapps
- [ ] yad
- [ ] python-xapp
- [ ] ruby-maruku
- [ ] ruby-yard
- [ ] snapper-gui
- [ ] steam-manjaro
- [ ] steam-native
- [ ] st-manjaro
- [x] minitube
- [ ] os-prober
- [ ] packagekit
- [ ] packnroll
- [ ] palemoon-bin
- [ ] pkgbrowser
- [ ] linux-rt-manjaro
- [ ] lxde
- [ ] lain
- [ ] libcpuid
- [ ] lightdm-settings
- [ ] lightdm-slick-greeter
- [ ] lightdm-webkit2-greeter-manjaro
- [ ] lighter-gnome
- [ ] disable-tracker
- [ ] dropbox
- [ ] dunstify
- [ ] gnome
- [ ] grub-btrfs
- [ ] guayadeque
- [ ] imagewriter
- [ ] i-nex
- [ ] conky-lua-nv
- [ ] cinnamon
- [ ] command-not-found
- [ ] compare-mirrors
- [ ] compiz-manjaro
- [ ] budgie-desktop
- [ ] cesious-theme
- [ ] checkhash
- [ ] adapta-maia-theme
- [ ] arc-firefox-theme
- [ ] arc-themes-maia
- [ ] artwork-breath
- [ ] artwork-maia
- [ ] awesome-freedesktop
- [ ] breeze-maia-icon-themes
- [ ] bspwm-scripts
- [ ] abiword-gtk2
- [ ] spacefm
- [ ] zsh-autosuggestions
- [ ] nautilus-admin
- [ ] pacui
- [ ] palemoon-i18n
- [ ] plymouth-theme-manjaro-fancy-budgie
- [ ] mate
- [ ] maia-console
- [ ] kmozillahelper
- [ ] bspwm-manjaro
- [ ] bumblebee
- [ ] delayed-hibernation
- [ ] deepin-manjaro
- [ ] dmenu-manjaro
- [ ] flatix-theme
- [ ] plymouth-theme-manjaro-gnome-17.0
- [ ] xtitle
- [ ] lemonpanel
- [ ] limepanel
- [ ] libpthread-stubs
- [ ] plymouth-theme-manjaro-cinnamon
- [ ] plymouth-theme-manjaro-circle
- [ ] plymouth-theme-manjaro-extra-elegant
- [ ] plymouth-theme-manjaro-gnome
- [ ] plymouth-theme-manjaro-redefined-bsplash
- [ ] python-npyscreen
- [ ] pywebkitgtk
- [ ] ruby-sass
- [ ] xfce4-dockbarx-plugin
- [ ] kde-servicemenus-rootactions
- [ ] gtk-theme-breath
- [ ] i3
- [ ] kde-servicemenus-dropbox
- [ ] sddm-andomeda-qt-theme
- [ ] downgrade
- [ ] gtk-engine-murrine
- [ ] gtk-theme-maia
- [ ] mugshot
- [ ] powerpill
- [ ] terminus-font
- [ ] transifex-client
- [ ] corebird
- [ ] python-efl
- [ ] vibrancy-colors
- [ ] lxdm-manjaro-theme
- [ ] menulibre
- [ ] mhwd-addon-amdgfx-hwe
- [ ] arc-maia-icon-theme
- [ ] budgie-wallpapers
- [ ] screenfetch
- [ ] tintin-alteraeon
- [ ] mate-wallpapers
- [ ] conky-cli
- [ ] emacspeak
- [ ] espeak
- [ ] adwaita-maia-gtk3
- [ ] adwaita-manjaro-themes
- [ ] allservers
- [ ] bmenu
- [ ] xdgmenumaker
- [ ] masalla-icon-theme
- [ ] virtualbox-dkms-modules
- [ ] x-apps
- [ ] xcursor-chameleon-pearl
- [ ] elementary-xfce-icons
- [ ] evopop-gtk-theme
- [ ] firefox-arc-maia-settings
- [ ] moka-icon-theme
- [ ] qt1
- [ ] sxhkd
- [ ] kde1-kdebase
- [ ] kde1-kdelibs
- [ ] linux-netbook
- [ ] artwork-andromeda
- [ ] engrampa-thunar-plugin
- [ ] oblogout-manjaro
- [ ] qt-at-spi
- [ ] fluxbox-theme-vertex-maia
- [ ] purple-skypeweb
- [ ] fluxbox-theme-manjaro
- [ ] pcaudiolib
- [ ] prpltwtr
- [ ] telegram-purple
- [ ] oysttyer
- [ ] gnome-video-arcade
- [ ] xorg
- [ ] xwinfo
- [ ] yaourt-gui-manjaro
- [ ] zsh-history-substring-search
- [ ] ttf-montserrat
- [x] turbulence
- [x] turbulence-artwork
- [x] turbulence-evolution
- [ ] ultraflatorange-icon-theme
- [ ] unified-manjaro-themes-openbox
- [ ] veracrypt
- [ ] vertex-maia-icon-theme
- [ ] virtualbox-dkms-manjaro
- [ ] volumeicon-gtk2
- [ ] wallpaperd
- [ ] wmutils
- [ ] wpa_tui
- [ ] xboomx
- [ ] xcursor-breeze
- [ ] xcursor-maia
- [ ] xcursor-menda
- [ ] xcursor-rezowhite
- [ ] xdo
- [ ] xfce4-weather-plugin-menda-circle-icons
- [ ] xfce-theme-greenbird
- [ ] xfwm4-manjaro-netbook
- [ ] xlogin
- [ ] timeset
- [ ] timeset-gui
- [ ] tintin
- [ ] tintwizard
- [ ] tmpwatch
- [ ] ttf-comfortaa
- [ ] ttf-dejavu-sans-mono-powerline
- [ ] ttf-font-icons
- [ ] pmenu
- [ ] pocketsphinx
- [ ] prelink
- [ ] preload
- [ ] pulseaudio-ctl
- [ ] purple-hangouts-hg
- [ ] purple-whatsapp
- [ ] pyplanemode
- [ ] python2-imaging-alt
- [ ] python-i3
- [ ] python-tesserwrap
- [ ] raktpdf
- [x] razor-qt
- [ ] rootmenu
- [ ] sakis3g
- [ ] sddm-manjaro-theme
- [ ] skippy-xd
- [ ] solarized-dark-themes
- [ ] sonarlinux-profiles
- [ ] sphinxbase
- [ ] srandrd
- [ ] sunflower
- [ ] sutils
- [ ] sxiv-rifle
- [ ] tclx
- [ ] thunar-shares-plugin-manjaro
- [ ] morc_menu
- [ ] mygtkmenu
- [ ] mygtkmenui
- [ ] nautilus-empty-file
- [ ] nemo
- [ ] networkmanager098
- [ ] network-manager-applet098
- [ ] networkmanager-dmenu
- [ ] nitrux-icon-theme
- [ ] nouvegnomegray-icon-theme
- [ ] numix-manjaro-themes
- [ ] numix-reborn-themes
- [ ] numix-themes-archblue
- [ ] obkey
- [ ] ocrdesktop
- [ ] ofono
- [ ] open-fuse-iso
- [ ] open-fuse-iso-term
- [ ] pantheon-wallpaper
- [ ] parachute
- [ ] parole
- [ ] pdf2img-c
- [ ] pekwm-menu
- [ ] pkgcacheclean
- [ ] plasma5-themes-menda
- [ ] mdsplib
- [ ] mediterraneannight-theme
- [ ] menda-circle-icon-theme
- [ ] menda-lxqt-panel
- [ ] menda-themes
- [ ] linux-tools
- [ ] locale-info
- [ ] lua-clock-manjaro
- [ ] lxappearance-gtk3
- [ ] lxdm
- [ ] lxdm-consolekit
- [ ] lxdm-manjaro-theme-openbox
- [ ] lxmed
- [ ] lxmusic-gtk3
- [ ] lxqt-theme-maia
- [ ] lxsession
- [ ] manjarobox-artwork
- [ ] manjaro-budgie-settings-extra
- [ ] manjaro-netbook-system
- [ ] manjaro-redefined-kdm-theme
- [ ] manjaro-xdg-menu
- [ ] manj-grub
- [ ] hal-flash
- [ ] hibernator
- [ ] isousb
- [x] jwm
- [ ] kdeicons-kfaenza
- [ ] keyboardctl
- [ ] kio-sysinfo
- [ ] laptop-mode-tools
- [ ] lemonbar-xft-clicky
- [ ] lightdm-another-gtk-greeter
- [ ] lightdm-another-gtk-greeter-themes
- [ ] faenzaflattr-icon-theme
- [ ] faenza-icon-theme
- [ ] faenza-manjaro-netbook-icon-theme
- [ ] fbmenugen
- [ ] fbmenu-manjaro
- [ ] fetter
- [ ] fisherman
- [ ] fix-trash
- [ ] forecasts
- [ ] frobtads
- [ ] frotz
- [ ] fusion-icon0.9
- [ ] grub2-theme-manjaro-redefined
- [ ] gtk-theme-config
- [ ] gtk-theme-e17gtk
- [ ] gtk-theme-numix-solarized
- [ ] gtk-theme-stylishdark
- [ ] gtk-youtube-viewer
- [ ] ephoto-git
- [ ] equate-git
- [ ] eviacam
- [ ] evopop-icon-theme
- [ ] faba-icon-theme
- [ ] faenza-green-icon-theme
- [ ] entrance-git-manjaro
- [ ] enlightenment-manjaro-themes
- [ ] dockbarx
- [ ] econnman
- [ ] ecrire-git
- [ ] emacs-speechd-el
- [ ] emerald0.9
- [ ] emerald-themes
- [ ] console-solarized
- [ ] bspwm-ruler
- [ ] bspwm-wallpapers
- [ ] c2esp
- [ ] cbatticon-gtk2
- [ ] chromium-chromevox
- [ ] chromium-pepper-flash-manjaro
- [ ] artwork-fluxbox
- [ ] artwork-maia-gnome
- [ ] awoken-icon-theme
- [ ] bar-aint-recursive
- [ ] bdf-zevv-peep
- [ ] blather
- [ ] brandr
- [ ] breeze-snow-cursor-theme
- [ ] advcp
- [ ] alternating-layouts

**Comment by philmmanjaro** [comment]
For the repository part, we have to identify them first. [Here](http://repo.manjaro.org.uk/pool/overlay/?C=M;O=A) is a list of all overlay packages in order by creation date.

**Comment by ThanosApostolou** [comment]
I would like to help with cleaning the manjaro repository of outdated packages. How can I help? Should I list here the packages which I believe they are outdated or should I do pull requests for deleting them?

**Comment by Huluti** [comment]
Just make a list here ;)

**Comment by udeved** [comment]
I'll remove all consolekit packages.

I don't have any overview of the dozens of theme and artwork packages, but a lot are outdated.

**Comment by ThanosApostolou** [comment]
The packages which I'm pretty confident that they are needed to be removed, for now, are these:

1. **faenza-green-icon-theme** It hasn't been updated for years and according to the creator's page, it needs mint-x-icons from AUR in order to work properly.
2. **cinnamon-power-applet** It doesn't work. Also, github page doesn't exist anymore and cinnamon has its own power applet so it isn't needed.
3. **razor-qt** It's not maintained anymore since it has been merged with lxqt.
4. **beshell** It hasn't been updated and it needs kde4 libraries.
5. **kdeicons-kfaenza** The pkgbuild gives errors - source links are no longer supported.]

Additionally the modified numix themes are a bit old. If someone can test if they are causing problems with the latest gtk3 versions or if they work ok despite them being old...

**Comment by excalibur1234** [comment]
is it not possible to compare the packages in the manjaro repository with the identical packages in the arch repositories automatically?
if the version number in the manjaro repositories is lower, the package needs to be updated or it can be removed (except for packages, which are downgraded on purpose, but these are not many).

**Comment by Ste74** [comment]
I'm not a software engineer 😄 , i'm a mechanical engineer 😜 but i think the easy way is select the pkgs for year of build : i see pkgs build in the 2012/2013/2014 .. i think start to exam it and write only what have to maintain otherwise the pkgs in this years i think can be safe removed.. 
in the 2015/2016 and now is more easy know what is the pkgs ( the packager team not change in this time )

**Comment by philmmanjaro** [comment]
**boxit** can compare all packages with those in Arch-Linux. Some packages may be old and from 2012 and so on. That doesn't mean that those are outdated. We have to check each single one and come up with a list. Some of the core-team members are still from the beginning here. Me for example :smiley:

**Comment by Ste74** [comment]
>  i think start to **exam it and write only what have to maintain** otherwise the pkgs in this years i think can be safe removed..
Yep is what i mean 😄 .. in this year (2012-2013 )  more of the pkgs are themes for openbox or general themes/icons/fonts .. decide if we need this .. razor-qt is outdated and also beshell .. manjaro alsa and pulse metapkgs are used in our iso so no remove it .. 
My comment was only for do a point to start 😉

**Comment by ThanosApostolou** [comment]
Is **manjaro-hotfixes** still needed? I have removed it from all my machines and I haven't experienced any problem. It hasn't been built since 2015 and it seems that it originally was created for a problem in 2012 https://manjaro.org/2012/08/02/nm-applet-might-not-start-for-you-anymore/. So, if it is not needed anymore, it might cause more problems than it solves in future updates.

**Comment by udeved** [comment]
We could move the polkit rules to manjaro-system package and drop hotfixes.

**Comment by udeved** [comment]
Related, I would again bring up manjaro-system, and reasoning, why we should modernize it.
Currently, it has a big weakness, if something goes wrong sync first, all the fixes manjaro-system is supposed to do are lost until the package is rebuilt.
We should really switch to alpm hooks for that, its task driven, we can have pre and post transactions hooks, ie drop sync first pacman patch.

**Comment by philmmanjaro** [comment]
@udeved: would be great. Can you test it. I assume you already started a new project for it already ...

**Comment by udeved** [comment]
https://github.com/manjaro/packages-core/commit/3a7a2707a34b9d896aecd9b7325af970c61107e2
https://github.com/manjaro/manjaro-system-ng/commit/e53e3d0be0a6c4169f9262a56bbb1058f3860f17

Regarding system hooks, I am for a clean cut, ie we don't port entire manjaro-system script, we just add new hooks if necessary for a particular update, eg stuff arch announces on their page for manual intervention.

What needs to be done is updating mhwd hooks.

**Comment by ThanosApostolou** [comment]
Should **mdm**, **mdm-themes** and **mdm-themes-extra** also be removed or get moved in the AUR (for users that already have them installed) since mint is dropping it (http://www.omgubuntu.co.uk/2017/04/linux-mint-adopts-lightdm-slick-greeter)? It's not so important but I remember mdm been known for security holes in the past and now that it won't be supported I think it's a good idea to remove it from manjaro repos.

**Comment by udeved** [comment]
@manjaro/maintainers @manjaro/packagers 

I have updated the list for core and extra git repos.

Could someone please check community and append the list?

**Comment by Ste74** [comment]
Please anyone can review the community pkgs , i have signed some packages now .. btw the sonar pkgs ? example purple series , espeak ... ?

**Comment by udeved** [comment]
@philmmanjaro 

Can I clean core and extra packages as marked in git devel branch?

**Comment by excalibur1234** [comment]
i see you have "pacui" in the list. i am still developing it and it is not outdated.
please keep it, otherwise i will not be able to distribute pacui in the manjaro repositories.

**Comment by philmmanjaro** [comment]
@udeved: some packages need discussion first before they got removed. For example **gcc49** is still used for **catalyst**. Before we delete any of these files/packages we should discuss each and everyone. Currently I've no time for this.

**Comment by Ste74** [comment]
@excalibur1234 , don't worry is only a list of all pkgs in community.. we have to sign what can be deleted ;)

**Comment by Tids** [comment]
I feel bad about this comment, but what's with all the openRC packages? Becuse ... [Manjaro-openrc will be discontinued](https://forum.manjaro.org/t/manjaro-openrc-will-be-discontinued/28387)

**Comment by excalibur1234** [comment]
i agree with @Tids.
also, feel free to remove `pacli-simple-git`. this has been replaced by `pacui` half a year ago.

**Comment by Ste74** [comment]
@Tids when is the time we remove all open-RC stuff since we have dropped it .
@excalibur1234 where you see pacli-simple-git ? I take a look into our repo but i don't see this and also in boxit i don't see it  ..

**Comment by excalibur1234** [comment]
> @excalibur1234 where you see pacli-simple-git ?
ah, sorry. pacli-simple-git is in the AUR. i have to request deletion of that package.

pacli is still in the community repo of manjaro and the last meaningful update was over a year ago. imho, it has many deficiencies, but it should still work. so i do not see any reason to remove it...

**Comment by philmmanjaro** [comment]
Next **filesystem** package will be **systemd** centric. Therefore **OpenRC** has to go. We will see when we do the switch.

**Comment by notuxius** [comment]
I'm proposing to also add some packages into cleaned up repos and maybe create separate issue for this process:

Applications:
whdd
woeusb-git
spotify + blockify + mopidy-spotify
testdisk-wip
zotero
wavebox-bin
photoqt
phototonic
xnviewmp-system-libs
xmind
ghostwriter
megasync + Dolphin integration
seafile
zoom
slack-desktop
aqemu
masterpdfeditor
netbeans-cpp
netbeans-php
neofetch
etcher
stremio-bin
rambox
whatsie
plex-media-server
enpass-bin
ocenaudio-bin
tor-browser + lang packs
brave
vivaldi
wire-desktop
webtorrent-desktop
shotcut
vidcutter
ffmulticonverter
qwinff
lossless-cut
komodo-edit
visual-studio-code
jetbrains-toolbox
pycharm-edu
pycharm-community
freefilesync
onlyoffice-bin
wps-office + dictionaries + fonts
gitkraken
viber
teamviewer
discord-canary

Dolphin Service Menus, KConfig Modules, KRunners:
https://aur.archlinux.org/packages/kde-servicemenus-thunderbird-attachment/
https://aur.archlinux.org/packages/kde-servicemenus-getmediainfo/
https://aur.archlinux.org/packages/kf5-servicemenus-copypath/
https://aur.archlinux.org/packages/kde-servicemenus-komparemenu/
https://aur.archlinux.org/packages/kcm-wacomtablet/
https://aur.archlinux.org/packages/kdeplasma-runners-vbox/
https://aur.archlinux.org/packages/kde-cdemu-manager-kf5/

Plus you maybe interested in other suggestions at https://github.com/netrunner-rolling/QA-Suggestions/

**Comment by jonathonf** [comment]
> I'm proposing to also add some packages

I think you're misunderstanding the term "clean out". ;)

Personally, I don't want to add to the load of package maintenance for commercial and binary-only software packages. I don't think we should be redistributing binaries without very good reason. The AUR is available for just such reasons.

**Comment by Ste74** [comment]
Since this programs are not used in our ISOs we don't have interest to add and maintain . Our users can install via AUR or compiling itself and plus you are off-topic here .

**Comment by fhdk** [comment]
> I'm proposing to also add some packages into cleaned up repos

I agree that we should not burden our selves with maintenance which AUR does just fine.
