### ISSUE TITLE
netinstall: pacman-mirrors have no effect on installed system

### ISSUE THREAD

**Issue by ThanosApostolou** [manjaro/release-plan#143]
I have this problem:

I built a new lxde ISO against stable branch (I use **netinstal="true"** and **chrootcfg="false"** on the LXDE profile). For some reason, even thought the live packages are installed from **https://mirror.netzspielplatz.de/manjaro/packages/** mirror, the default chosen mirror was **http://free.nchc.org.tw/manjaro/** from Taiwan which doesn't get updated vert often. This resulted in a broken installation on virtualbox, since in the Taiwan mirror, the linux49 was at version **4.9.24** but the **linux49-vritualbox-guest-modules** was at version **5.1.18-8** instead of **5.1.18-9** and the virtualbox modules couldn't been loaded after installation.

I run `sudo pacman-mirrors -f5` and `sudo pacman -Syy` before I start the installer but this didn't have any effect on the installed system. So, even though now the Taiwan mirror is updated, this problem can be repeated in the future with later updates. So how can I fix this? Can I somehow change the default mirror when I create the ISO? Shouldn't `pacman-mirrors` affect the installed packages form the netinstaller (I was advising people on the forum to use `pacman-mirrors -f5` before they run the installer but now I see that this has no effect)?

**Comment by Ste74** [comment]
Strange issue .. have you tried to do also the -geoip function? Or maybe -g -c all ? @udeved or @fhdk ?

**Comment by ThanosApostolou** [comment]
It seems to be working normally now, so feel free to close this. Just to understand this right, pacman mirrors are updated when manjaro live boots by some systemd service right?

**Comment by excalibur1234** [comment]
this systemd service is used to update the live system after boot:
https://github.com/manjaro/manjaro-tools-livecd/blob/master/data/sd/mirrors-live-net.service

**Comment by fhdk** [comment]
> I run sudo pacman-mirrors -f5 and sudo pacman -Syy before I start the installer but this didn't have any effect on the installed system.

I have no experience in the live-iso and their inner workings. But If it has no effect on the installed system - I think you're updating the live system.

You will most likely have a mounted install root at something like /mnt/calamares-xyx and you could have pacman-mirrors to point to that root by using -o and -d arguments which would lead pacman-mirrors to update the mirror file and the mirror list in your install-dir.

@Ste74 
Or if we could get pacman-mirrors 4.1-dev moved to release you can use the newly created api to assign a prefix to filehandling and read/write access protocols and branch in pacman-mirrors.conf.

**Comment by philmmanjaro** [comment]
@fhdk: how stable is **v4.1** series so far?

**Comment by philmmanjaro** [comment]
@ThanosApostolou: well, updating the mirrorlist on **live-session** only updates it for the live session. **Calamares** will run a new generation of the list using our [**postinstall** function](https://github.com/manjaro/calamares/blob/development/src/modules/postcfg/main.py#L71). Therefore we use again **IP**, which uses the mirror closest to you. We never check if that mirror is current.

**Comment by fhdk** [comment]
@philmmanjaro 
Very stable - the lastest changes to the code is very minimal.

* helpstrings - 
* a flag in api to signal if mirrorlist should be skipped
* also a few minor bugs has been squashed.

Nothing groundbreaking really.

I have been using it my self on my daily driver and also tested when booting isos and doing vbox installs - the first I do is fetching the dev version and testing it.

In my opinion it is very stable.

**Comment by ThanosApostolou** [comment]
@fhdk I've built the ISO after the last stable updates so it has *pacman-mirrors 4.0.4**
@philmmanjaro Yeah true I retested many times and after the installation the mirror is selected by geoip. Maybe this should be changed to **-f5** too since it seems like a better choice to me.

So, my conclusion is that for some reason **pacman-mirrors** didn't work when I was doing the first tests yesterday and it resulted in a random generated mirrorlist. I remember getting errors "no internet connection found" when I was running **pacman-mirrors -f5** but after some tries it worked fine. So, is it possible that the online mirror service was down or something at some  point yesterday? Either that, or my connection wasn't stable yesterday and that resulted in hit or miss when the pacman-mirrors was trying to update.

**Comment by fhdk** [comment]
@ThanosApostolou 
> it resulted in a random generated mirrorlist
> I remember getting errors "no internet connection found" when I was running pacman-mirrors -f5

I am leaning towards a wlan network connection?

A failsafe exist - If network connection check fails - then pacman-mirrors falls quietly falls back to `-m random`. (https://manjaro.org)

**Comment by ThanosApostolou** [comment]
I see... So most likely it was my connection's fault. Feel free to close this issue whenever you want, except if you want to change its title and talk about pacman-mirrors 4.1 here.

**Comment by ThanosApostolou** [comment]
@fhdk I've been thinking about it a bit and it seems like these types of errors happen too often. Connection fails, then pacman-mirrors falls back to `-m random` and when connection is up again then the user probably has a broken or outdated mirror on the top of the mirrorlist. So I have this idea:

What about an option `pacman-mirrors -s` (or --safe) which won't need internet connection and it will only add the mirrors which we know for sure that they are always updated and working like those (I don't know if they are more):
https://mirror.netzspielplatz.de/manjaro/packages/
https://repo.stdout.net/manjaro/
https://manjaro-mirror-a.alpix.eu/
Or it can just use `pacman-mirrors -m random` and then delete the lines of 1 of these mirrors and add it to the top of the mirrorlist (I think it can be easily done for your skills).
Then if connection fails, it should be used as a fall-back option for pacman-mirrors and the user will always have an updated mirror even if `pacman-mirrors -f5` fails. What do you think?

**Comment by fhdk** [comment]
Whenever a user runs a pacman-mirrors command which modifies the mirrorlist it is implicit that the user runs `pacman -Syu` after this command.

Which ever situation - if a network error occur - it is the users responsibility to rerun the commands when the network is again available.

We cannot solve that with an extra switch - If your installer needs to be sure an internet connection exist before calling pacman-mirrors to generate the mirrorlist you can use [this gist](https://gist.github.com/fhdk/0ed497472e3d2e460132e1dd2111ddf7)

**Comment by ThanosApostolou** [comment]
Ok I think I understood. Everything seem to work fine, even better with pacman-mirrors 4.1 so I close this issue.
