### ISSUE TITLE
Issue with lightdm

### ISSUE THREAD

**Issue by philmmanjaro** [manjaro/release-plan#145]
Seems we have an issue with lightdm ...

![lightdm](https://cloud.githubusercontent.com/assets/5050022/25700154/a67cf05c-30c6-11e7-8cd8-1b01268406bb.jpg)

**Comment by philmmanjaro** [comment]
Seems we have a similar issue also with **sddm**. Will check now with **stable** branch ...

**Comment by philmmanjaro** [comment]
Hmm, seems to be a regression with the latest **manjaro-tools-git** code. Current **v0.15.2-2** seems to work just fine.

**Comment by udeved** [comment]
Not sure this is tools related, buildiso doesn't do any DM config. We only set services in buildiso.
The rest is done by livecd packages.

**Comment by Strit** [comment]
Just created an ISO with SDDM on stable branch. SDDM works fine there, on manjaro-tools 0.15.2.

**Comment by philmmanjaro** [comment]
@Strit: I'm talking about the current git code of **manjaro-tools**. I had no time yet to pinpoint the issue. Something introduced a regression. If I use the same packages on my ISO and just use **v0.15.2** release all is fine for me also.

**Comment by udeved** [comment]
@philmmanjaro 

I can't confirm for sddm on systemd. Works with latest git.

**Comment by oberon2007** [comment]
Here's i3 with lightdm:

![](http://imgur.com/aLaRxoQ.png)

Interesting also, why is it trying to run plymouth?

**Comment by oberon2007** [comment]
Were you able to fix this @philmmanjaro ? Or did you just build your 17.0.2 previews with stable tools?

**Comment by philmmanjaro** [comment]
I used the stable tools for now ...

**Comment by Ste74** [comment]
Still present ?

**Comment by philmmanjaro** [comment]
It is fine with current **manjaro-tools**.
