### ISSUE TITLE
[buildpkg] -b option error

### ISSUE THREAD

**Issue by oberon2007** [manjaro/release-plan#146]
```
$ buildpkg -p pix -b testing
 --> Loading compiler settings: x86_64
==> Start building [pix]
==> ERROR: No chroot dir defined, or invalid path '/var/lib/manjaro-tools/buildpkg/testing/x86_64'
```

**Comment by udeved** [comment]
More detail please, full -q output.

**Comment by oberon2007** [comment]
It's working now after I created **/var/lib/manjaro-tools/buildpkg/testing/x86_64** manually and ran
```
 mkchroot /var/lib/manjaro-tools/buildpkg/testing/x86_64/root base-devel
```
So seems there was a problem doing exactly that automatically ...
```
$ buildpkg -p pix -b testing -q
 --> Loading compiler settings: x86_64
==> manjaro-tools
  -> version: 0.15.2
  -> config: ~/.config/manjaro-tools/manjaro-tools.conf
==> PROFILE:
  -> build_lists: x-apps
  -> build_list_pkg: pix
  -> is_build_list: false
==> OPTIONS:
  -> arch: x86_64
  -> branch: testing
  -> chroots_pkg: /var/lib/manjaro-tools/buildpkg
==> ARGS:
  -> create_first: false
  -> delete_first: false
  -> clean_first: false
  -> update_first: false
  -> purge: false
  -> namcap: false
  -> sign: false
  -> udev_root: false
==> PATHS:
  -> pkg_dir: /home/bernhard/manjaro/pkg/testing/x86_64
==> BUILD QUEUE:
  -> pix
```

**Comment by oberon2007** [comment]
I just tried removing **/var/lib/manjaro-tools** completely. Now the error occurs regardless of branch when I run ``buildpkg``. The directory tree is not created.

**Comment by udeved** [comment]
So this a git version 0.16, and you didn't mump the version?

**Comment by udeved** [comment]
Chroot creation works differently now.

To create chroot/root, you need -o paramater.
The user copy works then.
I made it so to reduce disk writes, ie the copy will always be synced or updated.

**Comment by oberon2007** [comment]
It's one commit before https://github.com/manjaro/manjaro-tools/commit/21d5a1a0d69d64f259e758b0cd87f05c55da331e So maybe this explains it ;)

**Comment by oberon2007** [comment]
rebuilding...

**Comment by udeved** [comment]
-o parmeter in combination with -d ....

**Comment by oberon2007** [comment]
so commit **21d5a1a** doesn't fix it in any case.

**Comment by oberon2007** [comment]
uhm. ``man buildpkg`` doesn't tell me anything about ``-o`` and ``-d``... what are they?

**Comment by udeved** [comment]
The commit did not fix anything except deletion of the chroot/root.

You use it wrongly.

**Comment by udeved** [comment]
`buildpkg -h`

**Comment by oberon2007** [comment]
I've deleted /var/lib/manjaro-tools and:
```
$ buildpkg -p pix
 --> Loading compiler settings: x86_64
==> Start building [pix]
==> ERROR: No chroot dir defined, or invalid path '/var/lib/manjaro-tools/buildpkg/unstable/x86_64'
```
What's wrong usage with that?

**Comment by udeved** [comment]
I told you, buildpkg -h has the answer.

    buildpkg -p pix -do

or 

    buildpkg -p pix -uc

**Comment by oberon2007** [comment]
Ok. So when you run buildpkg for the first time it will fail if you don't use ``-o`` option - seems odd, but ok ;)=

**Comment by udeved** [comment]
Yes, create once and never again.
The rest is handled in the chroot copy.

**Comment by oberon2007** [comment]
ok

**Comment by philmmanjaro** [comment]
I rather recommend to execute the `-o` option automatically. Why is it needed to be ran once manually and we get an error which might confuse people?

**Comment by udeved** [comment]
No, we can't execute -o always, since it would run counter to aim of the recent changes.

Apparently, I am tired of english, sometime I hate this language.

-o ist nur zur Ersterstellung der Wurzel, in der wird nie gebaut. Die dient nur als Quelle für die Kopie.
Ist die Kopie einmal erstellt, dann bedinet ihr nur noch die Kopie, es sei denn, ihr braucht wie ich neben systemd auch eine udev root. Dafür wäre dann -d, um die Wurzel neu zu erstellen.

**Comment by philmmanjaro** [comment]
Ok, passt. Gerne kann man den Fehler, falls einer kommt, besser erklären. Ich bin immer offen für neue Funktionen.

**Comment by udeved** [comment]
Mit anderen Worten, wir handhaben jetzt die chroot so, wie es sein soll, und mkchrootpkg es vorschlägt.
Die Wurzel wird nie verändert, hat nur base-devel, die Kopie ist es, die verändert wird.

Vorher haben wir immer die Wurzel mit neu erzeugt, was unnötigt ist, und nur die Platte belastet.

**Comment by udeved** [comment]
To clear things up in english.

Previously, it went in one go

* create chroot/root
  * rsync user copy from chroot/root in chroot/$USER
  * build in chroot/$USER

Now, we have

* create chroot/root once (-o)

* rsync user copy, with update(pacman, to update the copy for new base-devel pkgs) and clean option (-c and -u)
  * build in Chroot/$USER

* optionally, delete chroot/root (-d) best in combination with -o

**Comment by Ste74** [comment]
So if we need to introduce and test the depends for new pkgs we will use -do and if is only an normal update pkgs we do -u ?

**Comment by udeved** [comment]
yeah, -do would be equal to recreating chroot/root too, you start from zero so to speak.
In most cases, its not necessary, and you just use -c switch to clean out the chroot copy(reset)
