### ISSUE TITLE
Update iso-profiles faster 

### ISSUE THREAD

**Issue by Chrysostomus** [manjaro/release-plan#147]
Manjaro-architect uses the iso-profiles as a template for installation to keep on track with changing editions. By default it uses the manjaro-tools-iso-profiles package, and has an option for using the git repo directly. 

However, this has some side effects. Particularly in unstable repo, the repo package lags so far behind that the installation just fails because of wrong package names. This is the situation currently. 

What could we do to keep the profiles more up to date?

**Comment by udeved** [comment]
Not much can be done about it.

I would go to read netinstall yaml instead, there are always uptodate so no direct depend on packages.

**Comment by Chrysostomus** [comment]
Could you elaborate on this "no direct depend on packages"? Are they like package groups?

**Comment by udeved** [comment]
Yes, package groups defined in yaml. Only little problem. you need a little custom yaml parsert in bash.
Or, you use python which has nice easy yaml handling.
CAL reds these yaml files at run time, ie from url.

**Comment by Chrysostomus** [comment]
Are these groups more up to date than iso-profiles repo in git?

**Comment by oberon2007** [comment]
Simply rebuilding iso-profiles packages whenever important changes happen should normally be enough. Like that under normal circumstances profiles packages on a given branch shouldalso match the packages available on the same branch.
We were a bit lazy in the past updating those packages.
With the git profiles you will of course always have the problem that changes in principle reflect the state of unstable branch - same applies to the .yaml files. They will reflect the state of the branch a maintainer is currently building. I don't see where the difference or advantage there would be. Maybe I miss something here ... ?

**Comment by oberon2007** [comment]
we have developed a good habit with updating desktop-settings pkgs, we just should do the same with iso-profiles pkgs, then these problems in m-a should disappear.
We should just make sure and double check if m-a uses matching branches of profiles, settings-packages and actual packages...
