### ISSUE TITLE
Avahi-ZeroConf Bowser ( /usr/bin/avahi-discover ) missing package python2-dbus

### ISSUE THREAD

**Issue by meolix** [manjaro/release-plan#15]
Avahi-ZeroConf Bowser ( /usr/bin/avahi-discover ) missing package python2-dbus
The package python2-dbus is not installed for running avahi-discover on the live-cd.
Fix for this issue: Add package python2-dbus to the installed packages.
Thanks

**Comment by philmmanjaro** [comment]
Well, this works as designed. **python2-dbus** is an optional dependency as you can see with -Qi:
```
[manjaro@manjaro ~]$ pacman -Qi avahi
Name           : avahi
Version        : 0.6.31-16
Description    : Multicast DNS-SD / Zeroconf Suite
Depends On     : expat  libdaemon  glib2  libcap  gdbm  dbus
Optional Deps  : gtk3: avahi-discover-standalone, bshell, bssh, bvnc
                 [installed]
                 gtk2: gtk2 bindings [installed]
                 qt4: qt4 bindings [installed]
                 pygtk: avahi-bookmarks, avahi-discover [installed]
                 python2-twisted: avahi-bookmarks
                 mono: mono bindings [installed]
                 python2-dbus: avahi-discover
                 nss-mdns: NSS support for mDNS
```

**Comment by meolix** [comment]
Hmm... from user perspective I see the following:
Menu -> System -> Avahi Zeroconf Browser
Clicking on Avahi Zeroconf Browser : Nothing happend.
Looking into that menu-entry I see Exec=/usr/bin/avahi-discover
Running /usr/bin/avahi-discover from terminal I got Error message:
"Sorry, to use this tool you need to install Avahi, pygtk and python-dbus.  Error: No module named dbus"
So the point is: We have a non workin Menu-Option, which gives a user a non-working Avahi Zeroconf Browser. With no indication for the user that he might have to install a missing dependency!
Either take away the non-working menu-entry or give the user a working "Avahi Zeroconf Browser" within the menu!

**Comment by udeved** [comment]
You need gtk installed.

**Comment by philmmanjaro** [comment]
Well **avahi** seems to be installed as an dependency for something else. This info you get also with `pacman -Qi avahi`. I understand your side. However we might have also some editions not wanting to install GTK at all. For XFCE it won't be a problem to add this dependency, however we can't check for all optional dependencies. I'll think about it.
