### ISSUE TITLE
buildpkg chroot not automatically updated?

### ISSUE THREAD

**Issue by oberon2007** [manjaro/release-plan#150]
Using latest git tools I just ran into this problem:
Pushed new packages **lain** and **awesome-freedesktop** to unstable.
netzspielplatz has definitely synced since and ``pacman -Si`` knows the packages.
Still when I now try to build **cesious-theme**, depending on those two pkgs, they are not found:
```
==> Making package: cesious-theme 0.1-1 (Thu May 11 11:56:15 UTC 2017)
==> Checking runtime dependencies...
==> Installing missing dependencies...
error: target not found: awesome-freedesktop
error: target not found: lain
==> ERROR: 'pacman' failed to install missing dependencies.
==> ERROR: Build failed, check /var/lib/manjaro-tools/buildpkg/unstable/x86_64/bernhard/build
```
Do I have to manually update the chroot now with ``-u`` option??

**Comment by oberon2007** [comment]
Building with ``-u`` worked. But shouldn't buildpkg check for latest available pkgs in any case?

**Comment by udeved** [comment]
> Building with -u worked.

There you go, works as intended.
