### ISSUE TITLE
Remove cinnamon-power-applet from repositories

### ISSUE THREAD

**Issue by ThanosApostolou** [manjaro/release-plan#151]
It is listed under Community repository but I cannot find the PKGBUILD on packages-community.

It doesn't work anymore and the github URL doesn't exist. So, given the increasing popularity of cinnamon desktop it might gets some users confused/dissatisfied if they try to install it and use it.

@oberon2007 Can you verify that it is not needed (it doesn't work on either cinnamon 3.2 or 3.4)?

**Comment by Strit** [comment]
I see the latest build was in May of 2014 by @philmmanjaro, So my guess is that it is not working anymore, since it has not been updated. Maybe the functionality got into other cinnamon packages?

**Comment by oberon2007** [comment]
https://lists.manjaro.org/pipermail/manjaro-packages/Week-of-Mon-20170515/011287.html
