### ISSUE TITLE
the switch to a configuration-less xorg setup

### ISSUE THREAD

**Issue by Tids** [manjaro/release-plan#152]
For the OSS-graphicsdrivers (intel,radeon,amdgpu,noveau) I suggest to switch to a config-free setup. Xorg (and wayland) is able to detect the drivers by themself. It is also more flexible in case of new hardware, because no hardcoded PCI slots or anything like this.

For hybrid systems we should phase out bumblebee where we're able to (I dont know how the situation is with Nvidia blob).

Mesa Prime should work much better without configuration files. It will use the graphicschip, that is either set as main in BIOS/UEFI or attached to the main screen, as main graphics chip by default. Now the user can switch to the dedicated graphicscard with `DRI_PRIME=1 <app>`. GNOME seems to have this already integrated in the DE itself.

The (untested) repo is here: https://github.com/manjaro/mhwd-db/compare/master...Tids:master

**Comment by udeved** [comment]
@Tids 

Do you eventually have time to test this? You use systemd, right?
https://github.com/manjaro/release-plan/issues/138

https://github.com/manjaro/packages-community/blob/master/bumblebee/PKGBUILD#L45
You would just have to bump pkgrel and change `--without-pid` to `--with-pid` and quickly build the package with `makepkg -sri`.

**Comment by Tids** [comment]
@udeved I would. But right now I only own AMD systems (and an Intel only laptop) So I dont think its possible to test for me :(

**Comment by udeved** [comment]
This is still good news @Tids afaik there is no one in team with ati/amd.

Generally, I think we need a little renovating of mhwd.
In my view, we can drop the mhwd-db possibly, and use already existing hwids package. Most what mhwd-db does is to write xorg conf files, but xorg has developed, almost end of life cycle reached, and most cards work out of box by letting xorg geneate conf on the fly at run time.
What we need, hwid and vendor or model string, this is what mhwd needs to do, to detect hw by id, and match it against driver packages.
However, dropping mhwd-db would also make mhwd probably much less useful, its was written to use mhwd-db. 
The matching of id and driver could be done in new python based mhwd script. This would be a major change under the hood @philmmanjaro but I think we need to modernize mhwd. Its currently more trouble than help on hybrids.

**Comment by philmmanjaro** [comment]
@udeved: **MHWD** was not designed to support all hybrid cards. Yes it is old and somehow outdated. We should however use [ldm](https://github.com/solus-project/linux-driver-management) as an replacement for **mhwd**. There are already plans to port it to archbased distros.

**Comment by udeved** [comment]
Sounds fine to me too. I just see we need to do something on mhwd front.

**Comment by philmmanjaro** [comment]
Some modifications are already made by @Tids. So we simply have to review them to see if they a logic. Our community might give us the needed feedback when it is out there.

**Comment by udeved** [comment]
Do you have an approximate schedule when ldm is ported and ready on arch?
If its say still half a year to go, it would probably justify little work on mhwd additionally to @Tids contributions. Say ripping out all the xorg writing where we don't need them could do already some wonders on some systems.

**Comment by philmmanjaro** [comment]
I've added @Tids  current work to **mhwd-db** in a PR. Lets see if we get some [feedback](https://github.com/manjaro/mhwd-db/pull/8).

**Comment by Tids** [comment]
Thanks! I've tested so far with single Chip (on Intel (OOLD ATOM something and an I5, My R9 380 and an A8 APU) all of them work.

In general it should just work as long as I havend wrote in some missconfiguration.

**Comment by Tids** [comment]
@philmmanjaro One more commit to mhwd-amdgpu. 
https://github.com/tids/packages-core

looks like [wikipedia is wrong](https://en.wikipedia.org/wiki/AMD_Radeon_Rx_200_series) with
Topaz -> GCN1.0

Thanks to a [userreport](https://forum.manjaro.org/t/amd-problem-on-boot/25327/20) we know now that it is[ GCN1.2, so full AMDGPU support.](https://wiki.gentoo.org/wiki/AMDGPU)

I'm so i've moved it to the amdgpu-supported series.

----

Another thing is for the now deprecated video-hybrid-intel-ati-bumblebee
https://github.com/Tids/mhwd-db/commit/ea2d85aaab2b45f976ce959f60d38f8a9cd70905
We better use the id for the radeon driver, because otherwise its available for amdgpu and that results in a kernelpanic.

I'd also suggest that we remove video-hybrid-intel-ati-bumblebee and hybrid-intel-nouveau-bumblebee with one of the next (dev?)releases, because prime seems to work nicely.

The only issue here is: how to make an automatic switch for users from video-hybrid-intel-ati-bumblebee to prime? Because once we have removed that config from mhwd, people can not uninstall it by themself.

**Comment by ThanosApostolou** [comment]
@philmmanjaro regarding **ldm**, I did a comment on phoronix about that you are looking into this (on this article: https://www.phoronix.com/forums/forum/phoronix/latest-phoronix-articles/957116-solus-ramping-up-ikey-doherty-will-work-fulltime-on-the-os) and ikey responded that he is willing to accept requests:
![screenshot at 2017-06-13 15-27-30](https://user-images.githubusercontent.com/21288843/27082322-f6f6f244-504c-11e7-86d1-7ed075b69f22.png)
Just thought to let you know about it.

**Comment by Strit** [comment]
That's what I like about Ikey. He likes to collaborate on stuff, so others can use it too.

**Comment by philmmanjaro** [comment]
@Tids: is here still some open or all fine now with **v17.0.2-rc3**?

**Comment by Tids** [comment]
@philmmanjaro I think we're done with this now 👍
