### ISSUE TITLE
Remove base-devel and yaourt from packages-desktop file

### ISSUE THREAD

**Issue by Ste74** [manjaro/release-plan#154]
Hi , this is only a little list where i find the base-devel packages installed by default plus yaourt : 
https://github.com/manjaro/iso-profiles/blob/master/community/lxde/Packages-Desktop#L46
https://github.com/manjaro/iso-profiles/blob/master/manjaro/xfce/Packages-Desktop#L51
https://github.com/manjaro/iso-profiles/blob/master/manjaro/kde/Packages-Desktop#L59
i see also in deepin , awesome , lxde and in other in community ( budgie and mate 😜 ) but not example in cinnamon . So is possible remove all of this packages support and leave the users to install ? Is possible add the manjaro-aur-support packages into shared folder to install in every isos ? Check here some image of how work .. 
https://github.com/manjaro/iso-profiles/issues/59#issuecomment-306054985
This windows are only showed when yaourt or pacaur is installed and only one time . I hope in this way to make the user more prepared on how to handle packets out of the repo manjaro.

**Comment by philmmanjaro** [comment]
@Ste74: is this still relevant?

**Comment by Ste74** [comment]
Leave at maintainer the decision :smile:
