### ISSUE TITLE
Start including manjaro-architect in isos? 

### ISSUE THREAD

**Issue by Chrysostomus** [manjaro/release-plan#155]
I feel that manjaro-architect is starting to be stable enough to be included in install medias. It would be cool if it could be included in the 17.02 release. 

Reasons to include it:

- it mostly works 
- it allows installing editions that don't have up to date isos 
- it gives more options 
- it has been a while since we had working cli-installer 

Reasons not to include it yet:

- 17.02 is already quite close to completion 
- some languages have incomplete translations (english here and there, mostly in advanced sections) 
- it has mostly been tested with unstable branch

What do you think?

**Comment by oberon2007** [comment]
Oh yes, seems somehow I simply forgot! 😉 I will certainly be happy to include **m-a** in the i3 edition. Not sure how useful it is in Cinnamon and Deepin - but on the other hand, why not!?

> it has mostly been tested with unstable branch

Well, the manjaro-architect ISO is built against stable since quite a while already and it has been used by quite a lot of people meanwhile. The feedback is very positive, too.

**Comment by Ste74** [comment]
You mean include the script for download m-a ?

**Comment by oberon2007** [comment]
You just need to install **manjaro-architect-launcher**, yes. It comes with icons, .desktop file and all and will download the installer when executed.

**Comment by oberon2007** [comment]
No, sorry! That's rubbish! The **manjaro-architect** package actually would need to be installed and the installer launched directly, so not with 'setup' which will not be present.

**Comment by oberon2007** [comment]
**manjaro-architect-launcher** is nothing but the 'setup' script. It could be installed on another ISO, too, of course...
@Chrysostomus the theming still might need some tweaking when the architect is used with different terminal emulators ... ...

**Comment by Ste74** [comment]
Ok.. understand..

**Comment by Chrysostomus** [comment]
Without the theming, it just looks normal like nmtui, wifi-menu or the old cli-installer. 

@oberon Do you have in mind how to set the color scheme reliably? As dialogrc uses the existing colors of the terminal emulators color scheme, it would be easiest to first set terminal colors with a script (similar to what manjaro-zsh-config does). But it is really difficult to take all terminal emulators into account, because konsole and qterminal respond poorly to such color manipulation and don't have very distinct $TERM value.

**Comment by oberon2007** [comment]
The best will probably be to just use **dialog**'s default. And if in one or the other edition one wants to come up with a more subtle theming we can check that... It will unfortunately just not be possible to use **maia-console** with its **dialogrc** also for terminal emulators because as you say, they are just all too different and every edition themes their terminals differently.

**Comment by excalibur1234** [comment]
what packages do i have to add to Packages-Live file in order to integrate manjaro-architect?

is it enough to add "manjaro-architect" and "manjaro-architect-launcher" to get a desktop icon "Install Manjaro (CLI)" (equivalent to calamares)?

**Comment by oberon2007** [comment]
You will just need to add **manjaro-architect**. We can take care of the desktop icon in the live script.

**Comment by oberon2007** [comment]
I will include **m-a** with my community builds 17.0.2 For me it is ready and tested enough to this point.
@philmmanjaro for the official editiions I guess you are more inclined to milestone it 17.1?
In any case, right now or soon we should take a brief look at how the discours colors look in the respecitve terminals - Xfce and Gnome should be fine I guess but I have no idea yet how it will look in plasma...

**Comment by oberon2007** [comment]
Maybe as a first step for 17.0.2 we could at least include the m-a-ISO in the official announcements and upload a fresh build to manjarolinux SF?

**Comment by Ste74** [comment]
m-a added in any profiles
