### ISSUE TITLE
Need to build bash ourselves

### ISSUE THREAD

**Issue by udeved** [manjaro/release-plan#157]
After experimenting exporting a system wide path in manjaro-system-ng, I have come to the conclusion, we need to build bash ourselves.

The benefits are multiple, we can unify messages, and finally get some structure to bashrc customizations done in desktop-settings. Perhaps find a sane shared default? @manjaro/maintainers 

Reason is, the only way to export a path safely for console and x session is to use /etc/bash.bashrc.
Ad if we use this, we ca directly source manjaro shell libs in bashrc.
We could do customizations in /etc/bash.d/*.bashrc additionally to user bashrc.
We would have to introduce /etc/bash.d/ with the bash package ad make it read files when loading bashrc.
Using /etc/profile.d/ is only for login shells usable.
https://wiki.archlinux.org/index.php/environment_variables#Globally

**Comment by udeved** [comment]
In the unstable branch, we got this now:

```
$ ls -l /etc/bash /etc/bash/bashrc.d
/etc/bash:
insgesamt 12
-rw-r--r-- 1 root root   28 13. Jun 11:25 bash_logout
-rw-r--r-- 1 root root  701 13. Jun 11:25 bashrc
drwxr-xr-x 2 root root 4096 13. Jun 11:40 bashrc.d

/etc/bash/bashrc.d:
insgesamt 16
-rw-r--r-- 1 root root 1465 13. Jun 11:36 manjaro_colors.bashrc
-rw-r--r-- 1 root root  699 13. Jun 11:36 manjaro_common.bashrc
-rw-r--r-- 1 root root 1199 13. Jun 11:36 manjaro_functions.bashrc
-rw-r--r-- 1 root root  138 13. Jun 11:36 yaourt_colors.bashrc
```

**Comment by philmmanjaro** [comment]
OK, So we have the following package diffs now:

```
:: Different overlay package(s) in repository community i686/x86_64

-------------------------------------------------------------------------------
                             PACKAGE              testing             unstable
-------------------------------------------------------------------------------
                             elogind              229.4-1              229.5-1
                          libelogind              229.4-1              229.5-1
                      polkit-elogind  0.113+29+g3272a98-7  0.113+29+g3272a98-8


:: Different overlay package(s) in repository core i686/x86_64

-------------------------------------------------------------------------------
                             PACKAGE              testing             unstable
-------------------------------------------------------------------------------
                          filesystem            2017.06-4            2017.06-5
                      manjaro-system           20170406-5           20170606-1
                              pacman              5.0.1-8            5.0.2-0.4
                                bash                    -            4.4.012-3
                   manjaro-system-ng                    -           20170613-1


:: Different overlay package(s) in repository extra i686/x86_64

-------------------------------------------------------------------------------
                             PACKAGE              testing             unstable
-------------------------------------------------------------------------------
                   manjaro-live-base           20170425-1           20170606-1
                 manjaro-live-openrc           20170425-1           20170606-1
           manjaro-live-portable-efi           20170425-1           20170606-1
                manjaro-live-systemd           20170425-1           20170606-1
                              polkit  0.113+29+g3272a98-1  0.113+29+g3272a98-2
```
(lib)elogind, manjaro-live-(base,openrc,portable-efi) have no changes and can be moved or hold, as they don't matter.

**Comment by udeved** [comment]
I think you need default polkit too, I moved the pk.rules from manjaro-hotfixes in the pk packages.

**Comment by philmmanjaro** [comment]
The list to hold is now:

```
bash
filesystem
manjaro-live-systemd
manjaro-system 
manjaro-system-ng
pacman
polkit
polkit-elogind
```

Or do I miss some here?

**Comment by udeved** [comment]
Looks good I think.

manjaro-system was just a rebuild to remove it from base group, so technically, it could be removed from list.

**Comment by philmmanjaro** [comment]
This is done in our **devel** branch and can be found in our **xperimental** repo-branch already.

**Comment by jonathonf** [comment]
I wish I'd caught this earlier.

There's no need to build the whole bash package just to add a system-wide profile script: just put the script in `/etc/profile.d/`. Then it will be sourced by all users.

**Comment by oberon2007** [comment]
We're packaging it because of our custom rc files.

**Comment by Chrysostomus** [comment]
Maybe we could ship our customizations in /etc/profile.d/? Or maybe some user specific equilevant? Or was it that we  specifically want to avoid setting something that the arch package sets?

**Comment by oberon2007** [comment]
@philmmanjaro and I recently had a lengthy discussion about bash. I'm not sure any more why exactly in the end we decided to package it ourselves...

**Comment by Chrysostomus** [comment]
It was because artoo wished that we provide all settings via settings-packages, and bash owned /etc/skel/.bashrc.

**Comment by oberon2007** [comment]
We wanted to get rid of the strange uncommon **.extend.bashrc** file that people don't expect. It exists on no other Linux distribution.
Installing with settings package isn't possible as long as **bash** contains it aswell.
One way would be to deploy it via the profiles since the upstream package has it in the `backup` array, so it would be respected.

**Comment by philmmanjaro** [comment]
It is all about the **.extend.bashrc** we removed and replaced iwth **.bashrc** which now conflicts with **bash** and therefore we build it ourselfs without that file in skel.
