### ISSUE TITLE
Default GRUB configuration - Why does Manjaro load intel_ucode.img on AMD?

### ISSUE THREAD

**Issue by informer2016** [manjaro/release-plan#158]
I have an AMD processor, but for some reason Manjaro is loading the Intel microcode.
Is that intended? Is Manjaro assuming every computer has an Intel processor?

Trying to load Intel's ucode, which is supposed to be a workaround for Intel's errata, on AMD - is just plain wrong and could result in not-obvious software failures. My proposal for future releases is to change the approach for GRUB configuration - instead of giving this intel_ucode.img option for all the users, you could check if user's CPU is Intel, and if it is indeed Intel - alter the GRUB default configuration _(to add this intel_ucode stuff)_ during the boot of installation media

**Comment by Strit** [comment]
And how do you propose we do this CHeck and replace during install?

**Comment by informer2016** [comment]
@Strit While booting a LiveCD, this boot-time script checks if CPU is Intel, and if it is - then offer a slightly modified version of boot entry to the user ( with added intel_ucode ) . During the installation, the generated grub.cfg file could borrow the presence or absence of "intel_ucode" from the previously chosen boot entry.

However, if my proposal is technically impossible, then a better and more correct approach would be not to include intel_ucode in boot entry by default, like the most of others Linux distributions are doing

**Comment by philmmanjaro** [comment]
To clear this one up. It doesn't matter if **intel-ucode** gets loaded or not on an AMD system. With a newer kernel it is even possible to integrate this code to the kernel, as **KaOSx** does it. It is simple. Arch provides that **microcode** in a separate image which other Distros don't do. More about this topic can be found [here](https://wiki.archlinux.org/index.php/Microcode).

**Code snippet from KaOSx**

```
CONFIG_MICROCODE=y
CONFIG_MICROCODE_INTEL=y
CONFIG_MICROCODE_AMD=y
CONFIG_MICROCODE_OLD_INTERFACE=y
...
CONFIG_FIRMWARE_IN_KERNEL=y
CONFIG_EXTRA_FIRMWARE="amd-ucode/microcode_amd.bin amd-ucode/microcode_amd_fam15h.bin amd-ucode/microcode_amd_fam16h.bin intel-ucode/06-03-02 intel-ucode/06-06-05 intel-ucode/06-08-01 intel-ucode/06-0a-01 intel-ucode/06-0f-02 intel-ucode/06-16-01 intel-ucode/06-1c-02 intel-ucode/06-25-05 intel-ucode/06-3a-09 intel-ucode/06-3f-02 intel-ucode/0f-00-0a intel-ucode/0f-02-09 intel-ucode/0f-04-04 intel-ucode/0f-06-04 intel-ucode/06-05-00 intel-ucode/06-06-0a intel-ucode/06-08-03 intel-ucode/06-0b-01 intel-ucode/06-0f-06 intel-ucode/06-17-06 intel-ucode/06-1c-0a intel-ucode/06-26-01 intel-ucode/06-3c-03 intel-ucode/06-3f-04 intel-ucode/0f-01-02 intel-ucode/0f-03-02 intel-ucode/0f-04-07 intel-ucode/0f-06-05 intel-ucode/06-05-01 intel-ucode/06-06-0d intel-ucode/06-08-06 intel-ucode/06-0b-04 intel-ucode/06-0f-07 intel-ucode/06-17-07 intel-ucode/06-1d-01 intel-ucode/06-2a-07 intel-ucode/06-3d-04 intel-ucode/06-45-01 intel-ucode/0f-02-04 intel-ucode/0f-03-03 intel-ucode/0f-04-08 intel-ucode/0f-06-08 intel-ucode/06-05-02 intel-ucode/06-07-01 intel-ucode/06-08-0a intel-ucode/06-0d-06 intel-ucode/06-0f-0a intel-ucode/06-17-0a intel-ucode/06-2d-06 intel-ucode/06-3e-04 intel-ucode/06-46-01 intel-ucode/0f-02-05 intel-ucode/0f-03-04 intel-ucode/0f-04-09 intel-ucode/06-05-03 intel-ucode/06-07-02 intel-ucode/06-09-05 intel-ucode/06-0e-08 intel-ucode/06-0f-0b intel-ucode/06-1a-04 intel-ucode/06-1e-05 intel-ucode/06-2d-07 intel-ucode/06-3e-06 intel-ucode/06-47-01 intel-ucode/06-56-02 intel-ucode/06-56-03 intel-ucode/06-56-04 intel-ucode/0f-02-06 intel-ucode/0f-04-01 intel-ucode/0f-04-0a intel-ucode/06-06-00 intel-ucode/06-07-03 intel-ucode/06-0a-00 intel-ucode/06-0e-0c intel-ucode/06-0f-0d intel-ucode/06-1a-05 intel-ucode/06-25-02 intel-ucode/06-2f-02 intel-ucode/06-3e-07 intel-ucode/0f-00-07 intel-ucode/0f-02-07 intel-ucode/0f-04-03 intel-ucode/0f-06-02"
CONFIG_EXTRA_FIRMWARE_DIR="/lib/firmware"
```

**Comment by philmmanjaro** [comment]
**Grub v2.03** series now supports multiple initramfs images. So this will be the new default.
