### ISSUE TITLE
check all extramodules for newer versions

### ISSUE THREAD

**Issue by philmmanjaro** [manjaro/release-plan#16]
* it will be good to check all extramodules for newer versions
* decide which drivers we might drop (optional)

**Comment by udeved** [comment]
I believe, we have too many kernels for the size of team.
Perhaps reduce it to a 318, 41 and current dev kernel?

**Comment by philmmanjaro** [comment]
Since I maintain all kernels and I already have a system for how to do it there is no issue to support many kernels as we do now. However, for example **linux312** one extramodule is broken since April and nobody cared about it. So I really don't know who is actually using those older kernels. I'll drop **linux40** for sure now.

**Comment by udeved** [comment]
Was just a thought to have you more time by dropping some kernels.
I personally use stable lts kernels usually.
Its the only thing I like stable on the system.

**Comment by Esclapion** [comment]
I think also we have too many kernels. It has been critized in a french review. 3 max, 4 maybe ?

**Comment by philmmanjaro** [comment]
Some like it, some hate it. Ubuntu ships also several kernels. This makes us more flexible.

**Comment by philmmanjaro** [comment]
This is the current result of our ongoing kernel vote:
```
Linux 3.10 LTS series                            1 (0.8%) 
Linux 3.12 LTS series (maintained by Suse)       2 (1.6%) 
Linux 3.13 ESS series (maintained by Canonical)  1 (0.8%) 
Linux 3.14 LTS series                            9 (7.3%) 
Linux 3.16 ESS series (maintained by Canonical)  2 (1.6%) 
Linux 3.18 LTS series (maintained by Oracle)    32 (25.8%) 
Linux 3.19 ESS series (maintained by Canonical)  8 (6.5%) 
Linux 4.0                                        8 (6.5%) 
Linux 4.1 LTS series                            61 (49.2%) 
```

**Comment by Ste74** [comment]
Some old kernel you can leave but only lts. this for compatibility on old hardware . This is just my thoughts

**Comment by Esclapion** [comment]
With the 4.2, we have 10 kernels. How can the user choose ?

**Comment by Ste74** [comment]
It would be nice to have two kernels inside the iso lts one example 3.16 then the last ...
but seriusly the user search the last kernel .. but in old machine not always the best coiche i think

**Comment by philmmanjaro** [comment]
Most of the packages are now updated. Following I have on my todo list:
nvidiabl 0.76 -> 0.88
broadcom-wl 6.30.223.141 -> 6.30.223.248

Those we will lock at the current versions:
open-vm-tools-modules 2:2013.09.16
vhba-module 20140629

**Comment by philmmanjaro** [comment]
should be done now.
