### ISSUE TITLE
locale problem with new GRUB screen

### ISSUE THREAD

**Issue by oberon2007** [manjaro/release-plan#160]
i3status bar crashes when it is unable to run `setlocale(LC_ALL, "");` during startup.
We already had a problem with this [in the past](https://github.com/i3/i3status/issues/64) when we tried to not run `locale-gen` in the [live script](https://github.com/manjaro/manjaro-tools/commit/2259e083d85a93e1b5c7978780f2b2e96a7af696)
In the now existing situation the problem seems to lie somewhere in the GRUB-theme.
When the language setting is left at the default all is well and the output of `locale` in the live environment looks like

![locale_default](https://user-images.githubusercontent.com/11800714/27349577-0e77127c-55f8-11e7-9f0a-a7aaa66d4986.png)

But as soon as you explicitly select a language other than the default en_US, you get:

![locale_de](https://user-images.githubusercontent.com/11800714/27349961-4bd72d4a-55f9-11e7-9e5e-41b63a22363e.png)

and i3status is again unable to launch successfully.

**Comment by oberon2007** [comment]
I don't really understand what the problem is with locale setting in the live.
When I try to run `locale-gen` the output remains the same - meaning there is still the error displayed and env vars remain at the wrong `en_US.utf8` setting.
When I actually uncomment en_US.utf8 in **/etc/locale.gen** and run locale-gen again the errors go away and env vars remain at en_US of course...

**Comment by oberon2007** [comment]
What does the error message actually mean? Which "file or directory" is it referring to?

**Comment by philmmanjaro** [comment]
I hope this fixes it: https://github.com/manjaro/manjaro-tools-livecd/commit/8c5e52d32b6345096c48a1359649b4fc9f7b532a
