### ISSUE TITLE
Stop providing sha1sums and provide only sha256 or higher?

### ISSUE THREAD

**Issue by ThanosApostolou** [manjaro/release-plan#163]
I'm currently building my lxde 17.0.2 release candidate and I was thinking, since sha1 can be "cracked" theoretically , maybe we should stop providing sha1sums and provide only sha256sums from now on?

I've seen that no edition provides md5sums anymore, which is a good thing.

It's highly unlikely that anyone will target manjaro's ISOs and spent all these resources in order to perform any such attack, but this would show the users that security is taking seriously into consideration.

Tell me what you think.

**Comment by oberon2007** [comment]
Afaik for huge files like an ISO even md5 sums are still secure. It's a bit of a hype this whole story I believe 😉 sha256 calculation takes quite a while, not only for us but for the users who are supposed to verify it... The ISOs are signed also, so I really don't see any problem anywhere with whatever checksum.
However, anything desired is fine for me. I'll provide it 👍

**Comment by ThanosApostolou** [comment]
I see. However, Fedora is using sha256 for quite some time even though they have also other security checks. I consider Fedora's team the best as security is concerned, so I believe we should really try to do what they are doing :stuck_out_tongue: 

Is it ok if I provide only sha256 for my lxde ISOs? Or should I provide sha1 too like the official editions?

**Comment by oberon2007** [comment]
Btw if you want to verify your uploads on sourceforge in any case you will need to create sha1 too because they only provide md5 and sha1! 😉 

![](http://imgur.com/lcoje0y.png)

**Comment by oberon2007** [comment]
ah ok well you can of course run sha256sum in the sf-shell...

**Comment by philmmanjaro** [comment]
We still provide **sha1sum** since SF.net doesn't do anything else. So for a quick check it is OK. People should use the Signatures anyway to verify our ISOs. So I think we can close this and provide still **sha1** as given.

**Comment by ThanosApostolou** [comment]
Ok. I will upload the sha1sums in the lxde edition too then.
