### ISSUE TITLE
New theme for GDM session 

### ISSUE THREAD

**Issue by Ste74** [manjaro/release-plan#164]
Hi guys , after a little research and study i'm able to change the default screen of GDM .. see the screenshot:
![img_20170805_184610](https://user-images.githubusercontent.com/11218234/28997212-42472cf0-7a0f-11e7-9bd9-6eb93e6f6f83.jpg)

![img_20170805_184637](https://user-images.githubusercontent.com/11218234/28997215-4becd6f6-7a0f-11e7-9cab-194e09c83005.jpg)

![img_20170805_184658](https://user-images.githubusercontent.com/11218234/28997216-4fba12bc-7a0f-11e7-81b3-aeaf92069209.jpg)

this is a draft : the theme is based on adapta-breath-theme and the wall is a one of the manjaro gnome collection.. 

Since we can menage GDM we can create a hook to monitoring the gdm changes and in case of changing we can reinstall the theme ..
Please let me know a wallpaper to use and of course do you think :D

**Comment by Ste74** [comment]
Well , seem i'm able to do a complete gnome-shell theme for next release :) ... 
Created this repository to ask in our community helping to change some asset
https://github.com/Ste74/manjaro-gnome-theme

**Comment by Ste74** [comment]
@oberon2007 : new wallpaper 
https://github.com/Ste74/manjaro-gnome-theme/tree/master/adapta-manjaro-themes
grab from muser artwork ;)

**Comment by oberon2007** [comment]
very nice!

**Comment by Ste74** [comment]
https://github.com/manjaro/packages-community/commit/375d2e49b4f7a9d467f0b1d8ecbd19481b535dcb

**Comment by Ste74** [comment]
Actual state
https://youtu.be/IkOaBValby4

**Comment by Ste74** [comment]
I think now is ready but since 17.0.3 is a maintaining release for Gellivara this new look appear in 17.1 so not add in iso-profiles for now.  
https://github.com/manjaro/packages-community/commit/cbe6074524cb264762c49540674c08c3e838bae3

**Comment by Ste74** [comment]
Already in our repo and enable into Gnome profile
