### ISSUE TITLE
"Rebuild dynamic linker cache" issue

### ISSUE THREAD

**Issue by AJSlye** [manjaro/release-plan#17]
"Rebuild dynamic linker cache" takes up 30 seconds to initiliaze while booting from LIVE USB

**Comment by Kirek** [comment]
This should fix it: https://github.com/manjaro/manjaro-tools/commit/11a5d53901ba524dedb4ff98f8b59fb24585c8f9

This will prevent ldconfig.service (which causes the "Rebuild dynamic linker cache") and a few other services to start in the livecd.

Please test.

**Comment by AJSlye** [comment]
Only this one little change, or do I need to wait for Manjaro-tools to be
updated in the repository?
I'm currently using base, iso, pkg version 0.9.12-1 and efiboot 225-1 of
manjaro-tools.

**Comment by Kirek** [comment]
This single change would fix it. You already have the latest manjaro-tools, but it doesn't include this commit.
There is a PKGBUILD available to build the latest devel version of manjaro-tools at https://github.com/manjaro/packages-extra/blob/master/manjaro-tools-git/PKGBUILD

**Comment by AJSlye** [comment]
I just wanted to be sure there were not any other commits that would effect this one, or that would be beneficial at this time. I will make this change and then an rebuild my ISO.

Thank you.

**Comment by AJSlye** [comment]
That's OK, I'll just make this one change for now.
