### ISSUE TITLE
when the stable version 17.1 release?

### ISSUE THREAD

**Issue by adaaaaaa** [manjaro/release-plan#175]
will it solve the boot problem?

**Comment by Strit** [comment]
What boot problem are you referring too?

And I believe that 17.1 will release after the pre-releases are done and tested.

**Comment by adaaaaaa** [comment]
![img_20171123_232559](https://user-images.githubusercontent.com/23206387/33180351-5c8d8660-d0a7-11e7-9d7c-2d012e5001e6.jpg)
what's the problem? i am a newbee to linux...please help... @Strit

**Comment by jonathonf** [comment]
If you have an issue, please check the forum, and post there if you can't find anything that helps:

https://forum.manjaro.org/

This repo/issues board is for discussions and issues surrounding the release plan and planning process.

**Comment by adaaaaaa** [comment]
found a solution....
change the display option to discrete graphics card...
