### ISSUE TITLE
i can not recover from sleep mode...

### ISSUE THREAD

**Issue by adaaaaaa** [manjaro/release-plan#178]
i can see the option in chinese name "挂起"... in windows10, it's the same as sleep mode...
win10 can recover from sleep mode , the monitor can start-up normally...
in manjaro 17.1-pre3 , i can see my computer recover , at lease the power led is light , but , the monitor still in the sleep mode... i press the keyboard and move the mouse , it has no reaction at all...
what is the problem? the montior or manjaro?

**Comment by jonathonf** [comment]
The "release plan" issue tracker isn't a good place for asking for help with issues.

Please use [the forum](https://forum.manjaro.org/) instead.
