### ISSUE TITLE
Asus AC1300 Wifi Adaptör

### ISSUE THREAD

**Issue by mthnzbk** [manjaro/release-plan#179]
My English is bad.

I have an Asus ac1300 usb wifi adapter. I installed all the packages for rtl8812au from AUR but my equipment was not recognized. However, the Antergos LTS Kernel is also known for the hardware. So I'm trying to connect with a $5 wifi adapter.

**Comment by Chrysostomus** [comment]
The correct place for this discussion is here:

https://forum.manjaro.org/c/technical-issues-and-assistance/hardware
