### ISSUE TITLE
release version wrong in Calamares

### ISSUE THREAD

**Issue by oberon2007** [manjaro/release-plan#18]
Calamares still calls the latest release 0.9 instead of 15.09 !

**Comment by philmmanjaro** [comment]
Which version did you test? It is correct as in:
https://github.com/calamares/calamares-manjaro/commit/8fb7767864a3d36bf4ae845d59ff8445021140a7

**Comment by oberon2007** [comment]
Yes, I did not have the latest obviously, sorry :)
