### ISSUE TITLE
Add manjaro branding for refind

### ISSUE THREAD

**Issue by Chrysostomus** [manjaro/release-plan#182]
I created the package refind-theme-maia, fork off refind-theme-regular. Enables itself automatically, but must be installed after refind is installed with refind-install.

Since refind is an option offered by manjaro-architect, I figured we could theme it like we theme grub. I'm thinking of making both themes part of the bootloader installation.

Suggestions and opinions are welcome. Is this a good idea? Is the theme acceptable?

![refind-theme-maia](https://user-images.githubusercontent.com/12002226/35275743-691ccac2-0049-11e8-9376-3be22f7c8497.png)

**Comment by Ste74** [comment]
For me all is ok .. don't like the wallpaper and .. maybe the manjaro logo is not a square ?

**Comment by Chrysostomus** [comment]
Manjaro icons can be squared. I could try using the same wallpaper as the grub theme, though single color background works best with different resolutions.

**Comment by Chrysostomus** [comment]
![grub_bg](https://user-images.githubusercontent.com/12002226/35302045-e4a6e492-0095-11e8-91ef-55836b54160c.png)

Looks like changing the wallpaper alone will not do. The text and some icons drown in the background, plus the background is not very sharp. Higher resolution image would be better....

**Comment by Chrysostomus** [comment]
Actually, the first screenshot ws faulty. Here is how it ws supposed to look:

![maia-refind](https://user-images.githubusercontent.com/12002226/35319007-a5667968-00e6-11e8-86ed-b4ba76209c0b.png)

Here is how it looks with higher resolution version of the grub background:

![breath-refind](https://user-images.githubusercontent.com/12002226/35319032-ba1df14c-00e6-11e8-8621-3fcb299af44b.png)

And here is alternative repurposed from lxde wallpaper:

![lxbreth-refind](https://user-images.githubusercontent.com/12002226/35319051-ccf16452-00e6-11e8-8825-a2b9cba59f92.png)

Unselected icons are difficult to make stand out from that green criss cross part, as is text. The lxde alternative might be easier to work with.

**Comment by Chrysostomus** [comment]
![adapta-refind](https://user-images.githubusercontent.com/12002226/35319489-b87f8b46-00e8-11e8-8f86-06436df44acf.png)

![lockscreen](https://user-images.githubusercontent.com/12002226/35319500-c1e8e11e-00e8-11e8-8791-b050aa15857e.png)

Some more alternatives.

**Comment by Phoenix1747** [comment]
Looks quite nice, I like it.

**Comment by Chrysostomus** [comment]
Maybe a poll in forums would be in order?

**Comment by Strit** [comment]
This looks really awesome.
Is there a guide somewhere on how to switch from Grub to refind?
I would like to try this out on an existing system. 🙂

**Comment by Chrysostomus** [comment]
https://forum.manjaro.org/t/poll-refind-theme-maia-background/38935

@Strit there is not really much to it. Refind also interacts nicely with grub. You need a uefi system. Just do as root: 

     pacman -S refind-efi
     refind-install

To use this theme, install refind-theme-maia. 

Refind has two configurations: refind.conf on esp and refind-linux.conf on /boot of individual linux installations. You can set kernel parameters for autodetected kernels there. 

For readable documentation:

https://wiki.archlinux.org/index.php/REFInd

For thorough documentation: 

http://www.rodsbooks.com/refind/

**Comment by oberon2007** [comment]
Wow, those look VERY COOL indeed!

**Comment by Ste74** [comment]
👍
