### ISSUE TITLE
Possibility to add driver on manjaro ?

### ISSUE THREAD

**Issue by liberodark** [manjaro/release-plan#185]
Hello,

Have a Asus 200HA and no have sound on my pc.
Have possibility to add this on manjaro : https://github.com/Grippentech/Asus-E200HA-Linux-Post-Install-Script
Just for add driver officialy for sound only.
Wifi work perfect but sound on 4.9.xx not work and 4.14.xx is same.

Cordialy

**Comment by Strit** [comment]
Not much info on what is actually changed in their custom kernel.

Maybe links to the kernel patches needed are more helpful?

**Comment by Phoenix1747** [comment]
Did you try it with 4.15? Not sure if they changed so much on sound drivers but it's worth a try.

**Comment by jonathonf** [comment]
This scripts appear to install a custom kernel from deb packages. If you can find out which drivers are being added it might be worth considering for Manjaro; as it stands those scripts don't help.
