### ISSUE TITLE
Codenames suggestions

### ISSUE THREAD

**Issue by Phoenix1747** [manjaro/release-plan#186]
Hi, just had a look around for some nice sounding codenames and thought I wanted to share them with you:
* **Eridani** (actually Epsilon Eridani; a star)
* **Chalawan** (a yellow dwarf star)
* **Cervantes** (another star)
* **Mirach** (star)
* **Haumea** (dwarf planet)
* **Vesta** (asteroid)
* **Eunomia** (another asteroid)

**Comment by jonathonf** [comment]
The last release was Gellivara so the next one will begin with an "H". ;)

**Comment by Ste74** [comment]
> The last release was Gellivara so the next one will begin with an "H". ;)
**17.1.x Hakoila** already done ;)

**Comment by Phoenix1747** [comment]
"The last release was Gellivara so the next one will begin with an "H". ;)"
Oops, didn't think of that. What about **Ikeya** or **Iduna**? (both are asteroids)

**Comment by jonathonf** [comment]
> Hakoila

Um. Yeah. So there was that one too... :blush:

**Comment by philmmanjaro** [comment]
v18.0 will most likely be named as **Illyria** – Homeworld of the Illyrian species - based on the list of [Star Trek Planets/Stars](https://en.wikipedia.org/wiki/List_of_Star_Trek_planets_%28G%E2%80%93L%29).

**Comment by Strit** [comment]
Any idea when such a release would be? Q2?
