### ISSUE TITLE
Pacman-mirrors

### ISSUE THREAD

**Issue by fhdk** [manjaro/release-plan#189]
What are your thoughts on these issues?

Enhance pacman-mirrors to help pamac's [country selection](https://github.com/manjaro/pamac/issues/366) function to be restored.

* [Listing custom selected countries](https://github.com/manjaro/pacman-mirrors/issues/127)
* [Allow mirrors not up-to-date in mirror list](https://github.com/manjaro/pacman-mirrors/issues/128)

**Comment by philmmanjaro** [comment]
this is implemented now.
