### ISSUE TITLE
Disable power savings in live-session

### ISSUE THREAD

**Issue by philmmanjaro** [manjaro/release-plan#19]
KDE edition goes into power savings during installing with **Calamares**. We should disable **power savings** completely in **live-session**.

**Comment by philmmanjaro** [comment]
https://github.com/manjaro/manjaro-tools-iso-profiles/commit/ad27d7048162619973027f4fd0cf62fe28d0a0a2 fixes this for KDE. However we have to check if other desktop environments are also affected by this ...

**Comment by philmmanjaro** [comment]
At least Gnome is still affected by this ...

**Comment by Ste74** [comment]
If gnome Is affect i Think also budgie but not check because in my test
installation use thus. Budgie and gnome are related.
Il 02/nov/2015 09:40, "Philip Müller" <notifications@github.com> ha scritto:

**Comment by philmmanjaro** [comment]
@Ste74: it is not related to any installer, but do the fact if you don't type or move your mouse you will get into power savings by screen lock and later display power down. So for each DE we have to find a way to disable those settings at least in **live-session**.

**Comment by philmmanjaro** [comment]
It is fixed for **XFCE** and **KDE**. Still open for Budgie, Gnome and other community editions.
