### ISSUE TITLE
XFCE-GTK3 takes longer to load desktop

### ISSUE THREAD

**Issue by philmmanjaro** [manjaro/release-plan#197]
In live-session I detected that the destkop loads longer than usual. However this also happens with TTY ...

**Comment by philmmanjaro** [comment]
Happens also with 416 ...

**Comment by oberon2007** [comment]
Hm. 414? ;-)

**Comment by philmmanjaro** [comment]
We will see what it is. We are still in the alpha state anyway ...

**Comment by oberon2007** [comment]
I appear to have a similar issue with a current i3 unstable ISO with linux417 in vbox. Will try to compare to kernel 414 now.

**Comment by oberon2007** [comment]
We also should check if switching to regular gtk3 instead of gtk3-classic makes a difference!

**Comment by oberon2007** [comment]
**gtk3** vs **gtk3-classic** makes no difference.

**Comment by oberon2007** [comment]
To me it appears that the loading of the i3 desktop is normal while using **linux414** and slowed down with **416** or **417**.
Also with the newest kernels about every other time lightdm-slick-greeter refuses to start. I haven't found an error message in the logs, yet. System simply hangs without either the DM showing up (when trying to re-log) or when autologin is supposed to be happening.
Will try to find out if the same problem exists with lightdm-gtk-greeter for me.

**Comment by oberon2007** [comment]
Same issue with lightdm-gtk-greeter and linux417.
Since this problem is not present on my installed system, which also uses linux416, my best guess currently is that the issue is related to the **virtualbox-modules** for linux416 and 417.
Also [this strange observation](https://forum.manjaro.org/t/bspwm-v17-1-7-stable-isos-released/43687/22) could be caused by **linux416-virtualbox-modules** (this bspwm build uses 416)

**Comment by Phoenix1747** [comment]
> Also with the newest kernels about every other time lightdm-slick-greeter refuses to start. I haven't found an error message in the logs, yet. System simply hangs without either the DM showing up (when trying to re-log) or when autologin is supposed to be happening.
@oberon2007 

Does this only concern 4.17 and the latest testing lightdm/VBox version? Because I'm using lightdm-gtk-greeter from stable branch with kernel 4.16 and the virtualbox-host-modules and everything is perfectly fine.

**Comment by philmmanjaro** [comment]
Seems also KDE seems to be affected. Only our Gnome edition seems to be kinda fine. I've to see how it will act in a later state. **linux417** is still in early development ...

**Comment by philmmanjaro** [comment]
Seems **linux417 4.17.r180429.cdface5-2** fixes this, however we have still weird issues within CAL not able to click on dialogs with mouse. Maybe a VBox issue. Didn't had time to test on real HW.

**Comment by philmmanjaro** [comment]
Also **linux416 4.16.5** has no issue with this anymore. Also less regressions than **linux417** as of now ...

**Comment by philmmanjaro** [comment]
Seems to be related to an old friend: https://github.com/systemd/systemd/issues/4167
