### ISSUE TITLE
replace gksu

### ISSUE THREAD

**Issue by oberon-manjaro** [manjaro/release-plan#200]
**gksu** has been deprecated so we need to use alternatives.
Where **pkexec** isn't they way to go, **zensu** seems to be a simple and good option.
@manjaro/maintainers 

Current state of `manjaro:desktop-settings` repo:
```
[bernhard@manjaro-sx desktop-settings]$ grep -re gksu .
./community/bspwm-minimal/skel/.config/GTKmenu/appmenu:	cmd = gksu isousb
./community/bspwm-minimal/skel/.config/GTKmenu/appmenu:	cmd = gksu -l gnome-terminal
./community/bspwm-minimal/skel/.config/GTKmenu/appmenu:			cmd = gksu-properties
./community/bspwm-minimal/skel/.config/dconf/user.d/everything.conf:command-history=['poweroff', 'dmenu', 'pkill docky', 'gksu bleachbit', 'killall docky']
./community/openbox/skel/.config/Thunar/uca.xml:	<command>gksu thunar %f</command>
./community/openbox/skel/.local/share/file-manager/actions/root.desktop:Exec=/usr/bin/gksu /usr/bin/pcmanfm %u
./community/cinnamon/skel/.local/share/applications/nemo-root.desktop:Exec=gksu nemo
./community/cinnamon/skel/.local/share/applications/nemo-root.desktop:Icon=gksu
./community/jwm/skel/.jwm/menu:        <Program label="Root">gksu pcmanfm /</Program>
./community/jwm/skel/.jwm/menu:            <Program label="Gufw Firewall">gksu gufw</Program>
./community/jwm/skel/.jwm/menu:            <Program label="Privilege Granting">gksu-properties</Program>
./community/jwm/skel/.jwm/menu:            <Program label="Root File Manager">gksu pcmanfm /</Program>         
./community/jwm/skel/.jwm/menu:            <Program label="Root Terminal">gksu sakura</Program>            
./community/fluxbox/skel/.config/fbmenugen/schema.pl:{item =>	['gksu pcmanfm',		'Root File Manager',	'root-file-manager']},
./community/fluxbox/skel/.config/fbmenugen/schema.pl:  {item =>	['gksu lightdm-gtk-greeter-settings','LightDM Greeter',	]},
./community/fluxbox/skel/.fluxbox/menu:  [exec] (Root File Manager) {gksu pcmanfm}
./community/fluxbox/skel/.fluxbox/menu:  [exec] (Root Terminal) {gksu -l gnome-terminal}
./community/fluxbox/skel/.fluxbox/menu:  [exec] (Privilege granting) {gksu-properties}
./community/fluxbox/skel/.fluxbox/menu:  [exec] (LightDM Greeter) {gksu lightdm-gtk-greeter-settings}
./community/budgie/skel/.local/share/applications/gksu.desktop:Comment=Opens a terminal as the root user, using gksu to ask for the password
./community/budgie/skel/.local/share/applications/gksu.desktop:Exec=gksudo -l gnome-terminal
./community/budgie/skel/.local/share/applications/gksu.desktop:Icon=gksu-root-terminal
./community/lxde/skel/.config/lxsession-default-apps/settings.conf:terminal_manager/installed=Root Terminal,gksu,gksu-root-terminal,/usr/share/applications/gksu.desktop,;LXTerminal,lxterminal,lxterminal,/usr/share/applications/lxterminal.desktop,;UXTerm,uxterm,xterm-color_48x48,/usr/share/applications/uxterm.desktop,;XTerm,xterm,xterm-color_48x48,/usr/share/applications/xterm.desktop,;
./community/lxde/skel/.local/share/file-manager/actions/openfolderasroot.desktop:Exec=gksudo pcmanfm %u
./community/lxde/skel/.local/share/file-manager/actions/editasroot.desktop:Exec=gksudo leafpad %f
./community/lxde/skel/.local/share/file-manager/actions/editasroot.desktop:Exec=gksudo leafpad %f
./community/pantheon/skel/.local/share/contractor/folder-openasroot.contract:Exec=gksudo pantheon-files %U
./community/pantheon/skel/.local/share/contractor/file-openasroot.contract:Exec=gksudo scratch-text-editor %U
./community/deepin/skel/.local/share/applications/root-filemanager.desktop:Icon=gksu
./community/bspwm-mate/skel/.config/GTKmenu/appmenu:	cmd = gksu isousb
./community/bspwm-mate/skel/.config/GTKmenu/appmenu:	cmd = gksu -l gnome-terminal
./community/bspwm-mate/skel/.config/GTKmenu/appmenu:			cmd = gksu-properties
./community/bspwm/skel/.config/GTKmenu/appmenu:	cmd = gksu isousb
./community/bspwm/skel/.config/GTKmenu/appmenu:	cmd = gksu -l gnome-terminal
./community/bspwm/skel/.config/GTKmenu/appmenu:			cmd = gksu-properties
./community/bspwm/skel/.config/dconf/user.d/everything.conf:command-history=['poweroff', 'dmenu', 'pkill docky', 'gksu bleachbit', 'killall docky']
```
also we have:
```
[bernhard@manjaro-sx xfce-settings]$ grep -re gksu .
./skel/.config/Thunar/uca.xml:	<command>gksu dbus-launch thunar</command>
```
and in package lists still:
```
[bernhard@manjaro-sx iso-profiles]$ grep -re gksu .
./community/awesome/Packages-Desktop:gksu
./community/lxde/Packages-Desktop:gksu
./community/bspwm-mate/Packages-Desktop:gksu
./manjaro/xfce/Packages-Desktop:gksu
```
hits in community repo:
```
[bernhard@manjaro-sx community]$ grep -re gksu .
./python-xapp/PKGBUILD:            "gksu: Fallback authentication method for the GNOME desktop and derivatives"
./spacefm/PKGBUILD:            'gksu: perform as root functionality'
./sublime-text-dev/PKGBUILD:optdepends=('gksu: sudo-save support')
./snapper-gui/PKGBUILD:optdepends=('gksu: Access snapper-gui from application menu under GTK-base DE'
./snapper-gui/snapper-gui.desktop:Exec=[ -f /usr/bin/gksu ] && exec gksu snapper-gui || exec kdesu snapper-gui
./timeset-gui/PKGBUILD:depends=('gksu' 'python2-gobject' 'ntp')
./mhwd-chroot/PKGBUILD:optdepends=('gksu: gnome gui for su'
./fbmenu-manjaro/schema.pl:{item =>	['gksu pcmanfm',		'Root File Manager',	'root-file-manager']},
./fbmenu-manjaro/schema.pl:  {item =>	['gksu lightdm-gtk-greeter-settings','LightDM Greeter',	]},
./isousb/PKGBUILD:depends=('zenity' 'gksu')
./compiz-manjaro/src/~compiz-team/compiz/0.9.13/plugins/animation/src/animation.cpp:/// like the dimming layer of gksudo and x-session-manager.
./compiz-manjaro/src/~compiz-team/compiz/0.9.13/plugins/animation/src/animation.cpp:    // Never animate screen-dimming layer of logout window and gksu.
./compiz-manjaro/src/~compiz-team/compiz/0.9.13/plugins/animation/src/animation.cpp:    mNeverAnimateMatch |= "title=gksu";
./lxmed/PKGBUILD:depends=('gksu' 'java-runtime')
./octopi/PKGBUILD:              'gksu: for XFCE, Gnome, LXDE, Cinnamon'

```

**Comment by oberon2007** [comment]
@Chrysostomus is there a way to store the password in keyring with **zensu**? Atm it is asking for password every time again ... ?

**Comment by Chrysostomus** [comment]
Gnome-keyring could possibly be used for this? It could be added as optdepend.

I wonder if it would be better if zensu checked if there is a polkit agent running, and if so, just prepended pkexec to command instead of sudo with password query? Advent of polkit is why gksu was decrepated in the first place. This would get around the problem of apps that still  depend on gksu.

**Comment by oberon2007** [comment]
Well, I realize that pkexec also normally doesn't remember passwords, or does it? Maybe that's just **sudo** behaviour?
In any case 
> if so, just prepended pkexec to command

For some application I have tried sofar that would seem to work, however for some reason:
```
[bernhard@manjaro-sx ~]$ pkexec pcmanfm
Cannot open display:
```

**Comment by Chrysostomus** [comment]
Pass might be another option to store passwords here...

**Comment by Ste74** [comment]
Pkexec use a xml file wich contain the rules for work.. If app not provide the xml file pkexec not work.. Sudo is not better to run the graphical app for security reason.. Gksu etc. Solve this but again for security reason is not better so wayland and gnome want pkexec as standard...

**Comment by Chrysostomus** [comment]
I'm in a bit weird place with the adoption of zensu. I wrote it, but if it's going to be used more widely, it needs some significant improvement. It was originally designed to avoid the gtk2 dependency of gksu, then updated to avoid the webkit dependency of zenity. It was a bit of a hack to begin with.

**Comment by Chrysostomus** [comment]
If a password can be piped to pkexec, then that would be viable:

1) test for polkit agent
2) if available, pipe the password to pkexec and fall back to sudo if necessary
3) if no polkit agent running, use sudo

**Comment by fhdk** [comment]
I was just poking around to see what others have done and stumpled on this.

I have not read it in full yet but would share
https://code.launchpad.net/~roadmr/checkbox/1097816-pkexec/+merge/171930

**Comment by fhdk** [comment]
So to make any program able to run with elevated rights, as @Ste74 already noted, it requires  the presence of a policy file.

Sample file for gedit

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE policyconfig PUBLIC
 "-//freedesktop//DTD PolicyKit Policy Configuration 1.0//EN"
 "http://www.freedesktop.org/standards/PolicyKit/1/policyconfig.dtd">
<policyconfig>
    <action id="org.freedesktop.policykit.pkexec.gedit">
    <description>Run gedit program</description>
    <message>Authentication is required to run the gedit</message>
    <icon_name>accessories-text-editor</icon_name>
    <defaults>
        <allow_any>auth_admin</allow_any>
        <allow_inactive>auth_admin</allow_inactive>
        <allow_active>auth_admin</allow_active>
    </defaults>
    <annotate key="org.freedesktop.policykit.exec.path">/usr/bin/gedit</annotate>
    <annotate key="org.freedesktop.policykit.exec.allow_gui">true</annotate>
    </action>
</policyconfig>
```
An idea would be create a program which has the necessary policy file to act as a wrapper for starting GUI apps?

---

https://askubuntu.com/questions/287845/how-to-configure-pkexec

This one works around it by setting the variables preventing pkexec to run gui as root

    pkexec env DISPLAY=$DISPLAY XAUTHORITY=$XAUTHORITY gedit

---

**Comment by fhdk** [comment]
Another bypass operation

https://unlockforus.com/bypass-pkexec-password-prompt-admin-accounts/

**Comment by fhdk** [comment]
https://github.com/linuxmint/synaptic/blob/master/debian/synaptic-pkexec

**Comment by fhdk** [comment]
Wayland + Gnome

https://ubuntuforums.org/showthread.php?t=2374812

if [ $XDG_SESSION_TYPE = "wayland" ]; then xhost +si:localuser:root; fi

**Comment by Tids** [comment]
Why do we need a gksu replacement in the first place? I mean there is a good reason that it's not here anymore and linux moves on to polkit.
Also I dont like the approach to hijack pkexec, just to make something run on xwayland

**Comment by Chrysostomus** [comment]
1) repos and AUR still have some packages that use gksu internally even though they should not
2) some editions don't use polkit by default

That's the use case: transition period

**Comment by Tids** [comment]
To be realistic, ask yourself: Is there any progress for these missing parts to do the change to polkit? If yes -> transitioning phase is OK, if no: remove them from the repo, put them to the AUR.

gksu is in !aur, so thats nothing we have to care about.

For root terminal stuff we really should write bugreports, because calling them with gksu directly seems to be wrong, when its so easy to just run `sudo -i`, `pkexec` inside them and get root permissions

for gnome terminal
```gnome-terminal -- pkexec```
And gnome-terminal will actn as a root terminal.

For a polkit wrapper: please make sure you dont make things worse for wayland users, we dont want to start apps via Xwayland, because of something. One of the next steps on the wayland roadmap is to remove the xwayland dependency, so if we create here new dependencies for X, someone has to work on it later again. 

That transitioning period is ongoing for about 10years and we're already at stage 4 (or somewhere at stage 6 of 10 in the real list, but I cant find this list anymore :-1:) 
1. make polkit work (including pkexec)
2. integrate polkit into applications
3. make polkit necessary for the desktop (thats wayland)
4. remove support for sudo helpers

**Comment by fhdk** [comment]
@Chrysostomus 

http://aur.archlinux.org/packages/gksu-polkit-git

**Comment by oberon-manjaro** [comment]
This looks great, I like! :smiley: :+1: 
How did you manage to inherit this repo? I was already looking at the AUR package and couldn't find anything useful via debian as it looks like they have restructured there git and also abandoned the package.
With versioning we normally don't necessarily follow the AUR at all costs. At the same time we try to avoid epoch if possible. So I would suggest you drop the epoch and bump version to 0.0.3, including the latest commits.
Also I'd suggest to include a link /usr/bin/gksu > /usr/bin/gsku-polkit
It conflicts gksu anyway and typing 'gksu-polkit' is a little unpractical.
Also like that existing config and scripts will contiune to work without modification :nerd_face:

**Comment by fhdk** [comment]
On Fri, 01 Jun 2018 06:08:49 -0700
Bernhard Landauer <notifications@github.com> wrote:

> This looks great, I like! :smiley: :+1: 
> How did you manage to inherit this repo? I was already looking at the AUR package and couldn't find anything useful via debian as it looks like they have restructured there git and also abandoned the package.
> With versioning we normally don't necessarily follow the AUR at all costs. At the same time we try to avoid epoch if possible. So I would suggest you drop the epoch and bump version to 0.0.3, including the latest commits.
> Also I'd suggest to include a link /usr/bin/gksu > /usr/bin/gsku-polkit
> It conflicts gksu anyway and typing 'gksu-polkit' is a little unpractical.
> Also like that existing config and scripts will contiune to work without modification :nerd_face: 

Already ahead of you.

I have already made an gksu-polkit.install which conflicts gksu and zensu and creates a symlink as you suggested.

-- 
FH <fh@uex.dk>

**Comment by oberon-manjaro** [comment]
> an gksu-polkit.install which conflicts gksu and zensu and creates a symlink

Both needs to be done in the PKGBUILD, not an .install. Otherwise pacman will not know of the symlink's existence!

**Comment by fhdk** [comment]
The PKGBUILD has both **post_install()** and **post_remove()** which is where it happens

```
post_install() {
    ln -s /usr/bin/gsku-polkit /usr/bin/gksu
}

post_remove() {
    rm -f /usr/bin/gksu
}
```

**Comment by oberon-manjaro** [comment]
That's what I mean, yes. It goes inside `package()` function.
In general, please push your files so we can actually see what we discuss :smiley:

**Comment by fhdk** [comment]
Like this?

```
package() {
  cd $pkgname
  make DESTDIR="$pkgdir" install
  install -Dm644 "$srcdir/gksu-polkit.service" \
    "$pkgdir/$(pkg-config systemd --variable=systemdsystemunitdir )/gksu.service"
  ln -s /usr/bin/gksu-polkit /usr/bin/gksu
}
```

**Comment by oberon-manjaro** [comment]
`ln -s gksu-polkit $pkgdir/usr/bin/gksu`
:wink:

**Comment by fhdk** [comment]
I noticed that pkg-config was replaced by pkgconf?

The package() function uses pkg-config - should I change it?

**Comment by fhdk** [comment]
https://github.com/aarnt/octopi/issues/380#issuecomment-503769593

**Comment by fhdk** [comment]
https://github.com/aarnt/octopi/issues/380#issuecomment-503769593
