### ISSUE TITLE
[openrc] figure out if we can drop upower-pm-utils

### ISSUE THREAD

**Issue by udeved** [manjaro/release-plan#21]
Currently, default upower should work with:

* kde
* xfce
* lxqt

No idea about the rest.

**Comment by philmmanjaro** [comment]
Do we now have any further insight on this topic?

**Comment by udeved** [comment]
Yes, it works with default upower for kde, however, it turns out, lxqt power management works better with upower-pm-utils.
i think we can close this, and let it be handled individually by profile maintainer.
