### ISSUE TITLE
GDM freeze

### ISSUE THREAD

**Issue by hansw-nlo** [manjaro/release-plan#212]
Dear all, 

Since it is unclear where to file a bug report I am trying it at this spot.

Situation: 

When I switch users in gnome (not using logout but Switch user) gdm will freeze. It works with logout. Seems like a long outstanding issue but nobody found a solution

Hardware: 

Intel® Core™ i9-10900X CPU @ 3.70GHz × 20
NVIDIA GeForce RTX 2060/PCIe/SSE2
Micro-Star International Co., Ltd. MS-7B94

Software:

Manjaro Linux; Build ID: rolling
64-bit 41.1 on X11

Dec 01 00:48:26 hans-desktop /usr/lib/gdm-x-session[2062]: (II) systemd-logind: releasing fd for 13:66
Dec 01 00:48:26 hans-desktop dbus-daemon[738]: [system] Activating via systemd: service name='org.freedesktop.Accounts' unit='accounts-daemon.service' requested by ':1.7' (uid=0 pid=775 comm="/usr/bin/gdm ")
Dec 01 00:48:26 hans-desktop gdm[775]: Gdm: Failed to contact accountsservice: Error calling StartServiceByName for org.freedesktop.Accounts: Refusing activation, D-Bus is shutting down.
Dec 01 00:48:26 hans-desktop systemd[1]: gdm.service: Main process exited, code=exited, status=1/FAILURE
Dec 01 00:48:26 hans-desktop systemd[1]: gdm.service: Failed with result 'exit-code'.
Dec 01 00:48:26 hans-desktop systemd[1]: gdm.service: Triggering OnFailure= dependencies.
Dec 01 00:48:26 hans-desktop audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 subj==unconfined msg='unit=gdm comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=failed'

If there is more info needed then please let me know.

**Comment by philmmanjaro** [comment]
Did you had a look into our forums yet: https://forum.manjaro.org/c/support/gnome/27

**Comment by hansw-nlo** [comment]
I did but it is a huge forum with sometimes answers that are incorrect. It is all bundled on one page. I did submit it to the gnome git but they stated I should first try it at Manjaro. Is there any git where issues are kept together?

**Comment by hansw-nlo** [comment]
Suppose nothing will be done with it, sad story.

**Comment by Chrysostomus** [comment]
What branch are you using? This used to sometimes happen to me, but with the recent updates in unstable I can no longer reproduce it.

Does it happen to you with both gdm and gdm-plymouth, or only on of those?

**Comment by hansw-nlo** [comment]
I am using the stable branch, afaik it was only on gdm since gdm-plymouth does not ring a bell. I can confirm it since the plymouth one is not installed.

**Comment by hansw-nlo** [comment]
Afaik plymouth is only there for the boot, my problem is located elsewhere (switching users)

**Comment by hansw-nlo** [comment]
I did a reinstall of Manjaro and now with oss drivers. On wayland and I can switch to another user.
