### ISSUE TITLE
sysctl is broken

### ISSUE THREAD

**Issue by hansw-nlo** [manjaro/release-plan#214]
Hi all, writing this here, imho a forum is not suited for handling issues. 

Sysctl in Manjaro is broken. Manjaro points to the Arch manual and there it is stated one should create files in the /etc/sysctl.d/ directory. However, a sysctl -p nags that /etc/sysctl.conf can't be found.

```
cd /etc/sysctl.d/
vi 50-namespace.conf
sysctl -p
```
sysctl: cannot open "/etc/sysctl.conf": No such file or directory

The fix is to simply move all entries to /etc/sysctl.conf and then it works

**Comment by fhdk** [comment]
You are using the wrong arguments.

when you use -p you are supposed to add a filename - if you don't sysctl.conf will be assumed and as it is not used the message is thrown

use `--system` instead

**Comment by hansw-nlo** [comment]
Using a filename is optional, see the man page. 

```
Load  in  sysctl   settings   from   the   file   specified   or
              /etc/sysctl.conf  if none given.  Specifying - as filename means
              reading data from standard input
```

The --system gets it from other locations. Imho their should either be a /etc/sysctl.conf or the code should be adjusted to not nag anyone about it.

**Comment by fhdk** [comment]
If you want to use `/etc/sysctl.conf` that's fine but the behavior is not a bug - the message is purely informational.

sysctl load configurations found `/etc/sysctl.d` on boot and when you initiate a reload using

    sysctl --system

If you want to reload a specific file - use 

    sysctl -p /path/to/config.conf
