### ISSUE TITLE
Manjaro 23.0 review

### ISSUE THREAD

**Issue by philmmanjaro** [manjaro/release-plan#218]
**Uranos 23.0** (2023-09-03)

### Full
https://download.manjaro.org/xfce/23.0/manjaro-xfce-23.0-230903-linux65.iso
https://download.manjaro.org/xfce/23.0/manjaro-xfce-23.0-230903-linux65.iso.sig
https://download.manjaro.org/xfce/23.0/manjaro-xfce-23.0-230903-linux65.iso.sha1
https://download.manjaro.org/xfce/23.0/manjaro-xfce-23.0-230903-linux65.iso.sha256
https://download.manjaro.org/xfce/23.0/manjaro-xfce-23.0-230903-linux65.iso.torrent
https://download.manjaro.org/xfce/23.0/manjaro-xfce-23.0-230903-linux65.iso.pkgs
### Minimal
https://download.manjaro.org/xfce/23.0/manjaro-xfce-23.0-minimal-230903-linux65.iso
https://download.manjaro.org/xfce/23.0/manjaro-xfce-23.0-minimal-230903-linux65.iso.sig
https://download.manjaro.org/xfce/23.0/manjaro-xfce-23.0-minimal-230903-linux65.iso.sha1
https://download.manjaro.org/xfce/23.0/manjaro-xfce-23.0-minimal-230903-linux65.iso.sha256
https://download.manjaro.org/xfce/23.0/manjaro-xfce-23.0-minimal-230903-linux65.iso.torrent
https://download.manjaro.org/xfce/23.0/manjaro-xfce-23.0-minimal-230903-linux65.iso.pkgs
### Minimal (linux61)
https://download.manjaro.org/xfce/23.0/manjaro-xfce-23.0-minimal-230903-linux61.iso
https://download.manjaro.org/xfce/23.0/manjaro-xfce-23.0-minimal-230903-linux61.iso.sig
https://download.manjaro.org/xfce/23.0/manjaro-xfce-23.0-minimal-230903-linux61.iso.sha1
https://download.manjaro.org/xfce/23.0/manjaro-xfce-23.0-minimal-230903-linux61.iso.sha256
https://download.manjaro.org/xfce/23.0/manjaro-xfce-23.0-minimal-230903-linux61.iso.torrent
https://download.manjaro.org/xfce/23.0/manjaro-xfce-23.0-minimal-230903-linux61.iso.pkgs
### Minimal (linux515)
https://download.manjaro.org/xfce/23.0/manjaro-xfce-23.0-minimal-230903-linux515.iso
https://download.manjaro.org/xfce/23.0/manjaro-xfce-23.0-minimal-230903-linux515.iso.sig
https://download.manjaro.org/xfce/23.0/manjaro-xfce-23.0-minimal-230903-linux515.iso.sha1
https://download.manjaro.org/xfce/23.0/manjaro-xfce-23.0-minimal-230903-linux515.iso.sha256
https://download.manjaro.org/xfce/23.0/manjaro-xfce-23.0-minimal-230903-linux515.iso.torrent
https://download.manjaro.org/xfce/23.0/manjaro-xfce-23.0-minimal-230903-linux515.iso.pkgs

### Full
https://download.manjaro.org/gnome/23.0/manjaro-gnome-23.0-230903-linux65.iso
https://download.manjaro.org/gnome/23.0/manjaro-gnome-23.0-230903-linux65.iso.sig
https://download.manjaro.org/gnome/23.0/manjaro-gnome-23.0-230903-linux65.iso.sha1
https://download.manjaro.org/gnome/23.0/manjaro-gnome-23.0-230903-linux65.iso.sha256
https://download.manjaro.org/gnome/23.0/manjaro-gnome-23.0-230903-linux65.iso.torrent
https://download.manjaro.org/gnome/23.0/manjaro-gnome-23.0-230903-linux65.iso.pkgs
### Minimal
https://download.manjaro.org/gnome/23.0/manjaro-gnome-23.0-minimal-230903-linux65.iso
https://download.manjaro.org/gnome/23.0/manjaro-gnome-23.0-minimal-230903-linux65.iso.sig
https://download.manjaro.org/gnome/23.0/manjaro-gnome-23.0-minimal-230903-linux65.iso.sha1
https://download.manjaro.org/gnome/23.0/manjaro-gnome-23.0-minimal-230903-linux65.iso.sha256
https://download.manjaro.org/gnome/23.0/manjaro-gnome-23.0-minimal-230903-linux65.iso.torrent
https://download.manjaro.org/gnome/23.0/manjaro-gnome-23.0-minimal-230903-linux65.iso.pkgs
### Minimal (linux61)
https://download.manjaro.org/gnome/23.0/manjaro-gnome-23.0-minimal-230903-linux61.iso
https://download.manjaro.org/gnome/23.0/manjaro-gnome-23.0-minimal-230903-linux61.iso.sig
https://download.manjaro.org/gnome/23.0/manjaro-gnome-23.0-minimal-230903-linux61.iso.sha1
https://download.manjaro.org/gnome/23.0/manjaro-gnome-23.0-minimal-230903-linux61.iso.sha256
https://download.manjaro.org/gnome/23.0/manjaro-gnome-23.0-minimal-230903-linux61.iso.torrent
https://download.manjaro.org/gnome/23.0/manjaro-gnome-23.0-minimal-230903-linux61.iso.pkgs
### Minimal (linux515)
https://download.manjaro.org/gnome/23.0/manjaro-gnome-23.0-minimal-230903-linux515.iso
https://download.manjaro.org/gnome/23.0/manjaro-gnome-23.0-minimal-230903-linux515.iso.sig
https://download.manjaro.org/gnome/23.0/manjaro-gnome-23.0-minimal-230903-linux515.iso.sha1
https://download.manjaro.org/gnome/23.0/manjaro-gnome-23.0-minimal-230903-linux515.iso.sha256
https://download.manjaro.org/gnome/23.0/manjaro-gnome-23.0-minimal-230903-linux515.iso.torrent
https://download.manjaro.org/gnome/23.0/manjaro-gnome-23.0-minimal-230903-linux515.iso.pkgs

### Full
https://download.manjaro.org/kde/23.0/manjaro-kde-23.0-230903-linux65.iso
https://download.manjaro.org/kde/23.0/manjaro-kde-23.0-230903-linux65.iso.sig
https://download.manjaro.org/kde/23.0/manjaro-kde-23.0-230903-linux65.iso.sha1
https://download.manjaro.org/kde/23.0/manjaro-kde-23.0-230903-linux65.iso.sha256
https://download.manjaro.org/kde/23.0/manjaro-kde-23.0-230903-linux65.iso.torrent
https://download.manjaro.org/kde/23.0/manjaro-kde-23.0-230903-linux65.iso.pkgs
### Minimal
https://download.manjaro.org/kde/23.0/manjaro-kde-23.0-minimal-230903-linux65.iso
https://download.manjaro.org/kde/23.0/manjaro-kde-23.0-minimal-230903-linux65.iso.sig
https://download.manjaro.org/kde/23.0/manjaro-kde-23.0-minimal-230903-linux65.iso.sha1
https://download.manjaro.org/kde/23.0/manjaro-kde-23.0-minimal-230903-linux65.iso.sha256
https://download.manjaro.org/kde/23.0/manjaro-kde-23.0-minimal-230903-linux65.iso.torrent
https://download.manjaro.org/kde/23.0/manjaro-kde-23.0-minimal-230903-linux65.iso.pkgs
### Minimal (linux61)
https://download.manjaro.org/kde/23.0/manjaro-kde-23.0-minimal-230903-linux61.iso
https://download.manjaro.org/kde/23.0/manjaro-kde-23.0-minimal-230903-linux61.iso.sig
https://download.manjaro.org/kde/23.0/manjaro-kde-23.0-minimal-230903-linux61.iso.sha1
https://download.manjaro.org/kde/23.0/manjaro-kde-23.0-minimal-230903-linux61.iso.sha256
https://download.manjaro.org/kde/23.0/manjaro-kde-23.0-minimal-230903-linux61.iso.torrent
https://download.manjaro.org/kde/23.0/manjaro-kde-23.0-minimal-230903-linux61.iso.pkgs
### Minimal (linux515)
https://download.manjaro.org/kde/23.0/manjaro-kde-23.0-minimal-230903-linux515.iso
https://download.manjaro.org/kde/23.0/manjaro-kde-23.0-minimal-230903-linux515.iso.sig
https://download.manjaro.org/kde/23.0/manjaro-kde-23.0-minimal-230903-linux515.iso.sha1
https://download.manjaro.org/kde/23.0/manjaro-kde-23.0-minimal-230903-linux515.iso.sha256
https://download.manjaro.org/kde/23.0/manjaro-kde-23.0-minimal-230903-linux515.iso.torrent
https://download.manjaro.org/kde/23.0/manjaro-kde-23.0-minimal-230903-linux515.iso.pkgs

Test Sheet
-------------------------

Call **calamares** via `sudo -E calamares -d` to have a terminal log for possible errors. Comment findings in this issue.
To test local mhwd repo call `pacman -Ss --config /opt/mhwd/pacman-mhwd.conf`. It is broken when no packages are listed. When office chooser is enabled you may filter with `office`

manjaro-xfce-23.0-230903-linux65.iso

- [x] application-utility works
- [x] mhwd local repo works
- [x] office pkg got installed fine

manjaro-xfce-23.0-minimal-230903-linux65.iso

- [x] application-utility works
- [x] mhwd local repo works

manjaro-xfce-23.0-minimal-230903-linux61.iso

- [x] application-utility works
- [x] mhwd local repo works

manjaro-xfce-23.0-minimal-230903-linux515.iso

- [x] application-utility works
- [x] mhwd local repo works

manjaro-gnome-23.0-230903-linux65.iso

- [x] application-utility works
- [x] mhwd local repo works
- [x] office pkg got installed fine

manjaro-gnome-23.0-minimal-230903-linux65.iso

- [x] application-utility works
- [x] mhwd local repo works

manjaro-gnome-23.0-minimal-230903-linux61.iso

- [x] application-utility works
- [x] mhwd local repo works

manjaro-gnome-23.0-minimal-230903-linux515.iso

- [x] application-utility works
- [x] mhwd local repo works

manjaro-kde-23.0-230903-linux65.iso

- [x] application-utility works
- [x] mhwd local repo works
- [x] office pkg got installed fine

manjaro-kde-23.0-minimal-230903-linux65.iso

- [x] application-utility works
- [x] mhwd local repo works

manjaro-kde-23.0-minimal-230903-linux61.iso

- [x] application-utility works
- [x] mhwd local repo works

manjaro-kde-23.0-minimal-230903-linux515.iso

- [x] application-utility works
- [x] mhwd local repo works

**Comment by philmmanjaro** [comment]
[manjaro-xfce-23.0-230903-linux65.iso](https://download.manjaro.org/xfce/23.0/manjaro-xfce-23.0-230903-linux65.iso) seems to have a broken **mhwd** repo. Possible need for a rebuild.

**Comment by philmmanjaro** [comment]
`manjaro-gnome-23.0-230903-linux65.iso` seems fine so far. I tested **libreoffice** as office and got installed fine. Also mhwd repo listed all packages added.

**Comment by HanzelM** [comment]
`manjaro-gnome-23.0-minimal-230903-linux65.iso` installs just fine, calamares log reports some warnings about invalid configs, not sure of this is relevant, included below.
<details><summary>Details</summary>

`Warning: config '/var/lib/mhwd/db/pci/network_drivers/r8168/MHWDCONFIG' is invalid!`
`Warning: config '/var/lib/mhwd/db/pci/network_drivers/rt3562sta/MHWDCONFIG' is invalid!`
`Warning: config '/var/lib/mhwd/db/pci/network_drivers/r8168/MHWDCONFIG' is invalid!`
`Warning: config '/var/lib/mhwd/db/pci/network_drivers/rt3562sta/MHWDCONFIG' is invalid!`
`Warning: config '/var/lib/mhwd/db/pci/network_drivers/r8168/MHWDCONFIG' is invalid!`
`Warning: config '/var/lib/mhwd/db/pci/network_drivers/rt3562sta/MHWDCONFIG' is invalid!`

</details> 

`pacman -Ss --config /opt/mhwd/pacman-mhwd.conf` reports a list of packages.
Minimal has no office option, install libreoffice fresh after reboot, works.

Test install done in virtmanager QEMU/KVM. things like screen resize, cursor grabbing/release are enabled by default.

**Comment by philmmanjaro** [comment]
@HanzelM thx for testing those two minimal ISOs of Gnome. I marked them as complete. Most of the other ISOs I tested where also fine. Most likely XFCE full needs a rebuild, however I do a redownload of the ISO to check it again. And yes, minimal ISOs don't ship with the office choice, hence I updated the check list.

**Comment by philmmanjaro** [comment]
Invalid mhwd configs are fine. Also **Manjaro-Hello** has the **Application** button which starts the **application-utility** after installation in **Hello**. So installing it from there is fine on minimal ISOs.

**Comment by philmmanjaro** [comment]
I did a redownload of the ISO XFCE 65 full. Seems I had a bad download. Signs of the laptop I'm using. The retest went fine.

**Comment by fhdk** [comment]
kde minimal linux 515 on bare metal
* application utilty works
* local mhwd works
* installer works / reboot

**Comment by philmmanjaro** [comment]
oK, then we can do a release of it.
