### ISSUE TITLE
Use linux43 as kernel

### ISSUE THREAD

**Issue by philmmanjaro** [manjaro/release-plan#22]
With this kernel series we would have following improvements:

**DRM / Graphics**

- Intel Skylake Graphics "Gen9" are enabled by default.
- A smothering of other Intel graphics changes
- Initial open-source support for the AMD R9 Fury "Fiji" graphics processors
- A big rework of the Nouveau DRM driver for open-source NVIDIA graphics support
- OpenGL 3.3 support for VMware.
- Various other DRM driver improvements
- Minimal FBDEV updates

**Disk / File-Systems**

- The EXT3 driver has been removed as support for existing EXT3 file-systems can be handled by the EXT4 driver
- Many fixes for XFS
- Btrfs RAID 5/6 and TRIM fixes
- Fixes for EXT4
- Fixes for F2FS

**Processors**

- A big Linux scheduler change that "Potentially Affects Every SMP Workload In Existence" but so far we haven't seen any regressions yet
- x86 boot time optimizations
- A variety of MIPS updates
- ARMv8.1 functionality is now supported by the Linux kernel
- Power management updates and the PowerClamp driver now supports Skylake.
- Numerous ARM SoC and platform additions.
- "Fake NUMA" for the S390.
- A few Xen updates for the Linux kernel.
- AMD Carrizo power data is now exposed by the fam15h_power kernel driver

**More Hardware**

- Various input driver updates.
- Wacom driver improvements.
- Intel Skylake sound support and other Linux audio improvements.
- Better Toshiba Linux laptop support

**Comment by philmmanjaro** [comment]
Seems **linux43** is not the right kernel. With **Manjaro 15.12-pre3** I'm using again **linux41**, or do you prefer a different kernel for this release?

**Comment by udeved** [comment]
I don't mind.
I would go for 15.12 with either 41 or 42 and wait until 43 is stabilized.

**Comment by philmmanjaro** [comment]
Lets see what the outcome of **pre3** is. **linux42** is an option. Catalyst seems to work with the "fix".

**Comment by udeved** [comment]
You may find it helpful. ;)

https://packages.gentoo.org/packages/sys-kernel/gentoo-sources

**Comment by markjes** [comment]
Stick with 4.1.

**Comment by alexandruianu** [comment]
The new CPU/GPU support is great if 4.3 can work well, but if it still has issues, go with 4.1 since it's LTS.

**Comment by philmmanjaro** [comment]
Most likely we will use **linux41** again for this one ...

**Comment by philmmanjaro** [comment]
We keep **linux41** for now.
