### ISSUE TITLE
verioning community editions

### ISSUE THREAD

**Issue by oberon2007** [manjaro/release-plan#23]
At the moment the versioning of community editions appears a bit messy, partly because of the discrepancy with release numbers in Manjaro-Welcome and Calamares.
Would it maybe just be best to stick to the versions of major releases and in case a community edition has a relaunch during the period of a quarter append a number like 15.12.1 ?

**Comment by philmmanjaro** [comment]
Fixed with https://github.com/manjaro/manjaro-welcome/issues/18
