### ISSUE TITLE
Update 'Beginners-Guide'

### ISSUE THREAD

**Issue by philmmanjaro** [manjaro/release-plan#24]
We should update our Beginners guide at least till RC2.

**Comment by philmmanjaro** [comment]
![calamares-bootloader](https://cloud.githubusercontent.com/assets/5050022/11514830/e59c67e4-987a-11e5-8eac-3b3d95965dbb.jpg)

I also suggest to adopt **Calamares 2.0** into our guide from now on ...

**Comment by philmmanjaro** [comment]
Seems our documentation team needs more time. However the basic stuff is already done ...

**Comment by philmmanjaro** [comment]
Well, **Calamares 2.0** seems not to be as ready as I want it to be. With RC2 I added 1.1.4 once again. Basically only the partition page layout is now back to the old one.

**Comment by philmmanjaro** [comment]
I updated now the cover, removed the release numbers and updated some of the pictures. Also we use now date-based release version of this document.

**Comment by philmmanjaro** [comment]
Since we plan to depreciate **Thus** we have to rewrite some of our **beginners guide** in that regard.

**Comment by udeved** [comment]
Btw, why do we have a 16.08?
I thought we go with a 3 month cycle, ie 16.09?
