### ISSUE TITLE
Decide if manjaro-tools 0.9.15 is ready for Capella

### ISSUE THREAD

**Issue by philmmanjaro** [manjaro/release-plan#25]
We have to check if the current development of **manjaro-tools** is ready to be used for Capella

**Comment by udeved** [comment]
From my tests, buildiso is ready, deployiso kind of ready.
All there rest hasn't changed much, just set loading has changed in general.
It is more robust now.

But agreed, we need some more testing and test builds, possibly squash some escaped little bugs before release.

**Comment by philmmanjaro** [comment]
I'll go for an RC then or I test the current dev-build if it is the same thing on Monday.

**Comment by udeved** [comment]
user config has moved to ~.config/manjaro-tools/manjaro-tools.conf.

If you have user sets, new place is ~.config/manjaro-tools/{pkg,iso}.d

So probably good idea to rebuild git package, and move user config.

**Comment by philmmanjaro** [comment]
Ok, will take a look at it at least on Monday when I build **15.12-rc1** ...

**Comment by udeved** [comment]
Ah, and devel branch only works with the test repo on my account, iso-profiles.

**Comment by philmmanjaro** [comment]
Ok, this means I've to do a master build to test the current changes we have in the official profiles for now ...

**Comment by udeved** [comment]
Yes, I did kind of freeze master to be working with 'old' repo.

We need to decide how we do transition after your build.

The test repo shouldn't be far behind, if at all.
I could do transfer of repo and you update profile if necessary over WE.

**Comment by philmmanjaro** [comment]
I pushed out the [rc](https://github.com/manjaro/packages-extra/commit/68e5e6c3bf08305bd1bed25358f0b7f90211ca0b). Lets do this profile changes after **15.12-rc1**. I really see no rush in it.

**Comment by oberon2007** [comment]
Just built a Deepin-ISO with the new iso-profiles structure and **manjaro-tools-r1753.44570ca** and works flawlessly. Thank you @udeved ! :)

**Comment by udeved** [comment]
commit ba386036bbfb96f3aa08b25c29ac474e2e553747

**Comment by udeved** [comment]
@philmmanjaro 

Do you think its a viable way to do migration with update script?
We would just set a deadline for last commit, then run update, and teams needs to pull and we are done.

**Comment by philmmanjaro** [comment]
@udeved: if it works as you designed it. We have to double check it anyway on Saturday. A deadline is always good.

**Comment by philmmanjaro** [comment]
Not tested yet for building an ISO but the feedback from other developers are fine so far.
