### ISSUE TITLE
I'd love to have a lxqt-maia theme

### ISSUE THREAD

**Issue by udeved** [manjaro/release-plan#27]
As title says, I would love to maiaize lxqt session, so panel menu matches better for maia icons.

Basically some qss work and pixel pushing.

**Comment by excalibur1234** [comment]
i can help you to test it.

i always use lxqt with a vertical panel on the left screen edge with a dark theme. for the last half year, i have used menda-dark theme.

**Comment by udeved** [comment]
I have got a sddm maia and lxqt maia theme in the works.
lxqt maia is based off the dark theme, just altered menu hover colors etc

I would inform you when its packaged, thanks a lot.

**Comment by philmmanjaro** [comment]
That would be great. Keep me in the loop.

**Comment by udeved** [comment]
Once we sorted out the community thingy, it frees some time.
I currently don't get much done on this front, spent last month dealing with community issues almost entirely.

**Comment by philmmanjaro** [comment]
Well I think it will come down to this:

* Deepin by @oberon2007
* Mate by @coffeeking (sonar)
* Gnome by @coffeeking (sonar)
* LxQT by @udeved 

Or do we have any other **community edition** maintained by one of the **core team**.

**Comment by udeved** [comment]
Is there someone who could tweak the lxqt frost theme colors to match breath theme @manjaro/maintainers @manjaro/packagers ?

**Comment by Ste74** [comment]
@udeved  where is the theme ?

**Comment by udeved** [comment]
Its provided by standard lxqt install, I think it is in package lxqt-panel @Ste74 .

**Comment by Ste74** [comment]
Have you try to ask at one of the author of the theme ? I see lxqt team point in our wiki to explain how to modified or created one theme .. also one of the author of theme is italian 😄
