### ISSUE TITLE
Use linux 4.4-lts as kernel

### ISSUE THREAD

**Issue by philmmanjaro** [manjaro/release-plan#28]

**Comment by excalibur1234** [comment]
linux 4.4 will be the next LTS kernel. it looks like the best choice at this point in time.
this might change within the next 4 months, though.

**Comment by philmmanjaro** [comment]
There will be only one LTS by upstream. For 2016 it is 4.4 as every year the kernel in January will be LTS. This was decided by upstream and all supporting companies from the industry.
