### ISSUE TITLE
Release Torrents on Release-Day

### ISSUE THREAD

**Issue by philmmanjaro** [manjaro/release-plan#30]
For all given editions our Torrents should be ready on Release-Day

**Comment by Strit** [comment]
I usually do my best to make that possible.

**Comment by philmmanjaro** [comment]
ISO images are online now:

- [Manjaro 16.06 XFCE (32bit)](http://sourceforge.net/projects/manjarolinux/files/release/16.06/xfce/manjaro-xfce-16.06-x86_64.iso)
- [Manjaro 16.06 XFCE (64bit)](http://sourceforge.net/projects/manjarolinux/files/release/16.06/xfce/manjaro-xfce-16.06-i686.iso)
- [Manjaro 16.06 KDE (32bit)](http://sourceforge.net/projects/manjarolinux/files/release/16.06/kde/manjaro-kde-16.06-x86_64.iso)
- [Manjaro 16.06 KDE (64bit)](http://sourceforge.net/projects/manjarolinux/files/release/16.06/kde/manjaro-kde-16.06-i686.iso)
- [Manjaro 16.06 NetInstall (32bit)](http://sourceforge.net/projects/manjarolinux/files/release/16.06/netinstall/manjaro-net-16.06-x86_64.iso)
- [Manjaro 16.06 NetInstall (64bit)](http://sourceforge.net/projects/manjarolinux/files/release/16.06/netinstall/manjaro-net-16.06-i686.iso)

We also have **signature** (.sig) files, **build logs** (-build.log) and **check sums** (-sha1sum.txt, -sha256sum.txt). Please keep track on #59 before creating those **torrent files** ...

**Comment by Strit** [comment]
Torrents are now released at https://sourceforge.net/projects/manjarotorrents/files/release/16.06/
