### ISSUE TITLE
Proposal for Gnome de 16.06

### ISSUE THREAD

**Issue by Ste74** [manjaro/release-plan#31]
I have this idea in my head and I would submit to you. I would like to split gnome: gnome with minimal gnome vanilla and very few programs (now gnome is vanilla and 1.6GB in ISO) for the geeks and the community version no longer vanilla and with a look and feel more attractive and more useful extensions.
What do you think ?

**Comment by udeved** [comment]
I think this is more a general point we should discuss.

I am all for making a minimal DE default, only with a few apps, and the big editions will be an extra.

**Comment by Ste74** [comment]
is my thoughts

**Comment by Ste74** [comment]
Gnome 16.06 is out so i can close :smile:
