### ISSUE TITLE
Proposal for next releases

### ISSUE THREAD

**Issue by Ste74** [manjaro/release-plan#32]
I have talk whit  @oberon2007 for this .. do you think if for any de supported in manjaro we create a plymouth theme whit the logo de and manjaro word ( like deepin plymouth ) . I know not all people like plymouth but more people like it for eyes pleasure . At moment all plymouth theme are logo+word manjaro :p

**Comment by oberon2007** [comment]
Here's the looks of what we currently have: https://forum.manjaro.org/index.php?topic=30723.msg253351#msg253351 I think you already have more, @Ste74 , don't you?
I like your idea of a common style for all flavors with a distinctive attribute - maybe different colors, too? - to every individual spin. Of course this mainly concerns community editions but I love the idea of finding a common line there. 
Actually creating or modifying plymouth themes is really no big deal at all!

**Comment by udeved** [comment]
I think we all should concentrate on maia theming,because it provides a unified look on gtk and qt DE.

**Comment by oberon2007** [comment]
well in the plymouth it's nothing more than a question of choosing a font and a color ... - so that would mean, maia-green? hm. I'm not sure that everything will look too good in that color ;)

**Comment by udeved** [comment]
No clue, openrc doesn't use plymouth.
I kind of like seeing whats going on when system boots.

**Comment by Ste74** [comment]
LOL .. @udeved you are on the side of those who do not use plymouth :-)
but don't worry my request is only for talking whit us.. is not a priority.. only fun for people if want ;-)

**Comment by oberon2007** [comment]
I'm not good with colors, @Ste74 :stuck_out_tongue_winking_eye: but how about something like that for Gnome? I was just trying to follow the default background of the latest Gnome edition, but can be any color of course... Or better inverted, like, just the foot in color? How about Budgie and Pantheon? Do they have their own logos?

![gnome_preview](https://cloud.githubusercontent.com/assets/11800714/13198873/f84637e2-d814-11e5-8110-f321ba88f9ab.png)

**Comment by oberon2007** [comment]
or maybe with a gradient, a little more fancy?
![gnome_preview_gradient](https://cloud.githubusercontent.com/assets/11800714/13198937/c733ee2c-d816-11e5-9445-7bccaefe06b2.png)

**Comment by Ste74** [comment]
Yep @oberon2007 fancy stuff , i like it :smile: Have you used gimp ? 
pantheon > https://www.google.it/search?q=elementary+logo&biw=1252&bih=584&tbm=isch&tbo=u&source=univ&sa=X&ved=0ahUKEwiWi8WSnYfLAhVE6xQKHc_UA94QsAQIGw#tbm=isch&q=elementaryos+logo

Budgie > http://solusart.blogspot.it/

**Comment by oberon2007** [comment]
![gnome_foot_preview](https://cloud.githubusercontent.com/assets/11800714/13199573/7ebe5ec6-d829-11e5-9551-6013ab2eae3d.png) :laughing:

**Comment by oberon2007** [comment]
You can test **plymouth-theme-manjaro-gnome** already - I think it looks quite sweet :smiley:

**Comment by Ste74** [comment]
:+1:  :+1:  i like it :wink: i see announce in our forum look very cool

**Comment by Ste74** [comment]
@oberon2007 i am crazy .. do you like them :stuck_out_tongue_winking_eye: 
https://youtu.be/X0i5kEhBUo8

**Comment by oberon2007** [comment]
OMG! You are!! :laughing: Chrchrchr! Very funny!
Tiny things: Why is birdy not centered in the spinner? And: Mind the spelling of
"Enjoy the simplicity" :stuck_out_tongue_winking_eye: 
I like it - It puts me in a good mood - so I think it would be awsome to have that every morning when you switch on your office computer... Don't you think?

**Comment by Ste74** [comment]
Ah ah lol this is only a draft build tonight in 15 min ..

**Comment by oberon2007** [comment]
Ah, sure! sorry!! ;) I'm such a pedant, oh my!

**Comment by Ste74** [comment]
:stuck_out_tongue:
