### ISSUE TITLE
Let us do a 16.03-minimal release

### ISSUE THREAD

**Issue by udeved** [manjaro/release-plan#34]
I really think we should do a 16.03, but since Phil is away, probably only minimal editions.

**Comment by philmmanjaro** [comment]
For doing a release the [user documentation](https://github.com/manjaro/manjaro-user-guide) needs to been updated. Any install media based on our **stable** branch will work. So I rather recommend to check if all is set and release some like **16.06-pre1**. 

Based on it Jonathon can do a documentation with **calamares** also. **thus** didn't changed. Somebody has also to update [manjaro welcome](https://github.com/manjaro/manjaro-welcome) and so on. So releasing just as is won't cut it. The date was set to be **16.06** as I'm away for almost one month and doing a release needs planning and several testbuilds, tested by the public.

So rather thinking on doing a 16.03 release, lets do 16.06 properly. 15.12 lacked proper documentation and it seems users need to know on how to install Manjaro side by side with Windows. This case is even not yet documented. And yes, if we plan to do a release **manjaro-tools** has to be on a frozen state when we go into RCs ...

I don't have to be always the release manager. So if anybody wants to step up, so please do. But remember not to rush it. A fast-tracked release might give bad publicity if not fully out tested ...

**Comment by udeved** [comment]
Well, we can also use the time and implement some pacman hooks, and leave out 16.03.

My reason of having a 16.03 is only to introduce settings packages o install media, so users don't have to manually clean /etc/skel any longer.

**Comment by oberon2007** [comment]
I wanted to ask that already: How about removing /etc/skel by .install skript? Would that be bad practice?

**Comment by oberon2007** [comment]
oh. I will not solve the conflict, right?

**Comment by udeved** [comment]
Would probably ideal test for a pacman hook that removes /etc/skel and reinstalls bash & manjaro-base-skel

**Comment by oberon2007** [comment]
Theoretically this could also be accomplished with manjaro-system ...

**Comment by udeved** [comment]
I have just posted on that, I think we can replace manjaro-system with pacman hooks.

**Comment by oberon2007** [comment]
ah ok. :no_mouth:

**Comment by Kirek** [comment]
We should just leave the old installations as they are, there a to many versions and community editions to test everything and we don't want to chance breaking the creation of a new user by doing this, or remove customizations made by users in skel.

**Comment by udeved** [comment]
That's also a possibility.
I just think, from the pov of transition to settings packages considerably keeps 15.12 usage around, in my estimation at least until autumn. Would somehow need to think about how to ease this if we don't di 16.03.

**Comment by oberon2007** [comment]
The normal scenario to actually use the settings packages I think is anyway that someone deliberately decides to create a new user with an updated or new environment...
