### ISSUE TITLE
do we still need to ship Thus? 

### ISSUE THREAD

**Issue by philmmanjaro** [manjaro/release-plan#40]
**calamares** seems to be in great shape. Is **thus** still needed? We also have to think about updating our beginners guide.

**Comment by oberon2007** [comment]
What about encrytion? Did I miss that or is Calamares already capable of that?

**Comment by philmmanjaro** [comment]
Encryption is still planned, but not yet added. Also we had some issues due encryption. Some of the community editions already dropped thus. If we still want to keep it we should also check cnchi and maybe adopt some fixes/changes

**Comment by oberon2007** [comment]
I have met [this issue](https://github.com/manjaro/thus/issues/43) now in several profiles ...
Encryption is being discussed quite a lot in the forum and I would say to not offer the a tool for that is just not really an option.

**Comment by Esclapion** [comment]
CLI works for encryption ?

**Comment by Kirek** [comment]
@coffeeking mentioned that Calamares may have accessibility issues (I don't know the details)

**Comment by coffeeking** [comment]
hi
Yes, thus is still needed for sonar. Calamares isn't yet visible to
orca, so thus is needed temporarily until the calamares bugs are fixed.
One of the biggest problems right now is that orca simply can't see the
calamares window. If that can be fixed, calamares would be nearly 100
percent accessible. It used to be visible, several months ago, but some
bug or other made it invisible to orca.
Thanks
Kendell Clark


Ramon Buldó wrote:

**Comment by philmmanjaro** [comment]
Yes we have to see why orca doesn't see it. Was the 1.x series visible?

**Comment by coffeeking** [comment]
hi
Yes, 1.x was visible for a while. I can't remember exactly when it
became invisible, I'm sorry. I keep trying, but I removed it from my
computer for a couple of months, then when I added it again to make sure
our branding stuff still worked, it was inaccessible.
Thanks
Kendell Clark


Philip Müller wrote:

**Comment by udeved** [comment]
Could we add jovie for sonar in live layer?
Not yet fully ported, but its kde screen reader.

**Comment by coffeeking** [comment]
hi
This is an option, but to be honest, I'd rather calamares be made 
accessible so orca can read it. I'm not sure if jolie would be able to 
read it if orca can't, but I'll test this. I've tried contacting teo, on 
irc, but he never responded, so I need someone who will actively work 
with me to fix the accessibility issues. Thus is a very good installer, 
but it can't install alongside other OS's like calamares can, and that's 
an important missing feature. I hope I don't sound like I'm complaining, 
I'm not. You guys are fantastic, all of you. You go above and beyond to 
help all of us who need accessible software and sonar wouldn't exist 
without you.
Thanks
Kendell Clark

**Comment by philmmanjaro** [comment]
Write Teo an email or call him via Skype. He responds fast

**Comment by coffeeking** [comment]
hi
Email would probably be best. I cannot use skype because ... how to 
explain. Skype is qt4, which means you need an accessibility plugin 
installed to access apps written in it. Skype is a 32 bit application, 
and arch doesn't have a 32 bit qt-at-spi package, so skype is unusable 
for screen reader users. If microsoft would meerly rebuild their app to 
make it 64 bit this wouldn't be necessary. That being said, I'd like to 
get calamares accessible so we can switch over to it in june. It's clear 
manjaro wants to drop thus, which is fair. We just need an installer we 
can use before thus can be dropped.
Thanks
Kendell Clark

**Comment by udeved** [comment]
Well, I don't think its best idea to mix kde/qt based stuff.
Since calamares is kf5 based, I think its worth to try jovie, because orca is gtk based.
Jovie is supposed to be orca equivalent.

**Comment by coffeeking** [comment]
hi
It's definitely worth trying it. I'll install them both and report back
on what I find
Thanks
Kendell Clark


udeved wrote:

**Comment by coffeeking** [comment]
hi
Just installed jovie. When attempting to launch it, it launches but
never speaks, so I'm not even sure if it still works. In any case, it
won't read the installer either.
Thanks
Kendell Clark


kendell clark wrote:

**Comment by teo** [comment]
I'm taking a look at the screen reader today.
@philmmanjaro if you are ready to move to Calamares as your main installer, can you please check what exactly you feel is still missing (besides screen reader support, and encryption which is coming soon) and report it to https://calamares.io/bugs ?

**Comment by coffeeking** [comment]
hi
Teo, since you don't need the screen reader, if you just want to see how
well calamares communicates with the accessibility stack, try running
accerciser. I hope I'm not mangling that. That will give you a ton of
info to help you debug and fix it. Of course you can still use orca if
you want to make sure it's reading what it should, but that's also an
option if you can't understand the speech. You'll need to install it,
sudo pacman -S accerciser should do it.
Thanks
Kendell Clark
 

Teo Mrnjavac wrote:

**Comment by philmmanjaro** [comment]
I'll do another preview this weekend. Then we see what is still missing. Encryption is planned. Accessibility is still an open point.

**Comment by jonathonf** [comment]
Until Calamares has feature-parity with Thus we should continue to ship Thus. However, it probably doesn't need a desktop icon (so Calamares is 'primary' installer and Thus becomes an 'alternate' installer).

**Comment by coffeeking** [comment]
hi
This brings up a point I think I've raised before, but can't remember.
When building the sonar profiles, the desktop icons still read as
install "manjaro" instead of install "sonar. Is it possible to change
this in the build scripts?
Thanks
Kendell Clark


jonathonf wrote:

**Comment by philmmanjaro** [comment]
Kendell, yes it is possible by shipping some overlay files in /usr/share/applications as manjaro-tools will use those and copy them to the desktop. Else we have to edit the files if needed before copying.

**Comment by oberon2007** [comment]
@philmmanjaro that's done already :smiley: 
https://github.com/manjaro/manjaro-tools-livecd/commit/609e87f234625482b62ed8847f04d017fa866e79

**Comment by teo** [comment]
![spectacle t29208](https://cloud.githubusercontent.com/assets/126364/14176669/72178524-f752-11e5-977c-0e6cd1bf1413.png)
I've ascertained that Calamares works with Orca and Accerciser, though some strings appear to be missing.
As with any Qt application, it requires QT_ACCESSIBILITY=1 to be exported.

**Comment by coffeeking** [comment]
hi
This is no longer true if calamares is qt5. How did you get around the
fact that when launched via sudo orca can't see it? That's the one thing
keeping me from fully switching over to it and leaving thus behind.
Thanks
Kendell Clark


Teo Mrnjavac wrote:

**Comment by teo** [comment]
This is built with Qt5 and it works fine, but sudo seems to be a problem. I suspect dbus might not be sharing the stuff we want between different users.

**Comment by coffeeking** [comment]
hi
Is there any chance this could get fixed? Maybe you could file a bug or
something? Running apps as root is aparticular problem in the mate
desktop. Gnome seems to have some way of getting around this, but mate
doesn't.
Thanks
Kendell Clark


Teo Mrnjavac wrote:

**Comment by teo** [comment]
@coffeeking I'm not sure yet, I'm still investigating. Running applications as root is a problem for more than just the screen reader, and it might be a blocker for running under Wayland (also not sure yet).
Certainly the "right" way to fix this is to always run Calamares as normal user and only escalate with polkit as needed, but this is not a quick and easy fix.

**Comment by coffeeking** [comment]
hi
I'd be willing to wait if we decide to run as normal user and elevate as
needed. As long as thus works I can use that until calamares is changed.
But I'll go along with whatever you guys want to do.
Thanks
Kendell Clark


Teo Mrnjavac wrote:

**Comment by teo** [comment]
@philmmanjaro can you please check whether it's feasible for you to run Orca as root on the live system? As long as the QT_ACCESSIBILITY variable is set and exported when running Calamares, it should work.

**Comment by philmmanjaro** [comment]
@coffeeking: please check if `export QT_ACCESSIBILITY=1` and starting **orca** with root rights solves your issue you have with **calamares**.

**Comment by coffeeking** [comment]
hi
I'll try this. I have my doubts that this will work because pulse audio
might refuse to allow the sound through. But I will test. I'm building
an image now, it's nearly complete.
Thanks
Kendell Clark


Philip Müller wrote:

**Comment by coffeeking** [comment]
hi
I was right. Unfortunately launching orca as root doesn't work. Orca
does launch, but no sound gets through because pulse audio blocks it.
This is why using speakup isn't easy with pulse audio installed, because
since speakup, being in the kernel, must run as root and espeakup, the
connector between speakup and espeak, must also run as root. I don't
know who's bug this is but this should get fixed. I've checked and our
mate and gnome profiles already export the qt_accessibility variable,
it's in our /etc/profile.d folder in a file called qt_accessibility.sh.
Just in case, I re-exported it, but it didn't do any good. I'm sorry to
have such bad news. Looks like sudo's the problem.
Thanks
Kendell Clark


Philip Müller wrote:

**Comment by philmmanjaro** [comment]
Ok, is **Calamares** accessible if you start it as normal user?

**Comment by coffeeking** [comment]
hi
Yes, almost completely. It's only when launched as root that I can't get
at it. Although, it usually won't start as normal user. The last few
times I've tried this it has errored out, I'm guessing because it needs
to be run as root.
Thanks
Kendell Clark


Philip Müller wrote:

**Comment by Ste74** [comment]
Officially is dropped no ? I think can close , Thus for the moment remain in the repo but not ship via install media . If wrong sorry and reopen :wink:
