### ISSUE TITLE
Ship samba?

### ISSUE THREAD

**Issue by LordTermor** [manjaro/release-plan#42]
I haven't find any reasons why samba isn't in Manjaro by default? It's too hard to understand how to make available usershares, install kdenetwork-filesharing for dolphin etc for newbie users. 
Just wanted to recommend Manjaro(as the only one user-friendy distro with the latest Plasma) for some of my friends who want to try Linux, but SMB support is neccesary for them and they are don't know how to setup it.

**Comment by Kirek** [comment]
Added kdenetwork-filesharing to the preinstalled packages. 
https://github.com/manjaro/manjaro-tools-iso-profiles/commit/c353c52fb26858627572c6fdba568ade7d79d23b
Anything else needed for proper samba support?

**Comment by LordTermor** [comment]
It's needed to properly configure usershares folder, as described in ArchWiki

**Comment by Kirek** [comment]
Ok, I looked at the article at it seems this will need some tweaking with the installer.
I will do it when I have time.

**Comment by philmmanjaro** [comment]
How much tweaking is needed? Can it be done also with **MSM**?

**Comment by Kirek** [comment]
I was thinking of a new calamares module that takes care of this, could be added to msm user creation too.

**Comment by philmmanjaro** [comment]
@Kirek: a module for **Calamares** is also fine :+1:

**Comment by udeved** [comment]
We currently do samba postcfg in CAL.
A module would require samaba detection at build time to configure CAL settings.conf.

Close?
