### ISSUE TITLE
Cleanup of all unmaintained/broken gtk themes

### ISSUE THREAD

**Issue by philmmanjaro** [manjaro/release-plan#43]
We have a lot of old themes still in our repositories which are broken. We should clean them up.

**Comment by Ste74** [comment]
The first in my mind is evopop .. tonight see if anyone have updated otherwise drop it ( but for drop it want deleted to our github repo community and delete the symlink in unstable branch ? )

**Comment by philmmanjaro** [comment]
We should only clean up the binary repositories with **boxit**. Git repos can be kept. Maybe somebody will pick them up later.

**Comment by philmmanjaro** [comment]
Here is a list of themes I think which are broken:
```
extra/menda-circle-icon-theme
extra/menda-lxqt-panel
extra/plasma5-themes-menda
extra/sddm-menda-theme
extra/vertex-maia-icon-theme
extra/xcursor-menda
extra/xfce4-weather-plugin-menda-circle-icons
extra/xfce-theme-greenbird
community/menda-themes
community/menda-themes-dark
community/cinnamon-theme-minty
community/evopop-gtk-theme
community/numix-manjaro-themes
community/manjarobox-evolution-themes
community/manjarobox-legacy-themes
community/mediterraneannight-theme
```

However, we should double check it.

**Comment by Ste74** [comment]
Sorry for noobie question .. example mediterraneannight is too old about 3 years , i never used xfce and mate so ok this theme is broken under gtk 3.20 but xfce and mate? where the support for gtk 3+ i think is not complete (?)

**Comment by Ste74** [comment]
numix theme in launchpad have 3.20 support but is a bzr version
http://bazaar.launchpad.net/~numix/numix/trunk/files

**Comment by Kirek** [comment]
https://github.com/shimmerproject/Numix

**Comment by Ste74** [comment]
Oh well :smile:

**Comment by philmmanjaro** [comment]
So we already started to drop gtk3 support from themes not getting support at the right time for it. Also a way to do it :smile:

**Comment by Ste74** [comment]
I always afraid to make mistakes :stuck_out_tongue_winking_eye:

**Comment by korrode** [comment]
Personally, i'd just delete all themes from our repos that are not currently GTK 3.20 compatible.

**Comment by philmmanjaro** [comment]
Most of them are already modified. Do we still have some themes which are now not working at all?

**Comment by philmmanjaro** [comment]
Do we have still something to do here?

**Comment by Ste74** [comment]
Is still open ?

**Comment by udeved** [comment]
No idea @Ste74 if everything is cleaned up.

**Comment by philmmanjaro** [comment]
Don't know. Maybe. However I didn't got any bad feedback from the community. Seems to be fine now.

**Comment by Ste74** [comment]
I have start to cleanup ( if in my possibility) and close old open issue ..
