### ISSUE TITLE
Do we still need the BROWSER var?

### ISSUE THREAD

**Issue by philmmanjaro** [manjaro/release-plan#44]
> Sent by email: 27.04.2016 at 23:20 - from Dax Gahr:
> I've recently been having issues with too many resources being used up for
> apparently no reason. I figured out that xdg-open is spawning a ton of
> processes of itself.
> 
> It looks like in /etc/profile, BROWSER is set to "xdg-open", which is
> what's causing the recursive call issue. I tested this by typing "xdg-open
> http://www.google.com/", and sure enough, a ton of "xdg-open" processes
> started appearing. I can fix this myself by setting BROWSER to something
> else, but I was wondering if this was set in /etc/profile intentionally??

**Comment by oberon2007** [comment]
At the moment we also install it to **/etc/environment** ...
People using WMs will certainly be happy if it can be dropped that ;)

**Comment by noobpurple** [comment]
I also found it in my ~/.bashrc, by the way. Commenting them out fixed the issue.

**Comment by oberon2007** [comment]
@noobpurple , which edition do you use? I assume that in your .bashrc the variable was not set to xdg-open but to a specific browser?

**Comment by noobpurple** [comment]
I use manjaro-net-15.12 with i3 installed. And, no, it was originally set to xdg-open in my .bashrc.

**Comment by oberon2007** [comment]
OK. Especially for WMs that is certainly not a good idea :stuck_out_tongue_winking_eye:

**Comment by philmmanjaro** [comment]
So we drop it then.

**Comment by philmmanjaro** [comment]
@oberon2007: well we have it also in [thus](https://github.com/manjaro/thus/blob/master/thus/installation/process.py#L1088) and in [calamares](https://github.com/calamares/calamares-manjaro/blob/master/src/modules/postcfg/main.py#L31). Cli-Installer might be also the case ...

**Comment by philmmanjaro** [comment]
Yep, cli has it [also](https://github.com/manjaro/manjaro-cli-installer/blob/master/lib/util-inst.sh#L341).

**Comment by oberon2007** [comment]
:bowtie:
