### ISSUE TITLE
manjaro welcome addition

### ISSUE THREAD

**Issue by Ste74** [manjaro/release-plan#45]
Hi guys i would like to propose the addition of a voice in Manjaro welcome (live only) for the chroot using Manjaro-chroot called example: troubleshooting.
This entry could open the console with 'manjaro-chroot --help' : this will print options for chrooting, or open the one you see fit (a voice of the guide explaining the chroot via manjaro-chroot)

**Comment by philmmanjaro** [comment]
I don't think a voice is needed here. Will confuse people. Or do you know a nice tech-girl willing to record some sessions?

**Comment by Ste74** [comment]
Is only a idea to easy find manjaro-chroot . More people not know what is chrooting . Ok is a bad example but (not use *ubuntu about 3 years ) in ubuntu livecd i have notice to easy found how to repair the boot .. I do not know what could be the best way to say "hey do not worry inside the livecd is present manjaro-chroot" .

**Comment by Ste74** [comment]
maybe i understand mow you mean literally voice :satisfied:... damn it my 'stenglish'

**Comment by philmmanjaro** [comment]
I think we can close this as **manjaro-hello** will replace **manjaro-welcome**.

**Comment by Ste74** [comment]
I agree :)
