### ISSUE TITLE
mhwd-next?

### ISSUE THREAD

**Issue by udeved** [manjaro/release-plan#46]
In a chat I had recently, we came up with the idea to experiment with mhwd that is based on alpm hooks.
Ie the MHWDCONFIG wouldn't be needed eventually.

Thoughts?

**Comment by udeved** [comment]
The working would be:

1. have a pure device and vendor id db
2. have all the repetitive setup stuff and functions, including the depends, controlled by hook(s)
3. resolve depends via pacman 

So far the idea.

**Comment by udeved** [comment]
https://github.com/manjaro/release-plan/issues/142

**Comment by udeved** [comment]
https://github.com/manjaro/release-plan/issues/127

**Comment by Tids** [comment]
#152

**Comment by Tids** [comment]
@udeved would the alpm idea mean that we need to create "ready to use" packages for every hardware mix? Because in this case I spot a big problem. Some users might find a package that wont fit to the hardware but just installs them via pacman and now this user is unable to boot.
