### ISSUE TITLE
Do some commands to target system during installation

### ISSUE THREAD

**Issue by LordTermor** [manjaro/release-plan#48]
I think it will be nice for users to do "pacman-mirrors -g" and "pacman -S manjaro-keyring archlinux-keyring" in target system if Internet connection is available during installation. It will help to avoid troubles with low-speed updates and keyrings.

**Comment by spsf64** [comment]
This would resolve some problems many users complain about "slow" updates.
This could be like ubuntu, were it sets up at least the country you are on, or maybe closest mirror.
