### ISSUE TITLE
publish openrc editions of xfce and kde

### ISSUE THREAD

**Issue by philmmanjaro** [manjaro/release-plan#5]
* openrc seems to be popular
* why not adopt our current systemd profiles and pulish them also as openrc editions

**Comment by udeved** [comment]
I would help with a kde edition, besides my little lxqt profile.
But first, cgmanager has to reliably work in my view.
Its in progress with bugreports and help from cgmanager guys.

**Comment by oberon2007** [comment]
time and date in msm still needs to be openrc-enabled! ;)

**Comment by oberon2007** [comment]
Oh, and: Not sure about Calamares, but in any case Thus is also not capable yet of setting the time under Openrc I'm afraid!

**Comment by philmmanjaro** [comment]
Well, that is why it is optional. However if some is still missing regarding **openrc** please open issues in the needed **bug trackers** of each application.

**Comment by philmmanjaro** [comment]
So, do we ship openrc editions with **15.09** or should we wait for **Capella** in December?

**Comment by oberon2007** [comment]
Sorry, what is Capella? What still concerns me is the lacking time&date setting capabilities of Calamares, Thus and mainly MSM... Some programs (pinta for example) won't even launch before the user figures out how to set the timezone correctly. In my Openrc spins I have included the app timeset and provide a dummy /etc/localtime file to avoid that. But it's not clean at all and you are still confronted with ineffective funcions in those central apps...

**Comment by philmmanjaro** [comment]
These are our code names for each release:

**Ascella** (0.8), then **Bellatrix** (15.09), then **Capella** (15.12), then **Daniella** (common name)/Dallata, then **Ellada** (old name for Greece), then **Fringilla**, then **Gabriella**/Gellivara, then **Hollandia**, then **Isabella**/Illyria, then **Joëlla**, then **Ka-Ata-Killa**/Kalliope, etc.

I move it now to **15.12**.

**Comment by oberon2007** [comment]
Oh! :D I had missed these ;)

**Comment by udeved** [comment]
I would do by the end of the week lxqt-minimal and kde-minimal as openrc edition.

**Comment by systemovich** [comment]
Good news! Can't wait!

**Comment by philmmanjaro** [comment]
Ok, this settles then. We might have some **openrc** community editions.
