### ISSUE TITLE
Grub and Splash Screen

### ISSUE THREAD

**Issue by KUPOinyourWINDOW** [manjaro/release-plan#50]
On my early 2011 Macbook Pro when I install Manjaro there are two things that really bug me that I believe should be optional.

1) The grub screen showing even with only 1 OS installed. I shouldn't have to manually press enter or wait to have my OS boot with just one OS. Xubuntu (for example) doesn't give me this irritation.

2) The splash screen (the black background with Manjaro and some circles that light up) glitches towards the end and looks insanely messy. I'd love to have a splash screen but this is an issue that never gets fixed.

Cheers for your time.

**Comment by Strit** [comment]
Well, I can answer the first problem. The is because you should have the option to boot another kernel if you wish. If grub wasn't there, you'd always bee booting the same kernel, so when that kernel does not suit you anymore, you have no way to change it.

Plus. a lot of troubleshooting can be done from grub.

If you don't like the wait time, I guess you can change the default timer to zero, to boot instantly.

**Comment by KUPOinyourWINDOW** [comment]
On Ubuntu for example, if I have only one OS and one Kernel it skips the grub screen and boots up straight away. If I then add another Kernel or OS, it then shows grub.

Would it not be better to do something like this?

**Comment by Ste74** [comment]
uhmm i have tested the solution proposed from ubuntu about the grub menu .. it seem work at the fresh installation if the target system is single os .. but after add other os and come back on the single os seem not re hide the grub menu ..
I found this open bug report
https://bugs.launchpad.net/ubuntu/+source/grub2/+bug/1273764
Are proposed a workaround , i have to test them

**Comment by Ste74** [comment]
For the first issue i think is possible close via this https://github.com/manjaro/packages-core/tree/master/grub-quiet.
The second i don't uderstand do you mean

**Comment by oberon2007** [comment]
@Ste74 he means the transition of **plymouth** to the graphical session. :wink: @KUPOinyourWINDOW [this](https://wiki.archlinux.org/index.php/plymouth#Smooth_transition) might help you, but I think it is also depending on your hardware and driver how well the transition works. Maybe also [changing the plymouth-theme](https://classicforum.manjaro.org/index.php?topic=30723.msg253351#msg253351) would be an option? Not sure if that would change much, though...

**Comment by Ste74** [comment]
Grub-quiet is in the repo if plymouth issue remain please open on our bugs trucker www.bugs.manjaro.org
