### ISSUE TITLE
Suspend issues

### ISSUE THREAD

**Issue by udeved** [manjaro/release-plan#51]
We should track down this mysterious suspend behaviour.
No wake up, fans running, hdd sleeps, hard reset with kernels-4.4+ after suspend.
Many reports on forums, unfortunately, many on the old one. But issue still pops up.

I don't have this issue on gentoo on same machine.

**Comment by spsf64** [comment]
I have the same problem with any xfce de (xubuntu, arch and manjaro), if I switch to mate de it works fine.
I solved it by creating a restore shortcut (alt+r) to "xrandr --auto", btw this could be default in manjaro as it appear to be a mainstream xfce bug.

**Comment by udeved** [comment]
Why you describe has unfortunately not much to do with the suspend issue.
You got xrandr problem, but we have a power management issue with certain kernel versions.

**Comment by spsf64** [comment]
@udeved it actually happens with several different machines, 2 laptops (sony and asus) and 2 desktops (asus and gygabyte motherboards), also happens with nvidia and intel display adapters; I still believe it is a xfce problem..
Does your gentoo works ok with xfce?

**Comment by udeved** [comment]
I don't use xfce, I am on plasma5, on all my linux systems.

Do your systems wakeup? 
Do they properly susspend?
What kernel version?

Please provide some details.
We need to get more info to perhaps fix it.

**Comment by spsf64** [comment]
It only happens with xfce, system always wakes up, however with black/blank screen, as I said, the command "xrandr --auto" will bring the screen up. It happens with all kernels tested from 4.4 up to the latest as of today.

**Comment by udeved** [comment]
Then this is not the suspend issue I am talking about.
Sounds to me, your issue is more related to a missing resume partition or something.

The issue I encounter comes with kernel44+, as it reads in description, and it seems hardware related. No issue on a laptop. Several other people reported this issue, that their systems do not properly suspend, with fans still running, but hdd sleeps and doesn't wakeup, regardless if systemd or openrc.

**Comment by spsf64** [comment]
Ok, I understand, sorry to continue on... Maybe this it is necessary to open another issue.
I only use suspend (no hibernation) because I don't use swap.
Just to clarify, all machines DO suspend properly, however they have this black screen problem after resume.

**Comment by udeved** [comment]
Yes please, open a separate issue for this.
Perhaps provide some log snippets, and detailed description.
I think it justifies definitely an issue, since you say, you encounter it on all your systems with any kernel.

**Comment by udeved** [comment]
https://forum.manjaro.org/t/desktop-became-grey-after-hard-reset/1881

**Comment by Lgmarini** [comment]
Some details on how the issue behaves in my case:

Suspend works perfectly fine. 
When the system wakes up, it is responsive for 1/2 second, then it freezes completely, forcing a hard reset. 

It used to happen only occasionally, while now seems to be constant (which, in a way, makes it reproducible and potentially better). I am currently on Manjaro 16.06 (Xfce 4.12). The problem persists with any kernel (including 4.6 and pre-4.4).

Please let me know what further details or logs I can post to help solve the issue. Thanks.

**Comment by digitalcraftsman** [comment]
I can confirm the issues described by @Lgmarini with the latest release (Manjaro 16.06, Xfce 4.12).

**Comment by philmmanjaro** [comment]
So in other words with **linux41** we don't have this issue? If you say it happend with **4.4-rc** releases also, then we have to **[bisect](https://raw.githubusercontent.com/philmmanjaro/linux41/master/git-bisect.txt)** the issue here. **linux42** seems also to be fine. It will [take a while](https://github.com/philmmanjaro/linux41/commits/master/PKGBUILD) to get a result.

What needs to be done?

* define the first kernel which broke it (most likely **4.4-rc1** or later)
* define a kernel which works (most likely **4.3** or **4.2**)
* having a little knowledge of **git** and building packages with **PKGBUILD** scripts
* the will recompiling the kernel (roughly 13x) until you find the issue (apprx.  22h or more, depending on the CPU power)

If needed, I can create a guidance video on how to **bisect** the Manjaro kernel with the help of **buildpkg**, **git** and a given **PKGBUILD**.

**Comment by philmmanjaro** [comment]
Some findings:

- [unable to suspend on xfs](http://www.linuxquestions.org/questions/slackware-14/unable-to-suspend-or-hibernate-with-a-4-4-0-kernel-4175563710/)
- [4.4-2: kernel locks up on suspend ](https://bugs.archlinux.org/task/47757)
- [Suspend problem with kernel 4.4](https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1570899)
- [BFQ v7r10 seems to interfere with suspend to ram](https://groups.google.com/forum/#!topic/bfq-iosched/9N1QL9E-KH4)

If it is the CPU scheduler then we might have to revert https://github.com/manjaro/packages-core/commit/c269567340c236d4d8ccd3788a2f0383e0af7714

**Comment by Lgmarini** [comment]
As I wrote above, in my experience the bug does not depend on the kernel, or at least I haven't found one that is free of this bug. It is still there in 4.2 (just tested) and if I remember correctly it started before that.

Note: my system does not have problems with suspending, but only with waking up from suspension.

**Comment by philmmanjaro** [comment]
Well, you have to define a kernel which works. If it is the CPU scheduler you can switch it and test away:

```
[phil@manjaro ~]$ cd /sys/block/sda/queue
[phil@manjaro queue]$ su
Password: 
[root@manjaro queue]# cat scheduler
noop deadline cfq [bfq] 
[root@manjaro queue]# echo cfq > scheduler
[root@manjaro queue]# cat scheduler
noop deadline [cfq] bfq 
```

**Comment by Lgmarini** [comment]
After doing that, it suspended and resumed successfully (tested both in 4.1 and 4.6). (Note, however, that the issue used to happen only occasionally, so I am cautious at declaring it solved).

I am not fully aware of what I am doing with these changes. Is there a significant difference between the three schedulers?
Could you please guide me in detail on how to edit my kernel line?

Thanks for your help!

**Comment by udeved** [comment]
@philmmanjaro 

Whatever this causes it, linux41 and linux42 work, independently of init system.
I initially thought its a ck issue, but same behaviour reported with systemd.

It looks to me, if this is kernel and hardware specific, and does not influence all hardware.
It started with linux44, and I have not tested 4.6, but 4.5 also had this issue.

**Comment by philmmanjaro** [comment]
@udeved: it is either a kernel config issue, a regression in **v4.4** and up, or simply the I/O scheduler. If you face the issue and you can repeat it, a **git-bisect** is the only way to find the regression. However we might have to check if **v4.3** is fine with this issue. Either we ask in the forum if somebody has a saved **linux43** in his cache or you have to compile it to verify (if you want and have time). Suspend issues are complex and also depend current settings and drivers. So hard to tell.

**Comment by udeved** [comment]
Right, I found out when I compiled 4.4 with audit enabled.
I was originally gonna put it in the repos.

The ugly thing is, we did 16.03 with 4.4 kernel, so we should either find a fix or use different kernel for 16.06.

**Comment by philmmanjaro** [comment]
We won't use a different kernel for **16.06**. It supports new Intel hardware, which the old kernel doesn't do. Suspend issues are not so important for me in the whole. User can still downgrade the kernel if needed but it won't prevent them to install Manjaro. To find the fix somebody who has the fix has to **git-bisect** it. That is the only way to do it.

**Comment by udeved** [comment]
https://forum.manjaro.org/t/manjaro-xfce-not-going-to-sleep/2159

**Comment by Lgmarini** [comment]
After a week without problems, my system froze again twice (without any changes in kernel, CPU scheduler or other settings), so the problem persists. 
(I've noticed that there seem to be some "chain" effect: when the system is rebooted with a hard reset, it is more likely that it won't suspend correctly and freezes will occur frequently; instead, if it suspends correctly, it is likely that it will keep doing it.)

**Comment by udeved** [comment]
Can you revert the scheduler you posted earlier in one of 4.4+ kernels? At best linux44 @philmmanjaro

**Comment by philmmanjaro** [comment]
You mean to revert it back to **v7r8** release? https://github.com/manjaro/packages-core/commit/c269567340c236d4d8ccd3788a2f0383e0af7714 Why do you think that might help?

**Comment by udeved** [comment]
I guess it helps, since linux44 is our lts kernel atm, we do iso with it, and people still report suspend issues. Initial report was in May, I use still linux41, since all new kernel have this problem.

**Comment by udeved** [comment]
_bfq=v7r8 works as in linux41

_bfq=v7r11 doesn't work in linux44

**Comment by philmmanjaro** [comment]
We can give it a try with **v4.4.21** and see ...

**Comment by philmmanjaro** [comment]
@udeved: did you test a different scheduler as I had requested? If it is really the scheduler, we can change that.

**Comment by udeved** [comment]
Once the thing is in unstable, I'll test and report, but I am almost certain it will work with older bfq

**Comment by udeved** [comment]
Standard scheduler works, I tested and I also have a gentoo 4.4 kernel that works.

**Comment by philmmanjaro** [comment]
Ok, lets give **v7r8** another try ...

**Comment by udeved** [comment]
Sounds the only reasonable source that could cause it, and it must be something we add in manjaro.

**Comment by philmmanjaro** [comment]
Does **v4.4.21** works now as expected?

**Comment by udeved** [comment]
Appears to be suspending properly for me @philmmanjaro  :+1:

**Comment by philmmanjaro** [comment]
Great. Thx for confirming it. So we will keep it at that version for now.

**Comment by markjes** [comment]
I try it on two different laptops, Thinkpad T410 and T520 on kernel Kernel: 4.7.4-1.1and Kernel: 4.4.21-1, Desktop: Xfce 4.12.3 and the suspend still not working.

**Comment by ralph1313** [comment]
same here on Thinkpand T410 on kernel Kernel: 4.5.7-1, Desktop: Xfce 4.12.3

**Comment by lanjiann** [comment]
Same here. I use virtualbox and **manjaro 16.10 deepin** desktop version.
Both the live dvd version and the installed version can't wake up after being suspended. I tried all the kernels from 3.18.43-2 to 4.8.9-1. No one works well with suspension.
