### ISSUE TITLE
Will not boot after Kernel Update

### ISSUE THREAD

**Issue by joeffel** [manjaro/release-plan#52]
Installed 4.6 kernel using

`sudo mhwd-kernel -i rmc linux46`

Rebooted, stuck on blank screen.

**Comment by joeffel** [comment]
Reinstalled, installed 4.5 kernel using

`sudo mhwd-kernel -i rmc linux45`

Rebooted, stuck on blank screen.

**Comment by philmmanjaro** [comment]
Which kernel boots on your machine? Don't remove the running kernel while testing a new one. Also more information is needed to find a solution for your issue.

```
[phil@manjaro manjaro.github.io]$ inxi -SC
System:    Host: manjaro Kernel: 4.4.11-1-MANJARO x86_64 (64 bit)
           Desktop: Xfce 4.12.3 Distro: Manjaro Linux
CPU:       Quad core AMD Phenom 9650 (-MCP-) cache: 2048 KB 
           clock speeds: max: 2300 MHz 1: 1150 MHz 2: 1150 MHz 3: 1150 MHz
           4: 1150 MHz
```

**Comment by joeffel** [comment]
The default kernel works, 4.4, I think? What information do you need?

**Comment by philmmanjaro** [comment]
The output of `inxi -SC` might help for starters. Also if you have a laptop or a PC. Do you get any error message? If you in **grub** press `ctrl+e` before you select the kernel and remove `quiet splash` from the kernel line. With `ctrl+x` you start your PC to see the print outs. If needed make a screenshot from the error with your mobile phone or such.

**Comment by joeffel** [comment]
Oh maybe I should tell you that I tested it in a VM. I always test 
distros in a VM before I actually use them.

**Comment by jonathonf** [comment]
Can I just point out this is not an issue with the "release plan" ?

**Comment by philmmanjaro** [comment]
This might be related to this: https://github.com/manjaro/release-plan/issues/67

**Comment by joeffel** [comment]
I tested the stable release of 16.06, it works even with rmc flag enabled.
Great job!

**Comment by philmmanjaro** [comment]
So I close this now.
