### ISSUE TITLE
No sound in speakers connected through HDMI

### ISSUE THREAD

**Issue by oBraien** [manjaro/release-plan#55]
I have a 2.0 speakers connected through HDMI (HDMI-out-HDMI-in) and headphones conneted through line-in. So i can't get a sound work using hdmi scheme. I'm open PulseAudio Adjusting Volume and see that sound bar related to my browser showing that sound is playing and Integrated auio Digital Stereo (HDMI) is selected. At the configuration tab i see in combobox that nothing is connected to hdmi, every option is unplugged, except "Digital Stereo HDMI 3 out".  In Alsamixer i chose HDA Intel HDMI and there's only three options that related to SPDIF. How to make it work?

**Comment by philmmanjaro** [comment]
open **pavucontrol** and turn off all unneeded devices in **configurations**

![pavucontrol](https://cloud.githubusercontent.com/assets/5050022/15407277/56ee6ab8-1e0a-11e6-8f57-bd8d671b7b96.png)

**Comment by oBraien** [comment]
Thnx, but it doesn't helped.

**Comment by philmmanjaro** [comment]
Then check if some of these [trouble shoots](https://wiki.archlinux.org/index.php/PulseAudio/Troubleshooting) will help ...

**Comment by korrode** [comment]
A Github issue against our release plan is not the appropriate place for general support queries, especially when they're non-universal (HDMI audio works fine for most users, this issue is specific to your configuration).

Please sign up on our forums and post there.

https://forum.manjaro.org/
