### ISSUE TITLE
Wiki link

### ISSUE THREAD

**Issue by oberon2007** [manjaro/release-plan#56]
Is there hope that we will have a properly working Wiki with the 16.06 release? Right now you still have to add a security exception in a private window because of the expired certificate.
On the forum there were suggestions about moving the wiki from https to http - would that be a possibility?

**Comment by philmmanjaro** [comment]
I'm still in discussion with Roland Singer to get access to this server. So without that I can't do much about it. Hope is still there.

**Comment by oberon2007** [comment]
Help will be much appreciated, @m4ng0squ4sh! A 16.06 release with a broken Wiki-link on the Welcome Screen would be really bad publicity, I'm afraid! ...

**Comment by philmmanjaro** [comment]
Maybe we should link to arch-wiki temporally ...

**Comment by oberon2007** [comment]
Not a bad idea. Just, then it needs to be changed in **manjaro-browser-settings**, too!

**Comment by Ste74** [comment]
Hi , @philmmanjaro , @oberon2007 ..  i think temporary solution only .. people need answers : 
https://forum.manjaro.org/t/missing-wiki-workaround-suggestion/3156

**Comment by philmmanjaro** [comment]
Talking to **Roland Singer** is currently really hard. Only he has the access to @manjaro.org domain and the other servers. I only hold the forum server and repository server.

**Comment by oberon2007** [comment]
So we leave it the way it is for now? The browser-defaults, too?

**Comment by philmmanjaro** [comment]
We leave it as it is for now.

**Comment by alexara** [comment]
> Talking to Roland Singer is currently really hard. Only he has the access to @manjaro.org domain and the other servers. I only hold the forum server and repository server.

Maby you should move to `Let's Encrypt` and use an auto renewal script. You seem to have these problems quiet often. ;-)

**Comment by oberon2007** [comment]
solved :)
