### ISSUE TITLE
Depreciate Thus installer

### ISSUE THREAD

**Issue by philmmanjaro** [manjaro/release-plan#62]
Since **Calamares** should be just fine for Manjaro by then we should depreciate **thus**

**Comment by giocap73** [comment]
use only calamares.

**Comment by Strit** [comment]
When Calamares has full encryption support, I think we can do this. Not before.

**Comment by philmmanjaro** [comment]
What is this all about this encryption? With **calamares-dev** we already support full encryption including swap. This you can test with [Ellada builds](https://sourceforge.net/projects/manjarotest/files/16.08-dev/).

**Comment by Strit** [comment]
Will that version be ready and stable for Ellada iso's?

**Comment by udeved** [comment]
@philmmanjaro 

Should I make a cal branch. removing thus and cli install?
cal-dev-2.3.9x looks promising.
buildiso would need many little changes to support new features.

**Comment by ringo32** [comment]
yeah you can do like antergos , antergos-minimal , openbox+installer and terminal 🌴
