### ISSUE TITLE
Build Release images (v16.06.1)

### ISSUE THREAD

**Issue by philmmanjaro** [manjaro/release-plan#65]
- [x] xfce i686
- [x] xfce x86_64
- [x] kde i686
- [x] kde x86_64
- [x] net i686
- [x] net x86_64

**Comment by oberon2007** [comment]
Sorry, I was not able to follow everything these last three days ... Why do we need new install media now? Does that mean I have to rebuild Deepin, i3 and Cinnamon, too?

**Comment by philmmanjaro** [comment]
I'll write down all the changes and fixes I added to this release. Most likely it is cos of **AMDGPU** and the complains from some users not able to install the current release. Also I added some fixes to **pamac** and other packages.
