### ISSUE TITLE
git-bisect systemd regression with plymouth

### ISSUE THREAD

**Issue by philmmanjaro** [manjaro/release-plan#67]
Seems we have to git-bisect the issue we have with **plymouth** and **v230** ...

**Comment by philmmanjaro** [comment]
Before we bisecting anything, we may try first some sets of packages we have now in our branches:

|systemd|kernel|plymouth|works?|
|---|---|---|---|
|v230|v4.6.2|v0.8.8|hangs either with sddm or lightdm|
|v230|v4.6.2|v0.9.2.r44.g375a65f|hangs either with sddm or lightdm|
|v229|v4.4.13|v0.8.8|works for sddm and lightdm|
|v230|v4.4.13|v0.8.8|works for sddm and lightdm|

**Comment by oberon2007** [comment]
Is this solved meanwhile? Yesterday I built a Deepin ISO against testing branch (plymouth 1:0.8.8-2, systemd 230-5, lightdm 1:1.18.2-2 and kernel 4.6.4. No problems there.

**Comment by oberon2007** [comment]
Oh, I have to take that back! It had only worked because I had interrupted **plymouth**.
So, v233 / v46.4 / 1:1.18.2-2 does hang with lightdm!

**Comment by oberon2007** [comment]
Looks like the regression was probably introduced with the bump to linux 4.6.2 on June 8.
I'll build the latest commit of [4.6.1](https://github.com/manjaro/packages-core/commit/0e8314eb790c0803cddb3e1f289ab8deca1f8488#diff-948fbb115737866555083302e15868b2) now to verify.

**Comment by oberon2007** [comment]
It's a bit more mysterious: While in vbox the above mentioned package combination has an issue, the same setup works fine on real hardware! Maybe drivers are involved here aswell!?

**Comment by oberon2007** [comment]
Output of journalctl with the above mentioned deepin-ISO (linux4.6.4)
![](http://imgur.com/2hFUlHol.png)

**Comment by oberon2007** [comment]
I get the same problem with **linux4.6.1-2**

**Comment by philmmanjaro** [comment]
Yes, I didn't test **linux45**, which we might should do to narrow down which combination is affected. **linux46** it is for sure.

**Comment by oberon2007** [comment]
I can do that now in my vbox install... In any case it's weird that there's no issue on hardware ...

**Comment by philmmanjaro** [comment]
I also assume it is a VirtualBox only issue. Most people use VirtualBox and if Manjaro fails there we have the bad user experience. However we already have another issue with VirtualBox and Mouse rendering ... Maybe we should also test VMware or the opensource KVM.

**Comment by oberon2007** [comment]
Ok: Same issue with 4.5, no issue with 4.4

**Comment by philmmanjaro** [comment]
Ok, so some got introduced with 4.5 series then which is not working with VirtualBox. Maybe we should also test VMWare. I think @Kirek is using VMWare. The player is free. I run Manjaro on my work PC with that. Maybe I update the kernel on that machine one day for testing ;)

**Comment by Ste74** [comment]
But you want update the kernel in next 16.09 ? I.e. next iso install 4.6 ?

Il 20/lug/2016 21:27, "Philip Müller" <notifications@github.com> ha scritto:

**Comment by Ste74** [comment]
Is already an lts?

Il 20/lug/2016 21:32, "Stefano Capitani" <capitani74@gmail.com> ha scritto:

But you want update the kernel in next 16.09 ? I.e. next iso install 4.6 ?

Il 20/lug/2016 21:27, "Philip Müller" <notifications@github.com> ha scritto:

**Comment by philmmanjaro** [comment]
The LTS kernel is always the kernel stable in **January** ...

**Comment by Ste74** [comment]
I see at kernel.org now .. So next iso will use the 4.4 series or i wrong ?

**Comment by oberon2007** [comment]
I'll try the first 4.5 release https://github.com/manjaro/packages-core/commit/bc63c4a3a246a50d351a097645ba8e2c95943090#diff-205e8546f3ba94388f72ee35e7036359 next.

**Comment by philmmanjaro** [comment]
Always try RC1 first. That is the kernel with the most changes.

**Comment by oberon2007** [comment]
OK

**Comment by oberon2007** [comment]
https://github.com/manjaro/packages-core/commit/de5892116fd92be899468f421d6668414eeb5f4b#diff-a7fd83a51ce3c63c11fd5ad25e90f03e then

**Comment by oberon2007** [comment]
**linux45-4.5rc1** was still ok. Next I'll try https://github.com/manjaro/packages-core/commit/a946d761e90ce99a5a7448769e945482fb695a56 where the config and BFQ were updated.

**Comment by oberon2007** [comment]
The issue is present with **4.5-2**. I'll now do one commit before that to confirm.

**Comment by oberon2007** [comment]
I can comfirm that https://github.com/manjaro/packages-core/commit/a946d761e90ce99a5a7448769e945482fb695a56 is the first bad commit. Now the question is if the config or the BFQ update is responsible for the regression...

**Comment by oberon2007** [comment]
I've narrowed this further down by building a version of linux45 including the BFQ update but leaving the kernel config at the state of **4.5-1** with the single exception of ``CONFIG_BFQ_GROUP_IOSCHED=y`` which is needed with the 4.4.0 patches. This one does not have the plymouth issue in vbox.
So that means that something in the new config of **4.5-2** must have made the difference.

**Comment by Strit** [comment]
@oberon2007 Time to do a diff then. :)

**Comment by oberon2007** [comment]
The diff we already have! :wink: https://github.com/manjaro/packages-core/commit/a946d761e90ce99a5a7448769e945482fb695a56#diff-da2be459951c0eb75741c5db7823cce3

**Comment by oberon2007** [comment]
[**virtualbox-5.1.2**](https://www.virtualbox.org/wiki/Downloads) is due. We shall see what that changes...

**Comment by oberon2007** [comment]
So the virtualbox update didn't make any difference. I have made some kernel test-builds now with different config and have pretty much narrowed it down to very few possibilities. I should be able to determine in a few hours which setting is the culprit :grinning:

**Comment by philmmanjaro** [comment]
Ok, keep me posted on the progress.

**Comment by oberon2007** [comment]
I found it. The issue is caused by setting ``CONFIG_IO_STRICT_DEVMEM=y``
All the other recently adjusted linux45 config works as long as IO_STRICT_DEVMEM is not set.

**Comment by oberon2007** [comment]
> If this option is disabled, you allow userspace (root) access to all io-memory regardless of whether a driver is actively using that range. Accidental access to this is obviously disastrous, but specific access can be used by people debugging kernel drivers.

> If this option is switched on, the /dev/mem file only allows userspace access to *idle* io-memory ranges (see /proc/iomem) This may break traditional users of /dev/mem (dosemu, legacy X, etc...) if the driver using a given range cannot be disabled.
Hm. I guess in fact the issue is somewhere else, but maybe we should still switch it off for now?

**Comment by oberon2007** [comment]
Building a linx46 now with IO_STRICT_DEVMEM turned off for verification.

**Comment by oberon2007** [comment]
Working fine.

**Comment by oberon2007** [comment]
I have **4.6.4-2** ready here for both archs. Let me know if you want me to push those. Extramodules will need to be rebuilt, too. **4.5.7-2** with the changed config would still have to be built.

**Comment by philmmanjaro** [comment]
Hmm, seems this was already detected by some of our users: https://groups.google.com/forum/#!topic/de.comp.os.unix.linux.misc/MVcjCu2ei_8

**Comment by philmmanjaro** [comment]
Reading on for getting what will happen if we disable IO:

> If this option is switched on, and IO_STRICT_DEVMEM=n, the /dev/mem file only allows userspace access to PCI space and the BIOS code and data regions.  This is sufficient for dosemu and X and all common users of /dev/mem.

**Comment by philmmanjaro** [comment]
You can just add `iomem=relaxed` as a kernel parameter in grub. The problem is that X.org moved to rootless in the version pushed out, which breaks the Vbox additions.

**Comment by philmmanjaro** [comment]
@oberon2007: please also test those commits so we can confirm that solution and we don't need to change the kernel configs just for VirtualBox.

**Comment by philmmanjaro** [comment]
Seems to work, at least for me ...

![virtualbox](https://cloud.githubusercontent.com/assets/5050022/17118199/e8e97b08-52bf-11e6-9214-51f2996d0955.png)

**Comment by oberon2007** [comment]
GRUB kernel parameter works for me also. Looking good! :)

**Comment by oberon2007** [comment]
On my vbox install of Deepin however the kernel parameter in Grub is now causing issues when booting with a pre45 kernel. Lightdm-login throws me back to the greeter once and I con only login the second time ... With iomem defined like that via manjaro-tools and Grub that will also mean that everyone will have that setting in the final installs, right? Or am I missing something there? Maybe also not ideal.
Maybe we should still consider to use the kernel config in linux45 and 46 until a better solution comes up?

**Comment by kouros17** [comment]
The grub kernel parameter works also for me for guest 4.6, but I get "**floppy0 no floppy controllers found**" with guest 4.7 and doesn't boot. I tried to add floppy in blacklist of /etc/modprobe.d, without success

**Comment by Ste74** [comment]
But Next ISO ship drop 4.4 lts kernel? I also confused... 
Il 26/lug/2016 10:54, Bernhard Landauer <notifications@github.com> ha scritto:On my vbox install of Deepin however the kernel parameter in Grub is now causing issues when booting with a pre45 kernel. Lightdm-login throws me back to the greeter once and I con only login the second time ... With iomem defined like that via manjaro-tools and Grub that will also mean that everyone will have that setting in the final installs, right? Or am I missing something there? Maybe also not ideal.
Maybe we should still consider to use the kernel config in linux45 and 46 until a better solution comes up?

**Comment by Strit** [comment]
@Ste74 
No, I think 16.08/09 will still run Kernel 4.4, since it's an LTS, and no newer LTS will be released before those ISO's are made.

**Comment by oberon2007** [comment]
It's maybe not imperative that a release always uses an LTS kernel, since it's so easy for users to change it to whatever they need. 4.6 seems quite stable and reliable meanwhile, so I guess it is definitely an option to use it for 16.08. I gather from Phil's testbuilds that this is the plan...?

**Comment by oberon2007** [comment]
Just built a Deepin ISO against your **vbox-plymouth-issue** branch with **linux44**. This results in autologin not working due to the above mentioned double-login issue. It's possible though that this is a **lightdm-deepin-greeter** problem only and would not be an issue with the regular **lightdm-gtk-greeter** ...

**Comment by oberon2007** [comment]
Will try again later with i3 which uses the classic greeter.

**Comment by Ste74** [comment]
Tonight try also gnome or budgie with Lightdm,unstable branch and 4.4 series and 4.6 series....
Il 26/lug/2016 13:06, Bernhard Landauer <notifications@github.com> ha scritto:Will try again later with i3 which uses the classic greeter.

**Comment by oberon2007** [comment]
i3 with **plymouth**, **lightdm-gtk-greeter** and **linux44** works fine with your ``iomem=relaxed`` commits. So seems to be a deepin specific problem that it doesn't like that kernel parameter.

**Comment by philmmanjaro** [comment]
Ok, the issue is this:

* `iomem=relaxed` is only needed for VirtualBox when using kernels higher as **4.4** and iomem security set
* using `iomem=relaxed` will be set also to the installed system. On **VirtualBox** still needed
* changing the **kernel config** will force all users not even having the option to use the higher security

So we have a small dilemma here. Since you have created a version of the **linux46** kernel without the **io_strict** settings, which leads then to this:

> If STRICT_DEVMEM option is switched on, and IO_STRICT_DEVMEM=n, the /dev/mem file only allows userspace access to PCI space and the BIOS code and data regions. This is sufficient for dosemu and X and all common users of /dev/mem.

We have an option to test **Deepin** with it. On real hardware it makes no different for **plymouth**, however we have this for **VirtualBox** with the given combination. Let me check why upstream suggests to set it strict by default, starting with **v4.5** series. You may find a lot of issues in combination with **VirtualBox** if you search for it. That is why I kept **linux44** for now on the install medias. However, the plan is to higher the kernel version somehow ...

**Comment by philmmanjaro** [comment]
Did we checked already with **xdriver=vesa** option on an unpatched ISO to see if it is only with the **VirtualBox** drivers?

**Comment by oberon2007** [comment]
Will be interesting to see also if that will effect the current [mouse-cursor issue](https://github.com/manjaro/packages-community/issues/205) ...

**Comment by philmmanjaro** [comment]
@oberon2007: does this also affect **Deepin** if you use **linux45** and higher and the kernel parameter on? We can also add a function only to add this parameter on kernels higher than **linux44** ...

**Comment by philmmanjaro** [comment]
http://linux-kernel.2935.n7.nabble.com/Boot-problem-on-PPC-with-4-4-git-Bisected-to-commit-21266be-td1284760.html

**Comment by oberon2007** [comment]
Hanging **plymouth** aswell as the [faulty-cursor rendering](https://github.com/manjaro/packages-community/issues/205) indeed appear to be both related to vbox-driver!
I'm running an unpatched Deepin now with **linux46** and **video-vesa** and the session launches normally and with a proper cursor.
However I get a different cursor issue now, where a part of the screen cannot be reached because the pointer jumps to a position further to the edge of the guest-content ...

**Comment by philmmanjaro** [comment]
So this issue is still ongoing. In regard of **cursor problem** I found a patch for it. Additionally some X11 patches are also in queue on upstream.

**Comment by oberon2007** [comment]
Do you think it would make sense to open an issue at Oracle also for the IO_STRICT_DEVMEM story - isn't this **vbox-video** realted aswell?

**Comment by oberon2007** [comment]
Or is that what might be fixed by those X11 patches?

**Comment by philmmanjaro** [comment]
It is related to the same issue we face with VirtualBox. It might help to mention it also for Oracle. I don't know, if these X11 patches do anything about it ...

**Comment by philmmanjaro** [comment]
Seems the issue didn't changed so far. Really strange what is happening with **vbox** here ...

**Comment by oberon2007** [comment]
this problem seems to have disappeared. I just tried with linux48 on a Cinnamon ISO with plymouth and had no issue.

**Comment by philmmanjaro** [comment]
Seems to work now with **linux49** and latest **VirtualBox**
