### ISSUE TITLE
Add snap packages support natively

### ISSUE THREAD

**Issue by philmmanjaro** [manjaro/release-plan#68]
![g5095](https://cloud.githubusercontent.com/assets/5050022/16069497/44f693ce-32cf-11e6-835f-9211ae34894d.png)

Snaps work on any distribution or device. Snaps are faster to install, easier to create, safer to run, and they update automatically and transactionally so your app is always fresh and never broken. Read here on [how to package](http://snapcraft.io/create/) with snap.

**Comment by Strit** [comment]
I can see the benefit of snap packages for apps that are not in the repo, but isn't the "store" ubuntu only?

**Comment by udeved** [comment]
Won't work on non systemd afaik.

**Comment by udeved** [comment]
@Strit 

http://news.tecmint.com/ubuntu-snaps-package-manager-to-replace-others-on-debian-fedora-centos-rhel-and-archlinx/

> Basically, the initial packaging can be somewhat larger than usual as developers will have to include all the libraries (that an application depends on to run) in the Snap package itself.
> 
> Secondly, the apps can only be updated via a single channel which is the Ubuntu Store. While this is mostly an advantage, (as the store becomes a centralized point for Snap packages) it is mostly in the favor of Canonical.

Urgs, indeed, its ubuntu trying to sell a new format as de facto standard.

**Comment by budimanjojo** [comment]
So this is the new alternative to AUR and community repository now?

**Comment by Strit** [comment]
@udeved 
Yeah, I thought so. Altough it does run on Arch/Manjaro, it still relies on a 3rd party company for the snap repo.

**Comment by udeved** [comment]
It looks to me as if the PM is finally tied to systemd through the backdoor.

**Comment by Ste74** [comment]
Snap standard de facto ? How about Flatpak and AppImage ? Flatpak is cross platform and cross DE .. snap only ubuntu-oriented ?

**Comment by Chrysostomus** [comment]
Flatpak seems superior technology from the cursory glance I took. This one has canonical behind it though... Either way, cool that if we can get cross distro packages.

**Comment by philmmanjaro** [comment]
It is still in early stages. However it seems to have also **gentoo** support, so not only tied to **systemd**. If you check the lastest **libreoffice snap** you may wonder why **flatpak** is even smaller. We will see.

**Comment by udeved** [comment]
@philmmanjaro 

The gentoo ebuild you posted is a pure systemd build.

**Comment by excalibur1234** [comment]
in the long term, i am in favor of integrating snap packages.

when we integrate snap packages, there are 3 package sources: the manjaro repositories, the AUR, and snap packages. then, pamac, octopi, and CLI tools such as pacli (and yaourt?) should integrate snap support...

when flatpack becomes available, there are 4 package sources...

**Comment by Strit** [comment]
@excalibur1234 AppImage is already available, and does pretty much the same thing. Manjaro just does not have support for it yet, by default.

**Comment by philmmanjaro** [comment]
@udeved: I didn't checked the **Gentoo** ebuild yet, but it make sense as **Ubuntu** is **systemd**-focused. We will see what the community thinks. As of now only two packages are needed to have **snap** supported. If it doesn't work for **OpenRC**, then it is ok. If we should add further support to **Octopi** and **Pamac** we will see. As of now I integrated the bare basics.

**Comment by alexara** [comment]
I am personally against integrating snappy since AFAIK:

* it's a by Canonical controlled closed source app store
* devs need to sign a CLA to contribute to Snappy (sic!)
* Packages of Arch are found in AUR, those of Fedora in the external repos. Copr, Gentoo let's you build the packages directly on GitHub: not really converging
* snappy introduces lot's of duplicates of libraries
* package maintainer are no longer needed
* devs may push more unfree software which was filtered by package maintainer before

I would suggest: Wait a little while until the aggressive Canonical marketing stops and the hype is over. IMHO there's no reason to adopt it.

@udeved 

Fedora does not support Snappy:
>
There's an article on Ars as well. The "working with Fedora developers" claim is probably a misunderstanding on Softpedia's part; it's not true, and I doubt Canonical would have said that. What's going on is that Canonical beat us to market in development... and now their marketing folks have beat us in marketing, too. **We of course have zero plans to adopt Snappy in Fedora, and in fact multiple Fedora developers are working on a competing solution, Flatpak** [1] (formerly xdg-app), which is also being adopted by GNOME and Endless. Until today, Snappy was viewed as Ubuntu-specific, which is why there was so little interest in it.

Source: https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/thread/NO7RMLYNIAWJTDNRDCDUWBPF6I4YOH3Z/?sort=date

**Comment by jonathonf** [comment]
Given that the only store available is Canonical's (and unless they release the source it's the only one that will ever be available) I don't think it's worth the effort to support this.

---

AppImage is slightly different as that is a "fat" bundle of the application with all required libraries. Snappy and FlatPak (should) add containerisation as a way of improving compartmentalisation (and so security).

**Comment by LordTermor** [comment]
IMHO this should be an option during installation. Smth like that: "Enable Snapd? Snapd is a tool provided by Canonical in order to easy installation of software by various distributors. To install snap packages you should have an Ubuntu One account.  More info available at http://snapcraft.io"

**Comment by jonathonf** [comment]
We can't have every possible piece of software available as an option during installation.

If it's available in the repos there's no need to have a switch in the installer.

**Comment by LordTermor** [comment]
The difference with other packages is that Canincal wants to make de facto package manager for every distro. But user should know pros, cons, how to use and  what is it at least. And also have an option for  enabling/disabling this. It's imho of course. I just saw people that really aware of becaming snap the standard pm for every linux system cause of security questons and all-dependencies-in-one-squashfs architecture(and size of this squashfs)

P.S. This would be a good start for creating manjaro's own "software center" with appstream, aur and snap support =)

**Comment by philmmanjaro** [comment]
You can install **flatpak** with `sudo pacman -S flatpak`. **snap** is now also possible with `sudo pacman -S snapd` from **testing** and **unstable** branches ...

**Comment by jonathonf** [comment]
> Canincal wants to make de facto package manager for every distro

I'm sure they do. Given they're the only ones with the upstream Snap server they want to control the software distribution channel. No other distro is on board with this. Canonical can do what they want with Ubuntu, but pushing the idea that every other distro is on board is blatantly wrong.

Red Hat is putting effort into Flatpak and that is entirely open-source. It is, however, rather GNOME-centric, and still a good deal of development effort away from anything like being ready for serious use.

> This would be a good start for creating manjaro's own "software center"

For obvious reasons this isn't going to happen.

**Comment by LordTermor** [comment]
> snap is now also possible with sudo pacman -S snapd from testing and unstable branches ...

I've already installed snap in stable from aur(just for testing). I thought that the subject of topic is about installing snapd by default. Maybe now my posts would be clearer to understand. Sorry, I just mistook everything. 

Snapd in repos is definetly good(so as flatpak too).

**Comment by philmmanjaro** [comment]
Seems same as **flatpak** Archlinux decided to also adopt **snaps**. So no need from our end to invest some resources into it.
