### ISSUE TITLE
Manage vertex maia theme into browser

### ISSUE THREAD

**Issue by Ste74** [manjaro/release-plan#70]
Change or split pkg for firefox and palemoon
https://github.com/manjaro/packages-community/issues/193

**Comment by oberon2007** [comment]
It's a misunderstanding that the theme would install anything in the user home. Nothing has be changed there. We just use a symlink in some profile settings packages. We discussed that we want to use it for a uniform look with the gtk-theme.
Which package do you want to split and why?

**Comment by Ste74** [comment]
I know and for me is not a problem but if you see the link at our forum the
symlink have the same permission of the original folder so if i want
disable that i have 2 option: rename the symlink (normal user) or delete
(sudo user). So for newby user is difficult to understand that. My idea is
change permission of the chrome folder (770 ?) or do the chrome folder with
pkg so the user can be remove via pacman. I hope explain better.  :)
Il 19/giu/2016 01:31, "Bernhard Landauer" <notifications@github.com> ha
scritto:

**Comment by oberon2007** [comment]
Have a look at my comment there. permissions are correct and the normal user can of course rm the symlink. They were using a wrong command, trying to rm the content of the target folder! ;)

**Comment by Ste74** [comment]
Ah ah i have lost the * in the command and via smartphone don`t have see
your comment.... :p
Close this ;)
Il 19/giu/2016 11:13, "Bernhard Landauer" <notifications@github.com> ha
scritto:
