### ISSUE TITLE
Decide if we want to release 'Ellada' in September

### ISSUE THREAD

**Issue by philmmanjaro** [manjaro/release-plan#72]
Some say August is to fast for a new release. Maybe we should pospone to September after all to have a three month development cylce.

**Comment by udeved** [comment]
We could also do monthly, so the problem of community versions disappears.

**Comment by ringo32** [comment]
depend, if become has 15.12 it had 6 month cycle to 16.06 so keep on eye on vacation planning as well better month earlier if vacation whatever comes in,

**Comment by Strit** [comment]
August is actually more a vacation month than September is. At least here in Denmark. 

Doing monthly ISO's will create a lot of work for me though, especially if all the community editions will follow this release cycle. I feel 3 months is about right.

**Comment by udeved** [comment]
I was only proposing it for official editions, so we would not have community editions with newer date any longer. Official was always matching. ;) @Strit

**Comment by Strit** [comment]
Ah okay. I could do 12 torrents each month, if it was needed. :)

**Comment by udeved** [comment]
We may had to expand codename to Starwars whatever though with monthly. :)

**Comment by udeved** [comment]
Gets me the idea, why not codename the CAL instead of OS?

**Comment by ringo32** [comment]
3 months is fine, depend some issues occured... but if on schedule in thirth month a vacation is planned, if possible month earlyier.. september is stil ok. but avoid like the 15.12 to 16.06

**Comment by jonathonf** [comment]
Six months is fine. We should just do point releases in between as necessary.

**Comment by udeved** [comment]
Sound kind of what I proposed for 3 month cycle.

eg 16.06 june
16.06.1 july
16.06.2 august

**Comment by jonathonf** [comment]
What is the purpose of a new Codename release? What is going to be different between 16.06, 16.09, and 16.12?

16.06 made sense as there were a number of changes over 15.12 (e.g. kernel 4.1 to 4.4). What would change with Ellada?

**Comment by ringo32** [comment]
useless for every iso release a new code name... code name your development level i guess.. 6 month release is not good, if you feedback 15.12 to 16.06 lot simple issues occur also not good.

**Comment by udeved** [comment]
Right, I would do the core system codenameless, and assign codename to manjaro specific apps not tied to lsb-release. We just assign it, and eg grub would show like arch something manjaro(rolling)

**Comment by Strit** [comment]
Doing it the way Arch does it, is actually great. Just release ISO's with a date, and do them more frequently as snapshots of the current state of Manjaro. Mostly it will only be updated packages.

**Comment by philmmanjaro** [comment]
One change will be to use **Calamares** as our default installer. Therefore we should update our **Beginners Guide**. Teo will finish luks encryption this or next week. Every friday I'm doing a new **dev-build** so we can check the current status. With this I already fixed some isssues we had with **plasmashell**, **gcc 6.1** and **qt 5.6**.

**Comment by udeved** [comment]
@philmmanjaro 

Regardless of codename, if you do every Friday a dev build, can't you just release at end of month one dev build as eg "build against $branch", but no  "dev" in iso name? And every 3 month, §branch is stable? So say first month between stable releases, you do end of month unstable, second month between you do testing.
We'd get a monthly stable -> unstable -> testing -> stable cycle

**Comment by Ste74** [comment]
Related at this https://github.com/manjaro/release-plan/issues/76 , @philmmanjaro i don't problem with this release but in according with @udeved ( https://forum.manjaro.org/t/sf-download-locations/5690/12 ) thinking you can decide once and for all the release stable cycle? :smile:

**Comment by udeved** [comment]
I would also opt for 16.09, to stick with the cycle that was established.

**Comment by philmmanjaro** [comment]
I'm releasing now another preview of **Ellanda**. Original I planned to have RC1 by now. Seems the current packages are against me :smile:

**Comment by udeved** [comment]
We could use 0.13.5 soon. Should be stable then.

**Comment by oberon2007** [comment]
I'm currently building an i3 ISO based on master. Will report back about my findings :wink:

**Comment by oberon2007** [comment]
Will try installing with Calamares now...

**Comment by Ste74** [comment]
> https://bugs.manjaro.org/index.php?do=details&task_id=10
btw: Do you guys receive notifications for new tasks from bugs.manjaro.org? I don't and I can't find any settings for this...

no equal at you

**Comment by philmmanjaro** [comment]
I get email as I enabled myself to get some. By default it is set to none.

**Comment by udeved** [comment]
@oberon2007 

I am currently at laptop and forgot the password for new bugtracker. Its at home, and I don't wanna request new passwd.
The live environment is only configured in the livecd repo code. Its not by buildiso any longer.

**Comment by Ste74** [comment]
In my panel i see : group basic and Notification for the changes made by myself

**Comment by oberon2007** [comment]
@udeved , so do we need a package update of **manjaro-live-systemd**?

**Comment by udeved** [comment]
https://github.com/manjaro/manjaro-tools-livecd/commit/1f05714a797d1d749daebab6271ff467a992b448

**Comment by oberon2007** [comment]
@philmmanjaro , you mean here in the profile?
Or is there a setting in a different place?
!  [img](http://imgur.com/dDBcrbBl.png)

**Comment by oberon2007** [comment]
Maybe only the admin receives notifications for everything the way it is configured now?

**Comment by philmmanjaro** [comment]
Uncheck the checkbox might help. I've to see. Maybe I've to update **flyspray** to get it working. We will see.

**Comment by Ste74** [comment]
Ellada is out :smile: close it :wink:
