### ISSUE TITLE
Fix the regression that QT 5.7.0 doesn't support GTK3 theming

### ISSUE THREAD

**Issue by philmmanjaro** [manjaro/release-plan#73]
After upgrading Qt 5.6 -> 5.7, the GTK widget style disappeared and is not longer used by KDE applications as well as unavailable in System settings>Application style>Widget style

This has two reasons:

- QGtkStyle was moved to the qtstyleplugins repository (package **qt5-styleplugins**)
- **qt5ct** can be used as alternative

Using **qt5-styleplugins**:

- change the **/etc/environment** override variable to: `QT_STYLE_OVERRIDE=gtk2`

Using **qt5ct**:

- run `qt5ct` to set an icon theme, and set the environment variable `QT_QPA_PLATFORMTHEME=qt5ct` in **/etc/environment**.

To have the style also for applications you use **sudo** or any tools to get **root rights** you have to copy your **dot-config** file over with `cp -a /etc/skel/.config /root/`.

**Comment by philmmanjaro** [comment]
https://github.com/manjaro/manjaro-tools/commit/6770fb9bd1ca2642b63553e5a3346169485e7224

**Comment by philmmanjaro** [comment]
Check also [Arch Wiki](https://wiki.archlinux.org/index.php/Uniform_look_for_Qt_and_GTK_applications) on this topic.

**Comment by philmmanjaro** [comment]
If you have seg-faults with QT apps please do this:

* Install **qt5-styleplugins** and **qt5ct**
* Set environment variable in **/etc/environment** `QT_QPA_PLATFORMTHEME=qt5ct`
* Restart the system
* Start `qt5ct` and select **gtk2**

**Comment by SanKro** [comment]
could we set the environment variables in a script in /etc/profile.d/somescript.sh ?
because  there are people here who have XFCE AND KDE Plasma installed for different user. right now it just works the way that i use the normal manjaro design in XFCE (also for Qt apps) and on KDE Plasma breeze (also for GTK apps).

this solution in /etc/environment would force the style on both systems to use whatever is selected in qt5ct? so i would have to switch first after every start of a different desktop environment?

**Comment by philmmanjaro** [comment]
Fixes for **XFCE edition**: https://github.com/manjaro/manjaro-xfce-settings/commit/5056aa555b1424119ae41ed061d9e82446b6f5e6, https://github.com/manjaro/packages-community/commit/45d9fa9b55846e911e51611b8f4d049684c8f41c

**Comment by philmmanjaro** [comment]
@SanKro: please read this [thread](https://bbs.archlinux.org/viewtopic.php?id=214147).

**Comment by philmmanjaro** [comment]
It will be fun when **gtk2** support is dropped for good [1](https://lists.debian.org/debian-qt-kde/2016/04/msg00219.html), [2](https://codereview.qt-project.org/gitweb?p=qt%2Fqtbase.git;a=commit;h=899a815414e95da8d9429a4a4f4d7094e49cfc55)

**Comment by SanKro** [comment]
@philmmanjaro for the long run. isnt it possible to change Breeze or Adwaita to be more "manjarosh" since the two of them are available with Qt4,5 and GTK2,3 support?

**Comment by philmmanjaro** [comment]
@SanKro: please use the **Maia** themes, which is what you're searching for ...

**Comment by SanKro** [comment]
@philmmanjaro no it isnt. because there is no maia Qt widget style. here you need to use the GTK widget style for Qt apps.
what i mean is to create a widget style for:
GTK2, GTK3, Qt4, Qt5 that looks unified on every framework.
for the moment only 2 "styles" provide this: 
 * Breeze (available for Qt5,Qt4, GTK2, GTK3) 
 * Adwaita (available for GTK2, GTK 3 and https://github.com/MartinBriza/adwaita-qt Qt4 Qt5)

what i mean is not to "emulate" a GTK look, but to have native styles for every framework that looks the same.

so again - for the long run - wouldnt it be better to use adwaita or breeze and change them to fit into manjaros styleguidelines than to workaround the situation by pulling in a gtk2 look into Qt without real upstream support?

**Comment by Kirek** [comment]
maia-gtk is breeze-gtk with the maia color scheme, so using breeze widgets + maia colorscheme + maia-gtk matches.

**Comment by SanKro** [comment]
@Kirek ohh i didnt knew that. thanks so its of course the thing i'm describing. but then, why using this workaround with gtk2 themes for Qt instead of just using native breeze+colors?

**Comment by philmmanjaro** [comment]
For xfce we are using **vertex-maia** theme. On KDE this issue should not be present. There we use **maia**.

**Comment by philmmanjaro** [comment]
QT 5.7 [source breaks](http://doc.qt.io/qt-5/sourcebreaks.html) are useful to find out what changed in regard of styling:

Changes to QStyle

**QStyle::standardIconImplementation()** and **QStyle::layoutSpacingImplementation()** are removed, and the **QStyle::standardIcon()** and **QStyle::layoutSpacing()** functions are made pure virtual now. The removed functions were introduced in Qt 4 for binary compatibility reasons.
**QMotifStyle**, **QPlastiqueStyle**, **QCleanlooksStyle**, and **QCDEStyle** are replaced with a new fusion style. If your application depends on any of these removed styles, you can either use the [qtstyleplugins project](http://code.qt.io/cgit/qt/qtstyleplugins.git/) to get these styles or update your application to use the new fusion style. For more details about this change, see [this blog post](https://blog.qt.io/blog/2012/10/30/cleaning-up-styles-in-qt5-and-adding-fusion/).

The following QStyle implementations have been made internal:

* QFusionStyle
* QGtkStyle
* QMacStyle
* QWindowsCEStyle
* QWindowsMobileStyle
* QWindowsStyle
* QWindowsVistaStyle
* QWindowsXPStyle

Instead of creating instances or inheriting these classes directly, use:

* QStyleFactory for creating instances of specific styles.
* QProxyStyle for customizing existing style implementations.
* QCommonStyle as a base for implementing full custom styles.

**Comment by philmmanjaro** [comment]
Seems with the current [dev-build](https://sourceforge.net/projects/manjarotest/files/16.08-dev/xfce/minimal/) I managed to restore the unified look at least for XFCE. KDE edition has still some issues we should resolve ...

**Comment by philmmanjaro** [comment]
Some issues found with this:

`cinnamon --replace` overwrites QT_STYLE_OVERRIDE with `gtk`
LXDE has `QT_PLATFORM_PLUGIN` and `QT_QPA_PLATFORMPLUGIN` value hard coded in **lxsession** in `environment.c` within lines 678-679.

**Comment by kouros17** [comment]
I confirm that dev-build resolved the issue, but still exist το my current xfce desktop:
https://forum.manjaro.org/t/theme-issue-with-manjaro-settings-manager/5145

**Comment by philmmanjaro** [comment]
@kouros17: you have to select **gtk2** as theme and rerun `qt5ct` with **root rights** to do the same.

**Comment by philmmanjaro** [comment]
Seems the decision to remove **gtk theme support** was made almost [one year ago](https://github.com/qt/qtbase/commit/899a815414e95da8d9429a4a4f4d7094e49cfc55). One month later it was [moved to styleplugins](https://github.com/qt/qtstyleplugins/commit/102da7d50231fc5723dba6e72340bef3d29471aa). So far only two patches got added ([1](https://github.com/qt/qtstyleplugins/commit/7894e252d192c8fa2e0f9e66ad0c69a086670b05), [2](https://github.com/qt/qtstyleplugins/commit/bab11e7910d37bcf8b90d9be664757a9be568077)). Lets see what the difference now is.

**Comment by philmmanjaro** [comment]
I [reviewed the code](https://gist.github.com/philmmanjaro/877deb2a3e2979576f18455bc8331b53) and as mentioned, the code was simplified as direct linkage to libraries is used, instead QLibrary as before. However this needed also been changed within LXDE, Mate, Cinnamon, Gnome etc. to make it work.

**Comment by sljunkie** [comment]
I'm on Arch Linux. I'm experimenting with the **qt5-styleplugins** and **qt5ct** - these fixes won't work on gnome since starting a gnome-sessions overrides `QT_QPA_PLATFORMTHEME=qgnomeplatform`. This design worked with qt5 < 5.7. And [the folks at Qt](https://bugreports.qt.io/browse/QTBUG-52259) said that gtk3 plugin won't be provided until 5.8.0.

**Comment by philmmanjaro** [comment]
Seems to be a deadlock then. One option would be to revert the changes and adopt that what is added to the **qt 5.6 LTS** series also to **qt 5.7** series. This means Manjaro has to rebuild **qt5-base** on its own.

**Comment by philmmanjaro** [comment]
@sljunkie: the other weird option would be to patch **qt5ct** to accept also `qgnomeplatform` and such same as `qt5ct` so this won't matter as long as we know what platform theme the other applications use. I'll think about it.

**Comment by sljunkie** [comment]
It's a workaround. In gnome I could apply qt5ct but only on the terminal. Another tweak I could do is to change the .desktop files of the Qt applications I use (Lyx and Texmaker) so they'd exec `QT_QPA_PLATFORMTHEME=qt5ct <application name>` Somebody from [Debian](https://lists.debian.org/debian-qt-kde/2016/04/msg00219.html) suggested the most sound - and laborious - solution: make QGtkStyle support GTK3 styles.

> Basically GTK+ 2.x is going away, and because the whole styling model changed
in GTK+ 3.x, the only way of porting QGtkStyle to GTK+ 3 is a complete rewrite
of it (which nobody volunteered to do).

Most active linux GUI applications have already transitioned to GTK3 or QT5 (or are working on it) so that makes sense.

**Comment by sljunkie** [comment]
Ah, check this out on the [Arch Linux thread](https://bbs.archlinux.org/viewtopic.php?pid=1639229#p1639229).

So a simple workaround (when gtk 3.21.3 is officialy released) that would work in all DE's is to include an executable `/etc/profile.d/qt5style.sh` file containing

`export QT_QPA_PLATFORMTHEME=qt5ct`

in the **qt5ct** package.

**Comment by sljunkie** [comment]
I'll try to push a patch for gnome-session 3.20.1 to fix this

**Comment by philmmanjaro** [comment]
@sljunkie: please test the package I've already uploaded to our **unstable** branch and tell me if it works for you. It should be easy for Arch to include the upstream patch also in their package.

**Comment by sljunkie** [comment]
@philmmanjaro I rebuilt gnome-session. The patch works perfectly.

The other Arch package that could be modified is qt5ct - because if you are to use it you'll need to set the environment variable `QT_QPAPLATFORMTHEME=qt5ct` somewhere. These lines added in the PKGBUILD should work for all DE's // WM's:

```
echo "export QT_QPAPLATFORMTHEME=qt5ct" > /etc/profile.d/
chmod +x /etc/profile.d/qt5ct.sh
```

**Comment by philmmanjaro** [comment]
Currently we are useing the **/etc/environment** as explained in the first post of this issue thread. This is already part of our **manjaro-tools** and will be active with our next ISOs automatically.

**Comment by oberon2007** [comment]
I guess not much can be done about a historical qt4-application like **skype**, sigh!?
Until recently this could at least more or less be solved with qtconfig-qt4, but now:

![](http://i.imgur.com/plFMJsYl.png)

**Comment by SanKro** [comment]
after all its not worth to work on it anymore, since the new skype for linux 
isnt using Qt anymore.
https://community.skype.com/t5/Linux/Skype-for-Linux-Alpha-and-calling-on-Chrome-amp-Chromebooks/td-p/4434299

yaourt -S skypeforlinux-bin
https://aur.archlinux.org/packages/skypeforlinux-bin/

but i remember that you can set the Qt style from inside of skype settings

Am Dienstag, 19. Juli 2016, 14:49:15 CEST schrieb Bernhard Landauer:

**Comment by oberon2007** [comment]
Ah, cool! I didn't even know of that project, yet. Great news! 
Setting the style in the Skype options didn't work properly any more in any case...
Thanks!

**Comment by Frechdachs** [comment]
@oberon2007 AFAIK, the new skype client is just a browser that's running Skype web. So it probably won't show old p2p based group conversations. The only way to get those working on Linux seems to be the old qt4 based client. The official Skype client on Windows still supports the old p2p based group conversations.

**Comment by philmmanjaro** [comment]
**skype** is now officially removed from our repos beginning with todays **testing/unstable** update.

**Comment by philmmanjaro** [comment]
Question is now only if we need both entries or when **qt5ct** installed only the later ...

```
QT_STYLE_OVERRIDE='gtk2' >> /etc/environment
QT_QPA_PLATFORMTHEME='qt5ct' >> /etc/environment
```

**Comment by Esclapion** [comment]
On Lxqt, I need only:

QT_STYLE_OVERRIDE='gtk2' >> /etc/environment

no need of gt5ct.

**Comment by oberon2007** [comment]
``QT_QPA_PLATFORMTHEME='qt5ct'`` only is working fine on i3, Cinnamon and Deepin :laughing: 
I think ``$QT_STYLE_OVERRIDE`` alone did not do the trick - will double-check.

**Comment by oberon2007** [comment]
At least in Deepin it is as @Esclapion says: With only **qt5-styleplugins** and ``QT_STYLE_OVERRIDE='gtk2'`` qt styling works.

**Comment by Esclapion** [comment]
Both doesn't hurt in my case. One (QT_QPA...)  is only ineffective.

**Comment by philmmanjaro** [comment]
Ok, so for **qt5ct** to run on more DEs than XFCE `QT_STYLE_OVERRIDE='gtk2'` is also needed. For now we have this:

* by installing **qt5-styleplugins** only `QT_STYLE_OVERRIDE='gtk2'` gets added
* by installing **qt5ct** only `QT_QPA_PLATFORMTHEME='qt5ct'` gets added

My question is: should I not remove `QT_STYLE_OVERRIDE` when **qt5ct** got detected? https://github.com/manjaro/manjaro-tools/commit/af562e2da2bc82d18d7c13cb1b3ad34741bdf845

**Comment by oberon2007** [comment]
Looks like in order to serve all DEs we will need both. Cinnamon apparently like Lxqt needs ``QT_STYLE_OVERRIDE='gtk2'`` set, probably KDE, too?

**Comment by oberon2007** [comment]
In fact at the moment we're not even writing anything for Lxqt
```
case ${profile} in
		cinnamon*|deepin*|gnome|i3|lxde|mate|netbook|openbox|pantheon|xfce*)
```
But does it really make sense to override styling with gtk2 in a qt environment like lxqt by default, @Esclapion ?
Re ``QT_STYLE_OVERRIDE`` for gtk environments I suggest we keep it.
Otherwise we need to find out first which DEs need it. Cinnamon does, obviously, and possibly others, too...

**Comment by Esclapion** [comment]
For the moment, Lxqt uses by default gtk theme. Not directly Qt themes.
If an user will try to use Qt theme (if possible), he can change also /etc/environment ?

Lxqt 0.11 will come soon, but for the moment I read no change on this area.

**Comment by Ste74** [comment]
I m embarassed, i lost this discussion and in this day don`t use qt application (not see theme broken) .. will  see...
Il 02/ago/2016 10:33, Bernhard Landauer <notifications@github.com> ha scritto:Looks like in order to serve all DEs we will need both. Cinnamon apparently like Lxqt needs QT_STYLE_OVERRIDE='gtk2' set, probably KDE, too?

**Comment by oberon2007** [comment]
@Ste74 you can check easily with **manjaro-settings-manager** if it gets styled correctly. It is qt! :wink:

**Comment by oberon2007** [comment]
@Esclapion , so does Lxqt gtk2 automatically, or do you need to set QT_STYLE_OVERRIDE=gtk2 manually? If the user wants to set qt themes, he can do it with qt5ct (or qtconfig-qt4 for some 'ancient' apps ;) )

**Comment by Esclapion** [comment]
Not automatically, I must add QT_STYLE_OVERRIDE=gtk2 to /etc/environment.

qtconfig-qt4 has no effect on a qt5 environment. qt5ct is for me more an experimental tool, not commonly used by Lxqt users. Some people uses more QtCurve, else.

**Comment by Ste74** [comment]
Maybe gnome no affect ?
![schermata del 2016-08-02 18-42-53](https://cloud.githubusercontent.com/assets/11218234/17337066/6678a856-58e1-11e6-8162-d137bdbfa7b7.png)
![schermata del 2016-08-02 18-43-20](https://cloud.githubusercontent.com/assets/11218234/17337070/6d9c2022-58e1-11e6-87df-539aee6013aa.png)
![schermata del 2016-08-02 18-44-09](https://cloud.githubusercontent.com/assets/11218234/17337074/7437975e-58e1-11e6-84ef-59827d08436f.png)
![schermata del 2016-08-02 18-45-39](https://cloud.githubusercontent.com/assets/11218234/17337077/798694d0-58e1-11e6-9f74-7e2982bf8540.png)

**Comment by philmmanjaro** [comment]
Seems this leads nowhere. Let me explain in more detail.

We have two tools: **qt5-styleplugins** is needed since **qt 5.7** dropped support of gtk styling. To have it activated you need to add `QT_STYLE_OVERRIDE='gtk2'` instead of the old `QT_STYLE_OVERRIDE='gtk'`. On some DEs like **XFCE** installing **qt5-styleplugins** might lead to application crashes.

Therefore **qt5ct** exists, which needs `QT_QPA_PLATFORMTHEME='qt5ct'` to work. In the tool itself you can configure then which style you like and it will be saved in the conf file of **qt5ct**. Therefore no style override is needed.

So what happens:

* by installing qt5-styleplugins only `QT_STYLE_OVERRIDE='gtk2'` gets added
* by installing qt5ct only `QT_QPA_PLATFORMTHEME='qt5ct'` gets added and `QT_STYLE_OVERRIDE='gtk2'` gets removed

So my question is only regarding the current **qt5ct** setup, if that works for you. If you don't need it it won't change the settings anyway. I hope this is now more clearer to understand.

**Comment by oberon2007** [comment]
Yes, understood! And what I was trying to say that for Cinnamon it doesn't:

 [img]http://imgur.com/fUce0orl.png[/img]

**qt5-styleplugins** and **qt5ct** are installed, but **msm** is only styled correctly when **both** variables are defined!

**Comment by v17564** [comment]
My system: Manjaro OpenRC 16.06 Xfce x64 running in a virtualbox for probe. Yesterday i installed qt5ct and qt5-styleplugins in a notebook with i686 with the same result.

I made with Vertex-Maia theme and all steps of configuration process: Configure QT apps
[https://wiki.manjaro.org/index.php?title=Set_all_Qt_app%27s_to_use_GTK%2B_font_%26_theme_settings](url)

- qt5ct work: change from Windows to Fusion.
- qt5-styleplugins: don't work

for me.

I explain: if i install qt5-styleplugins and exec qt5ct for select "gtk2", the window of "menu -> configuration -> manjaro-settings-manager" always appear in black colour with a large buttons:
![manjaro 16 06 x64 clonar corriendo - oracle vm virtualbox_001](https://cloud.githubusercontent.com/assets/7533265/17338873/8f4c7980-58e9-11e6-8583-fecaa697afc3.png)

Also i try the philm xfce solution, but nothing.
[https://github.com/manjaro/manjaro-xfce-settings/commit/5056aa555b1424119ae41ed061d9e82446b6f5e6](url)

I installed qbittorrent and it seen correct.
![manjaro 16 06 x64 clonar corriendo - oracle vm virtualbox_002](https://cloud.githubusercontent.com/assets/7533265/17338894/b2dcce36-58e9-11e6-9d0b-29d517736977.png)

Now i delete qt5-styleplugins and select "Fusion" with qt5ct and all programs are seen correct.

I test with elementary theme without problem, i think isn't problem with the theme.

Note: also i downgrade gtk2 to version 2.24.30-2

**Comment by philmmanjaro** [comment]
**fusion** is the default **qt5** style. So I keep the override then. On my end it doesn't hurt if both are set. Let me review how we set it best ...

**Comment by oberon2007** [comment]
I think the old version ``QT_STYLE_OVERRIDE='gtk` can just be left out, no?

**Comment by v17564** [comment]
The aspect of qbittorrent in my actual physical machine without qt5ct:
![qbittorrent v3 3 6_003](https://cloud.githubusercontent.com/assets/7533265/17340154/54906f12-58ef-11e6-84af-acb5a0919713.png)

see the "Progreso" column:
![seleccion_004](https://cloud.githubusercontent.com/assets/7533265/17340231/9f90122e-58ef-11e6-8605-1244adb8865c.png)

**Comment by v17564** [comment]
I don't know @oberon2007, i delete the line QT_STYLE_OVERRIDE='gtk', and work.
You should ask to @philm.

**Comment by Esclapion** [comment]
I don't use "fusion", but "gtk2' for Style.

**Comment by v17564** [comment]
@philmmanjaro can you speak with developers of qt5ct to change the size of window?.

In a resolution of 1024x768 the size of the window for qt5ct are very large, it doesn't leave resize and therefore, the only way of gaining access to the buttons to "apply" and "ok" it's "moving" the window with alt+space with option "move".

**Comment by philmmanjaro** [comment]
`QT_STYLE_OVERRIDE='gtk'` is the old and needs to be changed to `QT_STYLE_OVERRIDE='gtk2'``as used by the new package **styles**. I think with the latest setup it should be fine now.

**Comment by oberon2007** [comment]
@v17564 **qt5ct** has a [bugtracker](https://sourceforge.net/p/qt5ct/tickets/?source=navbar) and I made the experience that they reply really quickly :) Please open a ticket there!

**Comment by v17564** [comment]
Ok @philmmanjaro i open a ticket.
Thanks.

**Comment by v17564** [comment]
Like clarification only.

Qbittorrent aspect without installing qt5ct and without changing the values of the variables in /etc / environment:

![manjaro 16 06 x64 clonar corriendo - oracle vm virtualbox_005](https://cloud.githubusercontent.com/assets/7533265/17374825/ac3d784e-59ae-11e6-93a4-48ba3563b9a9.png)

After installed qt5ct but "not" run the command, isn't necessary, and change the variables:

![manjaro 16 06 x64 clonar corriendo - oracle vm virtualbox_006](https://cloud.githubusercontent.com/assets/7533265/17374897/00b51cd8-59af-11e6-8214-bb8a29ddd534.png)


The aspect has changed.

**Comment by philmmanjaro** [comment]
@v17564: that is the default **fusion** theme QT5 uses now.

**Comment by v17564** [comment]
Hello.
I think that it would be necessary to change the parameters of configuration of qt5ct to avoid the exhibited in the following entry of the qt5ct bugtracer: 

Size of window is very large
https://sourceforge.net/p/qt5ct/tickets/23/

It would be necessary to remove from the configuration parameters the QT_STYLE_OVERRIDE in the /etc/environment and in the .xprofile of the users and only leave the QT_QPA_PLATFORMTHEME ='qt5ct'

For whom it has already installed qt5ct with qt5-styleplugins, it is recommended to erase the  configuration subdirectory of the user: rm -rf ~/.config/qt5ct

**Comment by philmmanjaro** [comment]
This is already taken care of with 16.08-pre4.

**Comment by philmmanjaro** [comment]
Seems root user is still [missing](https://github.com/calamares/calamares-manjaro/issues/27) partly ...

**Comment by udeved** [comment]
> To automatically set QT_QPA_PLATFORMTHEME for user session, add the following line to ~/.profile.

`[ "$XDG_CURRENT_DESKTOP" = "KDE" ] || [ "$XDG_CURRENT_DESKTOP" = "GNOME" ] || export QT_QPA_PLATFORMTHEME="qt5ct"
`

> This will export QT_QPA_PLATFORMTHEME environment variable for the whole user session.

https://wiki.archlinux.org/index.php/qt

**Comment by TomaszGasior** [comment]
Would be better to use by default in Manjaro XFCE this package — https://aur.archlinux.org/packages/qt5gtk2/ — instead of qt5ct? It seems to me, that Manjaro's users don't need Qt5 configuration tool. This solution is simpler to maintenance (QT_QPA_PLATFORMTHEME=qt5gtk2 variable is only needed, you don't have to keep qt5 configs in /etc/skel).

**Comment by embluk** [comment]
Hello,
I am using the Cinnamon desktop and I am trying to get https://github.com/mattanger/ckb-next working. I can install CKB but whenever I click on change colour the app crashes and after submitting an issue on https://github.com/mattanger/ckb-next the devs say it is something to do with Qt not supporting GTK theming anymore, they said they won't help as its not an issue directly around CKB.

I feel this issue where the app crashes when clicking on 'Change Colour' is something to do with what is referenced in this thread. I've gone through this thread and tried everything mentioned and still no luck.

I installed qt5ct but I cannot open it from the menu as it displays 1 error being:
` Please remove the QT_STYLE_OVERRIDE environment variable`
Inside /etc/enviroment all I have is QT_QPA_PLATFORMTHEME=qt5ct

To get qt5ct to run I have to use (From @v17564 ):
```
rm -rf ~/.config/qt5ct
export -n QT_STYLE_OVERRIDE
export QT_QPA_PLATFORMTHEME=qt5ct
qt5ct
```
All I select then is only GTK+, no other GTK variant...

If this helps here are the errors when the app crashes:
```
(ckb:18458): GLib-GObject-WARNING **: cannot register existing type 'GtkWidget'

(ckb:18458): GLib-GObject-WARNING **: cannot add class private field to invalid type '<invalid>'

(ckb:18458): GLib-GObject-WARNING **: cannot add private field to invalid (non-instantiatable) type '<invalid>'

(ckb:18458): GLib-GObject-CRITICAL **: g_type_add_interface_static: assertion 'G_TYPE_IS_INSTANTIATABLE (instance_type)' failed

(ckb:18458): GLib-GObject-WARNING **: cannot register existing type 'GtkBuildable'

(ckb:18458): GLib-GObject-CRITICAL **: g_type_interface_add_prerequisite: assertion 'G_TYPE_IS_INTERFACE (interface_type)' failed

(ckb:18458): GLib-CRITICAL **: g_once_init_leave: assertion 'result != 0' failed

(ckb:18458): GLib-GObject-CRITICAL **: g_type_add_interface_static: assertion 'G_TYPE_IS_INSTANTIATABLE (instance_type)' failed

(ckb:18458): GLib-GObject-CRITICAL **: g_type_register_static: assertion 'parent_type > 0' failed

(ckb:18458): GLib-GObject-WARNING **: cannot add private field to invalid (non-instantiatable) type '<invalid>'
```

**Comment by TomaszGasior** [comment]
@embluk please test qt5gtk2.
install https://aur.archlinux.org/packages/qt5gtk2/
and use QT_QPA_PLATFORMTHEME=qt5gtk2

**Comment by philmmanjaro** [comment]
@embluk: what happens if you call in a terminal `echo $QT_STYLE_OVERRIDE`?

**Comment by embluk** [comment]
I seem to have solved my issue by installing Qt 5.5 and building CKB with that. Then everything worked.
But because I wanted Qt 5.8, I uninstalled Qt 5.5 and installed Qt 5.8 and CKB still works, no issues. I guess it is because I built it from source using Qt 5.5 where the Gtk styling issue is not there...

Anyway, I tried @philmmanjaro suggestion to use `echo $QT_STYLE_OVERRIDE` and it gives me `gtk` in the terminal.

**Comment by niccolatorres** [comment]
I've `unset QT_STYLE_OVERRIDE` on linux to avoid annoying 

> QApplication invalid style override passed ignoring it

**Comment by Yanpas** [comment]
The only Qt5 application which doesn't use `qt5ct` theming is Qt creator. It still looks unfriendly with Xfce and any other Gtk DE

**Comment by sljunkie** [comment]
Under Gnome only Texmaker overrides qt5ct's color theme.

**Comment by J-J-Chiarella** [comment]
May be relevant: On Xubuntu, the qt5-style-plugins package works with Qbittorrent just fine, but Lyx does not use the file chooser from gtk and does not use the GTK button order (even though theming of bars and icons works). Maybe it affects Manjaro, too. Something you may want to check.

**Comment by codesardine** [comment]
Theming on linux is a mess, i still dont have uniform look across toolkits, what is the manjaro team using in 2018 for uniform look and witch themes are more supported.

**Comment by TomaszGasior** [comment]
`qt5ct` is unneeded now. It is possible to safely uninstall it*. Instead install `qt5-styleplugins` and use `QT_QPA_PLATFORMTHEME=gtk2` environment variable, for example in `/etc/environment`. 
In the past it didn't work but currently problem is fixed in Qt and this way you can easly get more consistent look of dialogs and skin without additional software.

* — Not in Manjaro, where it is dependency for `manjaro-<desktop>-settings` package.
