### ISSUE TITLE
fail to startx with nvidia GTX 1070 GPU

### ISSUE THREAD

**Issue by alexcwyu** [manjaro/release-plan#75]
i try to install manjaro xfce on my PC, which is using nvidia GTX 1070 GPU.
the live usb fail to startx. it seems to me the display card is not supported by mhwd / kernel.

can we support NVidia 367.27 driver please?

**Comment by Strit** [comment]
Sure, when it's not a BETA driver anymore.

**Comment by alexcwyu** [comment]
@Strit , can I just build the manjaro xfce iso and add support of the driver myself?

i am thinking to following this link to rebuild the iso:
https://old.forum.manjaro.org/index.php?topic=31731.0
https://wiki.manjaro.org/index.php?title=Build_Manjaro_ISOs_with_buildiso

how can I add the driver to kernel / mhwd?
Please shed some light on the step..

thanks!

**Comment by Strit** [comment]
Not sure how you can add them to mhwd, since that's a package phil controls.
Does the free driver not support the 1070 yet?

**Comment by udeved** [comment]
mhwd database need to support your gpu.
It will likely be supported when the driver becomes stable.

**Comment by alexcwyu** [comment]
more info from journalctl:

`Jul 06 21:53:38 manjaro systemd[1]: Started Accounts Service.
Jul 06 21:53:38 manjaro systemd[1]: Received SIGRTMIN+21 from PID 537 (plymouthd).
Jul 06 21:53:38 manjaro systemd[1]: Started Wait for Plymouth Boot Screen to Quit.
Jul 06 21:53:38 manjaro systemd[1]: Started Light Display Manager.
Jul 06 21:53:38 manjaro pacman-key[1596]: ==> Updating trust database...
Jul 06 21:53:38 manjaro pacman-key[1596]: gpg: marginals needed: 3 completes needed: 1 trust model: pgp
Jul 06 21:53:38 manjaro pacman-key[1596]: gpg: depth: 0 valid: 1 signed: 18 trust: 0-, 0q, 0n, 0m, 0f, 1u
Jul 06 21:53:38 manjaro pacman-key[1596]: gpg: depth: 1 valid: 18 signed: 66 trust: 0-, 0q, 0n, 18m, 0f, 0u
Jul 06 21:53:38 manjaro pacman-key[1596]: gpg: depth: 2 valid: 66 signed: 7 trust: 66-, 0q, 0n, 0m, 0f, 0u
Jul 06 21:53:38 manjaro pacman-key[1596]: gpg: next trustdb check due at 2016-10-19
Jul 06 21:53:38 manjaro systemd[1]: Started Initializes Pacman keyring.
Jul 06 21:53:38 manjaro systemd[1]: Reached target Multi-User System.
Jul 06 21:53:38 manjaro systemd[1]: Reached target Graphical Interface.
Jul 06 21:53:38 manjaro systemd[1]: Started TLP system startup/shutdown.
Jul 06 21:53:38 manjaro systemd[1]: Startup finished in 10.709s (kernel) + 10.510s (userspace) = 23min 1.638s.
Jul 06 21:53:38 manjaro kernel: Non-volatile memory driver v1.3
Jul 06 21:53:38 manjaro tlp[2026]: Loading kernel modules...done.
Jul 06 21:53:38 manjaro NetworkManager[1506]: <info> [1467842018.9827] device (enp7s0): link connected
Jul 06 21:53:38 manjaro NetworkManager[1506]: <info> [1467842018.9831] device (enp7s0): state change: unavailable -> disconnected (reason 'carrier-changed') [20 30 40]
Jul 06 21:53:38 manjaro NetworkManager[1506]: <info> [1467842018.9842] policy: auto-activating connection 'Wired connection 1'
Jul 06 21:53:38 manjaro kernel: igb 0000:07:00.0 enp7s0: igb: enp7s0 NIC Link is Up 1000 Mbps Full Duplex, Flow Control: RX/TX
Jul 06 21:53:38 manjaro kernel: IPv6: ADDRCONF(NETDEV_CHANGE): enp7s0: link becomes ready
Jul 06 21:53:38 manjaro NetworkManager[1506]: <info> [1467842018.9856] device (enp7s0): Activation: starting connection 'Wired connection 1' (42951426-6a69-3205-bfa5-55efa6da02b8)
Jul 06 21:53:38 manjaro NetworkManager[1506]: <info> [1467842018.9858] device (enp7s0): state change: disconnected -> prepare (reason 'none') [30 40 0]
Jul 06 21:53:38 manjaro NetworkManager[1506]: <info> [1467842018.9859] manager: NetworkManager state is now CONNECTING
Jul 06 21:53:38 manjaro NetworkManager[1506]: <info> [1467842018.9864] device (enp7s0): state change: prepare -> config (reason 'none') [40 50 0]
Jul 06 21:53:38 manjaro NetworkManager[1506]: <info> [1467842018.9870] device (enp7s0): state change: config -> ip-config (reason 'none') [50 70 0]
Jul 06 21:53:38 manjaro NetworkManager[1506]: <info> [1467842018.9874] dhcp4 (enp7s0): activation: beginning transaction (timeout in 45 seconds)
Jul 06 21:53:39 manjaro systemd[1]: lightdm-plymouth.service: Main process exited, code=exited, status=1/FAILURE
Jul 06 21:53:39 manjaro systemd[1]: lightdm-plymouth.service: Unit entered failed state.
Jul 06 21:53:39 manjaro systemd[1]: lightdm-plymouth.service: Failed with result 'exit-code'.
Jul 06 21:53:39 manjaro tlp[2026]: Applying power save settings...done.
Jul 06 21:53:39 manjaro tlp[2026]: Setting battery charge thresholds...done.
Jul 06 21:53:39 manjaro NetworkManager[1506]: <info> [1467842019.4945] address 192.168.0.112
Jul 06 21:53:39 manjaro NetworkManager[1506]: <info> [1467842019.4945] plen 24
Jul 06 21:53:39 manjaro NetworkManager[1506]: <info> [1467842019.4946] expires in 86400 seconds
Jul 06 21:53:39 manjaro NetworkManager[1506]: <info> [1467842019.4946] nameserver '192.168.0.1'
Jul 06 21:53:39 manjaro NetworkManager[1506]: <info> [1467842019.4946] gateway 192.168.0.1
Jul 06 21:53:39 manjaro NetworkManager[1506]: <info> [1467842019.4948] dhcp4 (enp7s0): state changed unknown -> bound
Jul 06 21:53:39 manjaro avahi-daemon[1508]: Joining mDNS multicast group on interface enp7s0.IPv4 with address 192.168.0.112.
Jul 06 21:53:39 manjaro avahi-daemon[1508]: New relevant interface enp7s0.IPv4 for mDNS.
Jul 06 21:53:39 manjaro avahi-daemon[1508]: Registering new address record for 192.168.0.112 on enp7s0.IPv4.
Jul 06 21:53:39 manjaro NetworkManager[1506]: <info> [1467842019.4962] device (enp7s0): state change: ip-config -> ip-check (reason 'none') [70 80 0]
Jul 06 21:53:39 manjaro NetworkManager[1506]: <info> [1467842019.4970] device (enp7s0): state change: ip-check -> secondaries (reason 'none') [80 90 0]
Jul 06 21:53:39 manjaro NetworkManager[1506]: <info> [1467842019.4975] device (enp7s0): state change: secondaries -> activated (reason 'none') [90 100 0]
Jul 06 21:53:39 manjaro NetworkManager[1506]: <info> [1467842019.4976] manager: NetworkManager state is now CONNECTED_LOCAL
Jul 06 21:53:39 manjaro NetworkManager[1506]: <info> [1467842019.4982] manager: NetworkManager state is now CONNECTED_GLOBAL
Jul 06 21:53:39 manjaro NetworkManager[1506]: <info> [1467842019.4983] policy: set 'Wired connection 1' (enp7s0) as default for IPv4 routing and DNS
Jul 06 21:53:39 manjaro NetworkManager[1506]: <info> [1467842019.4990] dns-mgr: Writing DNS information to /usr/bin/resolvconf
Jul 06 21:53:39 manjaro systemd[1]: lightdm-plymouth.service: Service hold-off time over, scheduling restart.
Jul 06 21:53:39 manjaro systemd[1]: Stopped Light Display Manager.
Jul 06 21:53:39 manjaro systemd[1]: Starting Light Display Manager...
Jul 06 21:53:39 manjaro systemd[1]: Started Light Display Manager.
Jul 06 21:53:39 manjaro systemd[1]: lightdm-plymouth.service: Main process exited, code=exited, status=1/FAILURE
Jul 06 21:53:39 manjaro systemd[1]: lightdm-plymouth.service: Unit entered failed state.
Jul 06 21:53:39 manjaro systemd[1]: lightdm-plymouth.service: Failed with result 'exit-code'.
Jul 06 21:53:39 manjaro NetworkManager[1506]: <info> [1467842019.6697] device (enp7s0): Activation: successful, device activated.
Jul 06 21:53:39 manjaro nm-dispatcher[1623]: req:2 'up' [enp7s0]: new request (1 scripts)
Jul 06 21:53:39 manjaro nm-dispatcher[1623]: req:2 'up' [enp7s0]: start running ordered scripts...
Jul 06 21:53:39 manjaro systemd[1]: Starting Network Time Service...
Jul 06 21:53:39 manjaro systemd[1]: lightdm-plymouth.service: Service hold-off time over, scheduling restart.
Jul 06 21:53:39 manjaro systemd[1]: Stopped Light Display Manager.
Jul 06 21:53:39 manjaro systemd[1]: Starting Light Display Manager...
Jul 06 21:53:39 manjaro systemd[1]: Started Light Display Manager.
Jul 06 21:53:39 manjaro systemd[1]: lightdm-plymouth.service: Main process exited, code=exited, status=1/FAILURE
Jul 06 21:53:39 manjaro systemd[1]: lightdm-plymouth.service: Unit entered failed state.
Jul 06 21:53:39 manjaro systemd[1]: lightdm-plymouth.service: Failed with result 'exit-code'.
Jul 06 21:53:39 manjaro ntpd[2351]: ntpd 4.2.8p8@1.3265-o Sat Jun 4 14:58:28 UTC 2016 (1): Starting
Jul 06 21:53:39 manjaro ntpd[2351]: Command line: /usr/bin/ntpd -g -u ntp:ntp
Jul 06 21:53:39 manjaro systemd[1]: Started Network Time Service.
Jul 06 21:53:39 manjaro ntpd[2365]: proto: precision = 0.087 usec (-23)
Jul 06 21:53:39 manjaro ntpd[2365]: Listen and drop on 0 v6wildcard [::]:123
Jul 06 21:53:39 manjaro ntpd[2365]: Listen and drop on 1 v4wildcard 0.0.0.0:123
Jul 06 21:53:39 manjaro ntpd[2365]: Listen normally on 2 lo 127.0.0.1:123
Jul 06 21:53:39 manjaro ntpd[2365]: Listen normally on 3 enp7s0 192.168.0.112:123
Jul 06 21:53:39 manjaro ntpd[2365]: Listen normally on 4 lo [::1]:123
Jul 06 21:53:39 manjaro ntpd[2365]: bind(21) AF_INET6 fe80::e048:ca45:1512:c468%3#123 flags 0x11 failed: Cannot assign requested address
Jul 06 21:53:39 manjaro ntpd[2365]: unable to create socket on enp7s0 (5) for fe80::e048:ca45:1512:c468%3#123
Jul 06 21:53:39 manjaro ntpd[2365]: failed to init interface for address fe80::e048:ca45:1512:c468%3
Jul 06 21:53:39 manjaro ntpd[2365]: Listening on routing socket on fd #21 for interface updates
Jul 06 21:53:40 manjaro systemd[1]: lightdm-plymouth.service: Service hold-off time over, scheduling restart.
Jul 06 21:53:40 manjaro systemd[1]: Stopped Light Display Manager.
Jul 06 21:53:40 manjaro systemd[1]: Starting Light Display Manager...
Jul 06 21:53:40 manjaro systemd[1]: Started Light Display Manager.
Jul 06 21:53:40 manjaro systemd[1]: lightdm-plymouth.service: Main process exited, code=exited, status=1/FAILURE
Jul 06 21:53:40 manjaro systemd[1]: lightdm-plymouth.service: Unit entered failed state.
Jul 06 21:53:40 manjaro systemd[1]: lightdm-plymouth.service: Failed with result 'exit-code'.
Jul 06 21:53:40 manjaro avahi-daemon[1508]: Joining mDNS multicast group on interface enp7s0.IPv6 with address fe80::e048:ca45:1512:c468.
Jul 06 21:53:40 manjaro avahi-daemon[1508]: New relevant interface enp7s0.IPv6 for mDNS.
Jul 06 21:53:40 manjaro avahi-daemon[1508]: Registering new address record for fe80::e048:ca45:1512:c468 on enp7s0.*.
Jul 06 21:53:40 manjaro systemd[1]: lightdm-plymouth.service: Service hold-off time over, scheduling restart.
Jul 06 21:53:40 manjaro systemd[1]: Stopped Light Display Manager.
Jul 06 21:53:40 manjaro systemd[1]: Starting Light Display Manager...
Jul 06 21:53:40 manjaro systemd[1]: Started Light Display Manager.
Jul 06 21:53:40 manjaro systemd[1]: lightdm-plymouth.service: Main process exited, code=exited, status=1/FAILURE
Jul 06 21:53:40 manjaro systemd[1]: lightdm-plymouth.service: Unit entered failed state.
Jul 06 21:53:40 manjaro systemd[1]: lightdm-plymouth.service: Failed with result 'exit-code'.
Jul 06 21:53:40 manjaro systemd[1]: lightdm-plymouth.service: Service hold-off time over, scheduling restart.
Jul 06 21:53:40 manjaro systemd[1]: Stopped Light Display Manager.
Jul 06 21:53:40 manjaro systemd[1]: lightdm-plymouth.service: Start request repeated too quickly.
Jul 06 21:53:40 manjaro systemd[1]: Failed to start Light Display Manager.
Jul 06 21:53:41 manjaro systemd[1]: Started Getty on tty2.`

**Comment by RMKD** [comment]
I'm also having issues with a new system76 machine (i5-6600 / GTX1080) - sure would love to replace the stock ubuntu with manjaro but the 16.06 live cd won't fully load (I get to the manjaro menu but all the options produce a black screen with cursor)

I've tried adding the following boot settings (suggested [here](https://old.forum.manjaro.org/index.php?topic=26422.15) and [here](https://community.linuxmint.com/tutorial/view/842) but with no luck:
```
nomodeset
nvidia.modeset=0
i915.preliminary_hw_support=1
```


@alexcwyu - have you found a solution?

**Comment by alexcwyu** [comment]
@RMKD 
i have a workaround.

1. i install manjaro NET 16.06.1 version first  (i think i add the nomodelset and set the modeset for intel, nouveau and ATI driver to 0)

2. after installation, chroot
sudo mhwd-chroot

3. update the pacman
sudo pacman -Ssy

4. install the nvidia driver from mhwd (but the driver is old version)
sudo mhwd -a pci nonfree 0300
sudo mhwd-gpu --setgl nvidia --setxorg /etc/X11/mhwd.d/nvidia.conf

5. clone the package extra from github and update nvida version in the linux46 and nvidia-utils:
https://github.com/manjaro/packages-extra/blob/master/linux46-extramodules/nvidia/PKGBUILD
https://github.com/manjaro/packages-extra/blob/master/nvidia-utils/PKGBUILD

6. build the package and install those package with Pacman -U
sudo pacman -U nvidia-utils-1\:367.27-1-x86_64.pkg.tar.xz opencl-nvidia-1\:367.27-1-x86_64.pkg.tar.xz mhwd-nvidia-1\:367.27-1-any.pkg.tar.xz  linux46-nvidia-1\:367.27-3-x86_64.pkg.tar.xz
 
7. install xfce

8. reboot and you should be able to see the xfce login

however, i believe the testing version should contain the latest driver and you shouldn't need to do that your self.

just download the latest dev /testing xfce ISO and see if you can boot to installation or not.
https://sourceforge.net/projects/manjarotest/files/16.08-dev/xfce/minimal/

**Comment by Strit** [comment]
The newest Nvidia drivers are also in the testing and unstable repositories now.

**Comment by RMKD** [comment]
thanks all! 16.08-dev installs like a charm. looks like there may be some refinements still in progress in the manjaro settings menu, but i can read thermal and other GPU stats from the NVIDIA X Server Settings out of the box.
