### ISSUE TITLE
Breeze cursor to match Vertex-Maia

### ISSUE THREAD

**Issue by oberon2007** [manjaro/release-plan#83]
Seems like at the moment I'm the guy who questions everything ... :grin: 
But I just realized, that the original **xcursor-breeze**, Menda's parent, in fact fits the new **vertex-maia** actually a lot better than Maia > Vertex cursor, don't you think?

![](http://imgur.com/9Sw1d6yl.png)

**Comment by Esclapion** [comment]
Personnally, I use xcursor-menda. I will have  a look on xcursor-breeze.

**Comment by Strit** [comment]
They look the same to me, to be honest.

**Comment by oberon2007** [comment]
They have different colors, that's what I mean! :laughing:

**Comment by oberon2007** [comment]
![breeze-maia](https://cloud.githubusercontent.com/assets/11800714/17927882/330ae2b8-69f8-11e6-9bdc-742c26cbfa4b.jpg)
Maia (=Menda) ==> Breeze

**Comment by Strit** [comment]
I like the Maia/Menda one better of those too. The other one seems To light/bright to match my dark theme. :stuck_out_tongue:

**Comment by oberon2007** [comment]
The question here is just, which one should be used for the official configuration with Vertex-Maia or Vertex-Maia-Dark and I think the original Breeze's colors fit better. Menda was adjusted originally for Menda-gtk themes, they were a lot more green...

**Comment by Chrysostomus** [comment]
I think breeze looks way better. It goes well with dark themes, because it is easier to see against dark and green background. It also looks more neutral and fits in greater variety of backgrounds.

**Comment by oberon2007** [comment]
There was also a lot of positive feedback to breeze-cursor theme in the forum. I think people would be quite happy with it. Any objections with a switch @philmmanjaro ? For me menda-cursor just sticks out as bit of a foreign element in vertex and looks out of place.

**Comment by Chrysostomus** [comment]
Also, mendas green is different from Maia green that manjaro uses mostly nowadays. If we want to have distinctive cursor, how about if we experimented with having the Maia green in the cursor?

**Comment by Chrysostomus** [comment]
Then again, the basic breeze cursor just looks very good and is not too disturbing or out of place anywhere.

**Comment by udeved** [comment]
We we close this?

**Comment by oberon2007** [comment]
Well, do we change to Breeze? Looks like some people are in favour, others don't really care. There was no statement from @philmmanjaro , yet? I would still like to use Breeze instead of Maia cursor :)

**Comment by Huluti** [comment]
I'm in favour.

**Comment by udeved** [comment]
I also you breeze cursor in lxqt.

**Comment by Chrysostomus** [comment]
I'm in favor. Bspwm edition also uses breeze.

**Comment by Ste74** [comment]
Yep , already use Breeze in all DE 😄

**Comment by oberon2007** [comment]
:+1:
