### ISSUE TITLE
Reintroduce Catalyst-{Input, Server, Video}

### ISSUE THREAD

**Issue by philmmanjaro** [manjaro/release-plan#85]
Only **Catalyst** is using **Xorg-Server 1.17** due compatibility issues. All other drivers suffer from this fact. Back in 2013 we had a way to provide a separate Xorg subsystem to make it work. Lets reintroduce it with our next release so all other drivers can have back the latest xorg-stack. [extra:281849e](https://github.com/manjaro/packages-extra/tree/281849ea09dc765aa0a45e38561a8ec1fa1914ca)

**Comment by udeved** [comment]
Great, I dislike to align with the slowest element in the chain.

**Comment by Kirek** [comment]
Note that Catalyst is dead and won't ever receive any more updates.

**Comment by philmmanjaro** [comment]
Duly noted. However we have to provide some for our AMD users after all. Simply removing **Catalyst** when **AMDGPU-PRO** is not yet ready makes also no sense.

**Comment by udeved** [comment]
What other options would we have?
I think holding back xorg due to ati is not viable in long run, and I think xorg-1.18 is overdue already.
I only see xorg-1.17 in separate repo to solve it.

**Comment by mirh** [comment]
Cool!
I guess that mhwd will handle the switch?

> I only see xorg-1.17 in separate repo to solve it.

Why not just a separate package, like steam-specific libs?

**Comment by SanKro** [comment]
@Kirek 
> Note that Catalyst is dead and won't ever receive any more updates.

Not entirely true. They still have to support 

- Red Hat Enterprise Linux Suite 7.2, 7.1, 7.0, 6.7, 6.6, 6.5 
- Ubuntu 12.04.4 LTS, 14.04.2, 14.04.3, 15.04, 15.10
- SUSE® Linux Enterprise 11 SP3, 12
- OpenSuSE 13.1

i dont know wich of them is already EOL'd
but as long as one of them is still "in support" there will be support by amd for fglrx too. it just wont get any new feature-release.

But +1 for the idea. with xorg 1.18 we will get proper xwayland(for all OS-drivers+amdgpu-pro) and modesettings DDX support

**Comment by mirh** [comment]
Driver being EOL'd has nothing to do with distributions being EOL'd, I don't think you guys are talking about the same kind of "support"..

And Ubuntu and RHEL might even afford to just maintain status quo respectively until 2019 and 2024, just by backporting security updates to older versions.. 

But Manjaro is rolling, newer=better and old software (at least that you can update :s) is left behind. 
This xorg version "decoupling" is really welcome. 
Hopefully once this is done we might start to offer fglrx 15.12 for supported hardware too.

**Comment by SanKro** [comment]
> Driver being EOL'd has nothing to do with distributions being EOL'd, I don't think you guys are talking about the same kind of "support"..

It has since fglrx/catalyst has "Professional" support or lets call it payed support by companies. so if you advertise that this driver supports RHEL 7.2 you simply can not drop support (on driver-side) for RHEL 7.2 until this version is EOL'd. So as long as there is one of this distros+versions in support, amd has to provide support for it. And yea this is may be for up to 10(+extended support) years from now. But if there will be a RHEL 7.3 - you will not see support for it anymore

**Comment by mirh** [comment]
Trivia: Red Hat is so into compatibility that they backport everything to always keep ABI stable. 
In these situation if fglrx broken, it's their fault. 
This is not something that applies in our case, where software is expected to be updated to support newer kernels. 

Professional support is still provided to FireGL users then, something different. 

> And yea this is may be for up to 10(+extended support) years from now. But if there will be a RHEL 7.3 - you will not see support for it anymore

If they still stick to x.org 1.17, no reason anything should break. But support here just means it runs.

**Comment by philmmanjaro** [comment]
New **xorg-stack** [uploaded](https://lists.manjaro.org/pipermail/manjaro-packages/Week-of-Mon-20160829/008394.html) and needed modifications [added](https://lists.manjaro.org/pipermail/manjaro-packages/Week-of-Mon-20160829/008395.html).

**Comment by mirh** [comment]
Mhh.. Just for the records, I [wouldn't](https://github.com/manjaro/manjaro-settings-manager/issues/84) know what's the deal in normal GUI, but at least in mhwd there's a [regression](https://github.com/manjaro/mhwd/issues/28).
