### ISSUE TITLE
andromeda for kde

### ISSUE THREAD

**Issue by udeved** [manjaro/release-plan#86]
My taste prefers heavily andromeda over maia theme. Never liked the dark greenish too much tbh.

What do you guys think? Should andromeda become default on plasma?

**Comment by philmmanjaro** [comment]
Is it ready and tested?

**Comment by udeved** [comment]
No idea if its deemed ready, but I use it on the laptop, and didn't notice big glitches. Also andromeda icons seem more complete.

**Comment by philmmanjaro** [comment]
will try to add it in my next dev-build ...
