### ISSUE TITLE
Add kernel 4.8

### ISSUE THREAD

**Issue by jonathonf** [manjaro/release-plan#87]
Kernel 4.8 is at rc6, but on unstable:

```bash
$ mhwd-kernel -l
available kernels:
   * linux310
   * linux312
   * linux314
   * linux316
   * linux318
   * linux41
   * linux44
   * linux46
   * linux47
   * linux-rt-lts-manjaro
   * linux-rt-manjaro
```

Kernel 4.8 should probably be added before the final rc.

**Comment by philmmanjaro** [comment]
Well, I can't adopt something which doesn't support all modules yet. Core part BFQ is not yet ported as the way we need it. Currently there is only a patch available to replace CFQ scheduler ...

**Comment by jonathonf** [comment]
Is it worth releasing a version to unstable that doesn't have all the normal Manjaro patches so e.g. working extramodules can be tested?

**Comment by philmmanjaro** [comment]
Seems there was [some work done](https://github.com/linusw/linux-bfq/compare/5924bbecd0267d87c24110cbe2041b5075173a25...e60fee8a1137975857e41069d06c40fe02b3a6db.patch), which I missed ...

**Comment by philmmanjaro** [comment]
... is in the works now. Let's see if its build. If not, I need another cup of tee ...

**Comment by philmmanjaro** [comment]
So far so good: ==> Finished making: linux48 4.8rc6-1 (Thu Sep 15 21:17:18 UTC 2016)
