### ISSUE TITLE
working tools for 16.10 release?

### ISSUE THREAD

**Issue by oberon2007** [manjaro/release-plan#89]
@philmmanjaro which combination of **mt** and profiles is to be used for the 16.10 release? I'm still seeing modifications going on. I think we need a stable version of the tools before we can think of a proper release. 16.8 was really chaotic and frustrating with different versions of the tools, separate branches of the profiles and even different boxit branches to be used for differnt tool versions.

**Comment by philmmanjaro** [comment]
Well, I'm still on the **mt-0.13.8** release and using the **16.10-dev** branch. For now it works. I still had no time to test **mt-0.14.x** yet. Seems we are currently a-sync in that regard.

**Comment by udeved** [comment]
mt-0.14 creates checksums for the sfs images now.
Add 
    checksum
to kernel args, and initramfs will check md5.
If it doesn't match, the iso will not boot.

**Comment by oberon2007** [comment]
cool!

**Comment by Ste74** [comment]
Marcus :D very nice function
 :D :D 
Il 21/ott/2016 13:15, udeved <notifications@github.com> ha scritto:mt-0.14 creates checksums for the sfs images now.
Add 
    checksum
to kernel args, and initramfs will check md5.
If it doesn't match, the iso will not boot.
