### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by philmmanjaro** [manjaro/release-plan#9]
decide how we should tag our install medias:

* manjaro-desktop-15.09-arch.iso
* manjaro-desktop-2015.09-arch.iso

**Comment by philmmanjaro** [comment]
Well, lets use **15.09**

**Comment by udeved** [comment]
I like, but keep in mind that its looks very similar to kde-apps release version.

**Comment by philmmanjaro** [comment]
Well, Ubuntu uses the same versioning. You see it in several projects nowadays ...
