### ISSUE TITLE
manjaro-settings-manager setfault

### ISSUE THREAD

**Issue by STiAT** [manjaro/release-plan#90]
see https://forum.manjaro.org/t/manjaro-settings-manager-segfault/11207

I decided today to ugprade, and decided I'll want to try again on my optimus hardware to use settings-manager to install the proprietary drivers.

>/usr/bin/manjaro-settings-manager: line 14:  1080 Segmentation fault      (core dumped) pkexec "$PROGRAM" "$@"

backtrace of manjaro-settings-manager-gui (including debugging symbols)
http://pastebin.com/0q6vZfQp

**Comment by Ste74** [comment]
Please, close this report and reopen on our bugtrucker. Github to report issue is deprecated. 
Il 19/ott/2016 10:20, STiAT <notifications@github.com> ha scritto:see https://forum.manjaro.org/t/manjaro-settings-manager-segfault/11207

I decided today to ugprade, and decided I'll want to try again on my optimus hardware to use settings-manager to install the proprietary drivers.


/usr/bin/manjaro-settings-manager: line 14:  1080 Segmentation fault      (core dumped) pkexec "$PROGRAM" "$@"


backtrace of manjaro-settings-manager-gui (including debugging symbols)
http://pastebin.com/0q6vZfQp

**Comment by STiAT** [comment]
Sorry, didn't know. Opened a report on the flyspray tracker.

**Comment by Ste74** [comment]
Don`t worry, no problem :)
Il 19/ott/2016 19:28, STiAT <notifications@github.com> ha scritto:Sorry, didn't know. Opened a report on the flyspray tracker.

**Comment by Ste74** [comment]
Maybe i can close
