### ISSUE TITLE
Unify Manjaro Icons to a set.

### ISSUE THREAD

**Issue by Tids** [manjaro/release-plan#92]
For the next release a good goal would be to

1. replace all the old Manjaro brandings with new ones (I'm working on this)
2. **unify all manjaro "own" icons to a small icon set that we can ship**

the secound one is a little harder and requires maybe some applications to change. Let me explain. The current situation is that some of Manjaros apps ships own logo-icons.
right now i've found:

/usr/share/about-distro/manjaro-logo.svg (kinfocenter)
/usr/share/icons/hicolor/48x48/apps/manjaro-welcome.png (manjaro-welcome)
/usr/share/icons/hicolor/scalable/apps/manjaro-settings-manager.svg (manjaro-settings-manager)

only in manjaros plasma edition. (Maybe there are more?) 
My idea would be to create a small set of "logo" files in different resolutions

```
/usr/share/icons/hicolor/16x16/apps/manjaro.png
/usr/share/icons/hicolor/22x22/apps/manjaro.png
/usr/share/icons/hicolor/32x32/apps/manjaro.png
/usr/share/icons/hicolor/48x48/apps/manjaro.png
/usr/share/icons/hicolor/64x64/apps/manjaro.png
/usr/share/icons/hicolor/128x128/apps/manjaro.png
/usr/share/icons/hicolor/scalable/apps/manjaro.svg(z)
```

and applications can just use the "manjaro" icon that now is provided by the icontheme instead of its own.

This would require that we ship that set preinstalled on all installationmedias.

On the pro-side 

- it would help a lot on branding-changes
- manjaro community editions with different logos could easily replace that set with an own set
- it would mostly kill blurry icons, since we have many resolutions and dont need to hardcode a single resolution only.

**Comment by Ste74** [comment]
I agree with this .. i like this idea to uniform logo style ( size , form and colour ) with the new maia color and with the new icon size of discourse forum .. example at the moment in mate edition i have used the icon .svg format provided via our vertex-maia-icon-theme because i not found other alternative .. 
But the .svg format is automatically scaled btw is possible use only this format ? Sorry for newbie question but i'm not a designer :\

**Comment by philmmanjaro** [comment]
What is the current status with this one? We also have to update the logos on our homepage and facebook if ready.

**Comment by oberon2007** [comment]
To be honest I had somehow missed this topic here... We have meanwhile updated icons in manjaro-welcome and msm without honoring the idea of a designed separate icon-pkg. I can have a look at this later today. Are there any other package except msm m-welcome and kinfocenter that need attention?

**Comment by oberon2007** [comment]
I see we also have:
``/usr/share/icons/logo5.png is owned by manjaro-artwork 1.0.8-2``

**Comment by oberon2007** [comment]
```
manjaro-artwork /usr/
manjaro-artwork /usr/share/
manjaro-artwork /usr/share/backgrounds/
manjaro-artwork /usr/share/backgrounds/Wallpaper-ST2-Black.jpg
manjaro-artwork /usr/share/backgrounds/Wallpaper-ST2-Blue.jpg
manjaro-artwork /usr/share/backgrounds/Wallpaper-ST2-Green.jpg
manjaro-artwork /usr/share/backgrounds/Wallpaper-ST2-Purple.jpg
manjaro-artwork /usr/share/backgrounds/Wallpaper-ST2-Red.jpg
manjaro-artwork /usr/share/backgrounds/manjaro.jpg
manjaro-artwork /usr/share/backgrounds/xfce/
manjaro-artwork /usr/share/backgrounds/xfce/Wallpaper-ST2-Black.jpg
manjaro-artwork /usr/share/backgrounds/xfce/Wallpaper-ST2-Blue.jpg
manjaro-artwork /usr/share/backgrounds/xfce/Wallpaper-ST2-Green.jpg
manjaro-artwork /usr/share/backgrounds/xfce/Wallpaper-ST2-Purple.jpg
manjaro-artwork /usr/share/backgrounds/xfce/Wallpaper-ST2-Red.jpg
manjaro-artwork /usr/share/backgrounds/xfce/manjaro.jpg
manjaro-artwork /usr/share/icons/
manjaro-artwork /usr/share/icons/logo5.png
manjaro-artwork /usr/share/icons/manjaro-logo.png
manjaro-artwork /usr/share/icons/manjaro.png
manjaro-artwork /usr/share/icons/whiskermenu-manjaro.svg
```

**Comment by oberon2007** [comment]
We should probably move all icons from the **manjaro-artwork** package to a separate icon-package and have all the apps depend on the icon package while using symlinks with the proper names in the app packages.

**Comment by oberon2007** [comment]
- I've created a [repo](https://github.com/oberon2007/manjaro-icons) on my github with the new icons in all sizes, @philmmanjaro maybe you want to fork it?
- The [**manjaro-icons** package](https://github.com/manjaro/packages-extra/commit/7c29d8e8326c6a4179c62a75888433750ca6e4ce) is already in unstable and
- used by [**manjaro-artwork**](https://github.com/manjaro/packages-extra/commit/30e73b4b47683a83b7cd4cbeea7f8dcdb0301345). This will also updates xfce4-whiskermenu icon via the new icon package.
- [**artwork-cinnamon**](https://github.com/manjaro/packages-community/commit/25fc785975733d9510e0600b97fff1bae51c2e2c) now also uses the depends and 
- **manjaro-welcome** is prepared: https://github.com/manjaro/packages-extra/commit/47307ac1a6113b91a8c51f31dac2468bf836cc75 together with https://github.com/manjaro/manjaro-welcome/pull/34
- for **manjaro-settings-manager** I left a [comment](https://github.com/manjaro/manjaro-settings-manager/commit/8d90a5384400183bcbc6ed3ee21b16207194315e#commitcomment-20062135) there about the possible procedure.

**Comment by Tids** [comment]
mostly a re-do of all things from manjaro/artworks
https://github.com/Tids/artworks

@oberon2007 for the standard icons of manjaro, could we use also *.svg icons for 16x16,32x32 and blah? Because the scaling is much better for smaller steps that we dont ship (22x22,24x24) and it should be supported by all the desktops out there. Also its easier to change *.svg then *.png ( i did that in here https://github.com/Tids/artworks/tree/master/icons/apps )

right now i have tried to re-create also all the templates as vectorgraphic instead of GIMP-files to have something that will work also on higher resolutions, if we need this.


Please also tell me if there is something missing.

**Comment by oberon2007** [comment]
Aren't **svg** scaled automatically (and that why they are called "scalable" :wink:? The **png** versions in different sizes are (theoretically) needed for applications that don't deal with vector icons. I think like that everything should be covered, no?

**Comment by Esclapion** [comment]
All applications I know can use svg. imho, we can replace all those sets of png by one light set of svg.

**Comment by oberon2007** [comment]
Well that's not entirely true because already **manjaro-welcome** and **msm** use both an svg and at least one or two different sized pngs as you can see in the updated PKGBUILDs. Also it will be nice to honor the icons used in existing installs and not just remove those icons. Like this they will just be replaced by the new one (via symlinks in **manjaro-artwork**. Also: Those files are so tiny, the whole pkg now is 9KB :laughing: I think it will not hurt to keep them in several sizes... :wink:

**Comment by philmmanjaro** [comment]
Now we almost finished the Icon-Switch to our new one. Maybe you guys also check our homepage and propose to me equals for the current ones by sending me the links to the new graphics.

**Comment by oberon2007** [comment]
The new logos are all in the [repo](https://github.com/oberon2007/manjaro-icons) linked above :wink: 
Also just sent a PR for **calamares**.
What's your preferred way? The one I proposed for [manajro-welcome](https://github.com/manjaro/manjaro-welcome/pull/34) or to actually replace the logo in the app, like in the calamares-PR?

**Comment by Tids** [comment]
I dont know why but the new maia icontheme has now again another color for the icons, wich is a bad thing
maia now:
![64x64](https://cloud.githubusercontent.com/assets/18744080/21466452/0c616738-c9cd-11e6-8437-b110ad4b0e55.png)
what i work with:
![logo64 svg](https://cloud.githubusercontent.com/assets/18744080/21466460/7c3428ac-c9cd-11e6-92d2-5425e64d902a.png)
Not a good idea to spread things again. I think it's @mcder3 s work so lets call him in and see xD ... we really need to adjust to "one style", "one color" or this will never end.

**Comment by mcder3** [comment]
I use the two colors, in the new theme of icons I used in the folders a green color that represents a Manjaro and in the color scheme the green color that was generated in Maia.

**Comment by philmmanjaro** [comment]
Hey David. All fine with that approach. We will figure it out.

**Comment by Tids** [comment]
since we have still a big difference in design: here are my guidelines 
[manjaro_style.zip](https://github.com/manjaro/release-plan/files/674849/manjaro_style.zip)
![style](https://cloud.githubusercontent.com/assets/18744080/21511727/9890ebd2-cca4-11e6-8002-112c5a9e58b3.png)
Its possible to change things but please dont adjust to a 200x200 logo, but to something more usefull. I'm not happy with the progress right now - that we have 2(or more) styles (in shape) and 2 colors.

Of course I can understand that one is the maia-fied color, but again why do we have 2 colors? If the current "manjaro-color" does not work for maia, lets change the color for everything to the maia-colors. Otherwise we have one color for the OS and a slightly different color for the website and stickers. That will look like "they're not done yet with artwork".

I'm not angry about something/someone here. I'ts just missing communication 😄

**Comment by mcder3** [comment]
I will not participate in the decision of which color will be at the end, depending on the decision taken, it could take me to adapt both a week and a month... so it has to be as soon as possible.

**Comment by mcder3** [comment]
I need them to solve the color problem as soon as possible, since it will be difficult to bring the changes in time for the next release.

In my opinion, the official color of manjaro is "#35BF5CFF" if the other environments have other colors is because of difficulties or because those who contribute consider that they would look better. Now in the case of "Manjaro Deepin" you can not ask him to change from blue to green because it is a very difficult job.

**Comment by Tids** [comment]
> In my opinion, the official color of manjaro is "#35BF5CFF"

true. thats also what i think it is

>  if the other environments have other colors is because of difficulties or because those who contribute consider that they would look better.

I'm also OK with this in case of Community-Editions. "Official"-Editions, on the other side, should have the same color, shape, textstyles, etc for the icons. As far as i can see right now we have 2 colors, 2 shapes atm.
![image](https://cloud.githubusercontent.com/assets/18744080/21569677/6326f636-cebf-11e6-9c09-2dc8ea7d3bcb.png)

is it OK for you when i suggest to use just my proposal @mcder3 @oberon2007 
[apps.zip](https://github.com/manjaro/release-plan/files/679008/apps.zip)? If you dont like them, I'm also OK to use one of yours as long as we have only one common style for everything 🙃

btw is there already an ETA/schedule for Manjaro 17.0?

**Comment by philmmanjaro** [comment]
Yes, we should have at least one shape. We should use one set of the logo, no matter on the used colour. We have one defined. If a different colour is needed, it is fine with me. However the shape should be final and we should update our logo then in [our repo](https://github.com/manjaro/artwork-logo). Please create a pull request for the review by our **artwork team**.

The release schedule is also [there](https://github.com/manjaro/release-plan/milestones) already.

**Comment by Kirek** [comment]
I think this is finished, or there are still some issues with the exact color/shape of the logo or other design guidelines?

**Comment by philmmanjaro** [comment]
I assume also that this is done by now ...

**Comment by oberon2007** [comment]
I'd say so, yes :)
