### ISSUE TITLE
sfs vs overlayfs

### ISSUE THREAD

**Issue by oberon2007** [manjaro/release-plan#93]
mt 0.14 default to sfs. What's the difference or advantage compared to overlayfs and which one should be use?

**Comment by Kirek** [comment]
They are different things, we always used various compressed squashfs images for our isos (root image, desktop, live...), and then we used aufs or overlayfs to mount those images overlaid, forming a single file structure.
I don't know how mt 0.14 handles it now, but if isn't using overlayfs it means there is only a single image.

**Comment by udeved** [comment]
Just file extension changed @Kirek 
iso initcpio hooks are in sync with arch, slightly modified, and I dropped isomounts file.

**Comment by oberon2007** [comment]
Thank you for the explanation @Kirek ! :)
