### ISSUE TITLE
[Plymouth] how do we want to handle themes?

### ISSUE THREAD

**Issue by udeved** [manjaro/release-plan#94]
I am not sure which package, but either plymouth or all theme packages miss a **libpng** depend.

**Comment by oberon2007** [comment]
Since all themes should normally be depending on **plymouth** already we can simply add the depends there.

**Comment by oberon2007** [comment]
libpng is in the dependency tree anyway:
plymouth < pango < cairo < libpng

**Comment by udeved** [comment]
Need to investigate.
Only plymouth in the live package list leads to errors when generating initcpio, complaining about missing libpng.

**Comment by udeved** [comment]
Here is the live packages list for manjaro-tools-0.14

Now question, can we simplify plymouth theme packages?
Probably create one theme package for manjaro, and somehow let a hook set a default theme?

As you can see, if you want a customized plymouth theme used for live session, you can't symlink the shared live list to the profile.
We have dozens of theme packages...

~~~
calamares-dev
manjaro-live-skel
>manjaro manjaro-syslinux-theme
mkinitcpio-nfs-utils
nbd
>openrc manjaro-live-openrc
>sonar sonar-calamares-branding
>sonar sonar-syslinux-theme
squashfs-tools
>systemd manjaro-live-systemd
>x86_64 manjaro-efi-utils
>manjaro_plymouth plymouth-theme-manjaro-elegant
>sonar_plymouth plymouth-theme-sonar-elegant
~~~

**Comment by udeved** [comment]
I think, no matter how we package them, plymouth themes should do the magic in a hook, and we can drop code that sets plymouth in buildiso.
This could also be done with DM themes.

**Comment by oberon2007** [comment]
How about the hook would check if only a single theme is currently installed and then configure **plymouth** accordingly? Like that whatever theme can just installed via package list and we are not limited to just one theme.

**Comment by Ste74** [comment]
I agree with it ... if is easy to do ... :) 

---

Greetings
Stefano Capitani

Il 2016-12-18 11:43 Bernhard Landauer ha scritto: 

> How about the hook would check if only a single theme is currently installed and then configure PLYMOUTH accordingly? Like that whatever theme can just installed via package list and we are not limited to just one theme. 
> 
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].
 

Links:
------
[1]
https://github.com/manjaro/release-plan/issues/94#issuecomment-267814379
[2]

**Comment by udeved** [comment]
I really would like to separate build tools from configuration tasks.
We basically need to decide if we package themes in one package, or if we keep one package per theme.
Besides that, we need a mechanism that sets the theme and eventual plymouth initcpio at package level, so buildiso doesn't have to care about plymouth theme, or later DM theme.

**Comment by udeved** [comment]
Do we have a plan to set plymouth theme with the concerning theme packages?
If so, mt-0.14 needs slight code changes.

**Comment by Ste74** [comment]
> I think, the easiest is to keep packages as they are, but add hook to set theme, or post_install scriptlet.

btw in my de profiles ( mate , gnome and budgie ) the combination of mt0.14 and pxe boot wrong the efi part ..

**Comment by udeved** [comment]
So guys, who is gonna do the plymouth theme setting?

I could make a hook, somebody needs to repackage all theme packages.

**Comment by oberon2007** [comment]
What is it exactly that needs to be changed in the theme packages?

**Comment by Ste74** [comment]
Plymouth theme auto installation ready 
 https://github.com/manjaro/packages-community/commit/7d898257a2e7623fb8ae0ef4d4a39ed28862e459
