### ISSUE TITLE
We should shift more config tasks at package level

### ISSUE THREAD

**Issue by udeved** [manjaro/release-plan#97]
Hi team,

in my view, if we look at arch linux, its puristic at package level in terms of configuring the system.

If we look at other distros, they almost all have some way to configure system stuff at package level, just different implementations and mechanisms.

Now, since we are based on arch linux, we historically had build tools do this kind of stuff, such as setting DM, plymouth for example, or enabling a service XY. Having tools do this stuff has multiple disadvantages. 
think, we should start to implement certain tasks at package level, let a given package XY set some config to XY instead of having external tools doing it. 

Let's use this issue to collect items we can do at package level:

- [x] plymouth theme
- [ ] plymouth initramfs activation
- [ ] DM themes

**Comment by Ste74** [comment]
Do you mean ? Example activate plymouth theme directly when user install a pkg plymouth-theme ?

**Comment by udeved** [comment]
Right @Ste74 
When a theme package is installed, all necessary settings wil be done, so we don't have to care about that in tools or CAL.

**Comment by Ste74** [comment]
Ok .. this leave the user free to adjust also the settings after install .. but we have to build a hooks to install/remove pkgs settings .. arch not provide it .. this is not a standard rule in arch ..

**Comment by udeved** [comment]
Yes @Ste74 , we need either hooks, or we do it postinstall in .install file.
And right, arch doesn't do it, but almost all other binary distros do such thing at package level.
We shouldn't rely on build tools or installer to configure this stuff.

**Comment by Ste74** [comment]
Via .install i can do but via hook i no idea .. if for other is ok no problem for me 😉

**Comment by Ste74** [comment]
Well , i want add new plymouth and wallpaper for gnome (a graphic user in our community work on it to match fine with our new official theme and suggest me ) so build with .install script to see and after rebuild all plymouth theme with this if you are agree ..

**Comment by Ste74** [comment]
I think also in this way is better if any plymouth theme have a dependence with plymouth theme default .. if user remove the theme and not install nothing the user have a fallback theme ..

**Comment by oberon2007** [comment]
If I'm not mistaken there is already some kind of a built in fallback image or so - maybe just try removing your only theme and check! :wink: To me it doesn't seem very logical to have one theme depend on another one that isn't actually needed and that I didn't choose to install. Also one can assume that people know what they are removing. Also: Once you remove the theme still nothing will stop you removing the depends of an uninstalled pkg... if you see what I mean :laughing:

**Comment by Ste74** [comment]
> If I'm not mistaken there is already some kind of a built in fallback image or so - maybe just try removing your only theme and check! 

Oh.. i have to check .. :)

> 😉 To me it doesn't seem very logical to have one theme depend on another one that isn't actually needed and that I didn't choose to install. Also one can assume that people know what they are removing. Also: Once you remove the theme still nothing will stop you removing the depends of an uninstalled pkg... if you see what I mean 😆

This is the arch way.. you are sure all people know how install or remove in general :p

**Comment by oberon2007** [comment]
As long as it doesn't prevent the system from booting it won't really be a problem.

**Comment by udeved** [comment]
The task would just shift from buildiso to the respective package. It doesn't make sense to have it take place at iso build time. The advantage of doing this at package level is, it will always work, also from repo as soon as the package gets installed, this the theme will be set and activated.

**Comment by Ste74** [comment]
All plymouth theme ready 
https://github.com/manjaro/packages-community/commit/7d898257a2e7623fb8ae0ef4d4a39ed28862e459

**Comment by udeved** [comment]
Very cool @Ste74.
Thanks for taking care of it. 😂

**Comment by udeved** [comment]
There is one more issue.
Do we also want to actually activate plymouth for initramfs by package?
Ie packages post_install add plymouth hook to mkinitcpio.conf?

**Comment by Ste74** [comment]
Yes , i have try to build an iso with plymouth in profile.conf disable .. Why only not leave the switch in the profile.conf Plymouth on / off ? If on only add plymouth hook into mkinitcpio or not ?

**Comment by udeved** [comment]
This is like it works currently @Ste74 
Just asked before I do mt-014 release.
If the package does it, we could also drop a CAL module besides buildiso code.

**Comment by Ste74** [comment]
> Ie packages post_install add plymouth hook to mkinitcpio.conf?
this in case plymouth pkgs active itself ? BTW create a metapkg to active it ?

**Comment by udeved** [comment]
If the **plymouth** package does it, we could also drop a CAL module besides buildiso code. ;)
The theme packages are fine I think.

**Comment by Ste74** [comment]
Ah i have missed that :p main plymouth pkgs are our overlay pkgs :)

**Comment by udeved** [comment]
Yes, we package plymouth already. 

What about DM service activation and DM themes?
We could do the same with DMs, but we don't package all of them.

**Comment by udeved** [comment]
I have added some possible plymouth activation/deactivation functions, untested, not used by plymouth.install.
https://github.com/manjaro/packages-extra/commit/9f5f49de275bcdad3d9322bb3e9914a0d673aef0

**Comment by Chrysostomus** [comment]
I second the motion to activate plymouth at package level, it would save me the work of implementing it in cli-installer. I would greatly appreciate this!

**Comment by jonathonf** [comment]
I'd recommend the use of a specific config package (e.g. `manjaro-config-plymouth`) rather than editing the upstream package for Manjaro. That also sets up a nice structure for other config packages that can be brought in as part of spin-specific metapackages.

**Comment by udeved** [comment]
Need help pls.

https://github.com/manjaro/release-plan/issues/91#issuecomment-276683036

**Comment by Ste74** [comment]
@udeved can build the new plymouth to try this during buildiso ? @philmmanjaro : i see plymouth is outdated in our repo .. i can rebuild with new version ?

**Comment by udeved** [comment]
Yes @Ste74 , please try.
We currently activate plymouth in buildiso for initramfs.
The code it put in plymouth package folder is unused so far.
We first need to decide if we want to activate plymouth by package, and then how. 
I would be in favour for doing this, probably as @jonathonf proposed.

**Comment by Ste74** [comment]
BTW : tried to build the plymouth pkg .. is normal the error during the initcpio build ? 
```

> stefano@ste74 plymouth]$ sudo pacman -U plymouth-1*
> caricamento dei pacchetti in corso...
> risoluzione delle dipendenze in corso...
> ricerca dei pacchetti in conflitto in corso...
> 
> Pacchetti (1) plymouth-1:0.8.8-3
> 
> Dimensione totale dei pacchetti da installare:  1,60 MiB
> 
> :: Vuoi procedere con l'installazione? [S/n] 
> (1/1) verifica delle chiavi presenti nel portachiavi            [##################################] 100%
> (1/1) verifica dell'integrità dei pacchetti                     [##################################] 100%
> (1/1) caricamento dei file dei pacchetti                        [##################################] 100%
> (1/1) controllo dei conflitti in corso                          [##################################] 100%
> (1/1) controllo dello spazio disponibile sul disco              [##################################] 100%
> :: Elaborazione delle modifiche al pacchetto...
> (1/1) installazione in corso di plymouth                        [##################################] 100%
> 
> ==================================================================================
> 1. To make Plymouth work:
>      1.1. Add "plymouth" to HOOKS after "base" and "udev" in /etc/mkinitcpio.conf
>      1.2. Add 'quiet splash' to the grub command line in /etc/default/grub
>      1.3. Rebuild your initrd image (# mkinitcpio -p [kernel preset name]).
>           E.g.: sudo mkinitcpio -p linux38
> 
> 2. To enable encryption, replace "encrypt" with "plymouth-encrypt" in
>    mkinitcpio.conf and rebuild your initrd image.
> 
> 3. You will also need to rebuild your initrd image every time you change your theme
>    (the default is set as 'spinfinity').
> 
>    To list all plymouth themes:
>        plymouth-set-default-theme -l
> 
>    To change theme:
>        # plymouth-set-default-theme <theme>
> 
>    To rebuild initrd image:
>        # mkinitcpio -p <kernel present name>
> 
> 4. For Smooth Transition to Display Manager you have to:
>      4.1. See the Wiki Page (link in 5) to prepare your Display Manager
>      4.2. Disable your Display Manager Unit
>           E.g. : systemctl disable kdm.service
>      4.3. Enable the respective DM-plymouth Unit (GDM,KDM,Lightdm,LXDM units provided)
>           E.g. : systemctl enable kdm-plymouth.service
> 
> 5. For more information please visit the Wiki page:
>    https://wiki.archlinux.org/index.php/Plymouth
> 
> OBS. If you have any leftover "kill Plymouth" lines in /etc/rc.local or ~/.xinitrc
>      they are no longer required.
> ==================================================================================
> 
> Dipendenze opzionali di plymouth
>     ttf-dejavu [installato]
> :: Esecuzione degli hook di post-transazione...
> (1/3) Updating linux48 initcpios
> ==> Building image from preset: /etc/mkinitcpio.d/linux48.preset: 'default'
>   -> -k /boot/vmlinuz-4.8-x86_64 -c /etc/mkinitcpio.conf -g /boot/initramfs-4.8-x86_64.img
> ==> Starting build: 4.8.17-1-MANJARO
>   -> Running build hook: [base]
>   -> Running build hook: [udev]
>   -> Running build hook: [plymouth]
> /usr/lib/initcpio/install/plymouth: riga 7: /usr/sbin/plymouth-set-default-theme: File o directory non esistente
> grep: /usr/share/plymouth/themes//.plymouth: File o directory non esistente
> ==> ERROR: file not found: `/usr/sbin/plymouthd'
> The default plymouth plugin () doesn't exist
> ==> Building image from preset: /etc/mkinitcpio.d/linux48.preset: 'fallback'
>   -> -k /boot/vmlinuz-4.8-x86_64 -c /etc/mkinitcpio.conf -g /boot/initramfs-4.8-x86_64-fallback.img -S autodetect
> ==> Starting build: 4.8.17-1-MANJARO
>   -> Running build hook: [base]
>   -> Running build hook: [udev]
>   -> Running build hook: [plymouth]
> /usr/lib/initcpio/install/plymouth: riga 7: /usr/sbin/plymouth-set-default-theme: File o directory non esistente
> grep: /usr/share/plymouth/themes//.plymouth: File o directory non esistente
> ==> ERROR: file not found: `/usr/sbin/plymouthd'
> The default plymouth plugin () doesn't exist
> errore: l'esecuzione del comando non è riuscita correttamente
> (2/3) Updating linux49 initcpios
> ==> Building image from preset: /etc/mkinitcpio.d/linux49.preset: 'default'
>   -> -k /boot/vmlinuz-4.9-x86_64 -c /etc/mkinitcpio.conf -g /boot/initramfs-4.9-x86_64.img
> ==> Starting build: 4.9.7-1-MANJARO
>   -> Running build hook: [base]
>   -> Running build hook: [udev]
>   -> Running build hook: [plymouth]
> /usr/lib/initcpio/install/plymouth: riga 7: /usr/sbin/plymouth-set-default-theme: File o directory non esistente
> grep: /usr/share/plymouth/themes//.plymouth: File o directory non esistente
> ==> ERROR: file not found: `/usr/sbin/plymouthd'
> The default plymouth plugin () doesn't exist
> ==> Building image from preset: /etc/mkinitcpio.d/linux49.preset: 'fallback'
>   -> -k /boot/vmlinuz-4.9-x86_64 -c /etc/mkinitcpio.conf -g /boot/initramfs-4.9-x86_64-fallback.img -S autodetect
> ==> Starting build: 4.9.7-1-MANJARO
>   -> Running build hook: [base]
>   -> Running build hook: [udev]
>   -> Running build hook: [plymouth]
> /usr/lib/initcpio/install/plymouth: riga 7: /usr/sbin/plymouth-set-default-theme: File o directory non esistente
> grep: /usr/share/plymouth/themes//.plymouth: File o directory non esistente
> ==> ERROR: file not found: `/usr/sbin/plymouthd'
> The default plymouth plugin () doesn't exist
> errore: l'esecuzione del comando non è riuscita correttamente
> (3/3) Arming ConditionNeedsUpdate...
> [stefano@ste74 plymouth]$ 
> 
```

this : 
 ==> ERROR: file not found: `/usr/sbin/plymouthd'

**Comment by Ste74** [comment]
Build a gnome iso from last your mt git , removed the plymouth from profile and all work fine 👍

**Comment by udeved** [comment]
Would be very nice to set plymouth activation in with package.

Example: 

We currently need to set two switches to build extra iso with plymouth.

* plymouth_boot=true
* extra=true

And other way round for disabled plymouth in basic config.

**Comment by Chrysostomus** [comment]
Separate config package like jonathon suggested would be great.

**Comment by oberon2007** [comment]
Since it doesn't make sense to have plymouth installed without using it, I think activation by package would be a good idea. Also it will be cool when people want to disable it they will just simply have to remove the package and it can do the rest. If the plan is to get rid of install scripts in the long run, should we use a hook instead? I can prepare that if you wish.

**Comment by udeved** [comment]
@philmmanjaro would have to be involved.
If we do it with hooks, the task can be split up onto different hooks already present. Grub hook comes to mind to set /etc/default/grub for example.

**Comment by Chrysostomus** [comment]
How would hooks handle multiple installed displaymanagers?

**Comment by udeved** [comment]
@Chrysostomus 

Either detect them, and if multiple detected, take last one found, or we build all relevant DMs ourselves.

**Comment by Chrysostomus** [comment]
Makes sense. I'm all for moving configuration to package level.

**Comment by udeved** [comment]
The beauty with hooks, we can deploy kind of hook addons to packages which come from arch upstream.

**Comment by Chrysostomus** [comment]
Yep, filtering is now fixed. It still thinks of them as runlevels

**Comment by oberon2007** [comment]
^ I think this was posted in the wrong repo, @Chrysostomus ... No problem, just so other people are not confused :wink:

**Comment by udeved** [comment]
So guys, could we make it so, that DM themes modify the config and set themselves with either alpm hook or post_install?

That would be of great usage for netinstalls, it wouldn't require CAL module changes.
