### ISSUE TITLE
Pacman files

### ISSUE THREAD

**Issue by agur4ik** [manjaro/release-plan#98]
As of pacman 5.0, there is a capability to search packages by files containing in them (`pacman -F`). It is used in Arch Linux repos (or just in their mirrors?) for a while already, but in Manjaro there are no files databases. As far as I remember they can simply be created by using `repo-add` from pacman >= 5.0. 

I know that there are third-party implementations for searching packages by files but isn't using a native solution better?

**Comment by Strit** [comment]
The manjaro tool for managing repo's (boxit) does not support this feature and would require mostly a rewrirte of the application to get it. That's why it's not in Manjaro.

**Comment by agur4ik** [comment]
Is there something Manjaro-specific in boxit that prevents replacing it by native pacman repo tool? I'm quite curious about it.

**Comment by Strit** [comment]
The code to Boxit is here, I don't know. Boxit is manjaro specific in general, so everything in Boxit is manjaro-specific.

It's a tool to manage the repo, which syncs with Arch repo, provides the overlay of manjaro specific packages and blacklists. I don't know much more than that.

**Comment by Strit** [comment]
For more info look at https://github.com/manjaro/boxit/issues/3

**Comment by agur4ik** [comment]
Thanks @Strit.

**Comment by Chrysostomus** [comment]
I looked into adding support for *.files in that script earlier, but did not have time to figure it out at the time. I hope someone can do it. It's silly that we don't support all the functions of our package manager.

**Comment by philmmanjaro** [comment]
This has to be added to **boxit**.

**Comment by Chrysostomus** [comment]
Excellent. I'll try to diff it with meld to see if the part generating the files can be ported.

**Comment by Chrysostomus** [comment]
Looking at the code, it seems boxit version of repo-add already has -f switch to generate .files. Does this not work?

**Comment by philmmanjaro** [comment]
fixed with https://github.com/manjaro/boxit/commit/67b8a8c8fadc154706cacbbfb00ba8a784d5d64a
